/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@nowlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38@sowlkettle.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@nowlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38@sowlkettle.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ;
typedef struct tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ;
typedef struct tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ;
typedef struct tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ_Content tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ_Content;
typedef struct tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg;
typedef struct tySequence__9b8bGX47ze3DmGLcMhkil5Q tySequence__9b8bGX47ze3DmGLcMhkil5Q;
typedef struct tySequence__9b8bGX47ze3DmGLcMhkil5Q_Content tySequence__9b8bGX47ze3DmGLcMhkil5Q_Content;
typedef struct tyObject_ViewablecolonObjectType___5ypD6KO2IGn9cE0Dd8dU9bCA tyObject_ViewablecolonObjectType___5ypD6KO2IGn9cE0Dd8dU9bCA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state_p0, void* ClE_0);
void* ClE_0;
} tyProc__tSwYc9c3RfPWZgS79a031fRA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ {
  NI len; tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ_Content* p;
};
struct tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg {
	RootObj Sup;
	tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w* widget;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ icons;
	NIM_BOOL darkTheme;
	tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ stylesheets;
};
struct tySequence__9b8bGX47ze3DmGLcMhkil5Q {
  NI len; tySequence__9b8bGX47ze3DmGLcMhkil5Q_Content* p;
};
struct tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg {
	tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg config;
	tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state;
	tySequence__9b8bGX47ze3DmGLcMhkil5Q startupEvents;
	tySequence__9b8bGX47ze3DmGLcMhkil5Q shutdownEvents;
};
struct tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w {
	RootObj Sup;
	tyObject_ViewablecolonObjectType___5ypD6KO2IGn9cE0Dd8dU9bCA* app;
};
struct tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ {
	RootObj Sup;
	tyObject_ViewablecolonObjectType___5ypD6KO2IGn9cE0Dd8dU9bCA* app;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ_Content { NI cap; tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ* data[SEQ_DECL_SIZE]; };
struct tySequence__9b8bGX47ze3DmGLcMhkil5Q_Content { NI cap; tyProc__tSwYc9c3RfPWZgS79a031fRA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_CDECL(void, gtk_init)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w*, eqdup___pkgZowlkettleZwidgetdef_u252)(tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w* src_p0, NIM_BOOL cyclic_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, at___pkgZowlkettle_u378)(NimStringV2* a_p0, NI a_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ, at___pkgZowlkettle_u398)(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ** a_p0, NI a_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ*, setupApp__pkgZowlkettleZmainloop_u124)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* config_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZowlkettle_u692)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ*, eqdup___pkgZowlkettleZwidgetdef_u80)(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* src_p0, NIM_BOOL cyclic_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__9b8bGX47ze3DmGLcMhkil5Q, at___pkgZowlkettle_u434)(tyProc__tSwYc9c3RfPWZgS79a031fRA* a_p0, NI a_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, execStartupEvents__pkgZowlkettle_u637)(tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg* context_p0);
N_LIB_PRIVATE N_NIMCALL(void, runMainloop__pkgZowlkettleZmainloop_u360)(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state_p0);
N_LIB_PRIVATE N_NIMCALL(void, execShutdownEvents__pkgZowlkettle_u683)(tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg* context_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettle_u728)(tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZwidgetdef_u73)(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettle_u695)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* dest_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
extern TNimTypeV2 NTIv2__d3JyYBq9cZSEhh9aSu6NKSzg_;
static NIM_CONST tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg TM__VTiXQbKeDMC62y9cSETFqNA_2 = {{{(&NTIv2__d3JyYBq9cZSEhh9aSu6NKSzg_)}, NIM_NIL, {0, NIM_NIL}, NIM_FALSE, {0, NIM_NIL}}, NIM_NIL, {0, NIM_NIL}, {0, NIM_NIL}}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, brew__pkgZowlkettle_u371)(tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w* widget_p0, NimStringV2* icons_p1, NI icons_p1Len_0, NIM_BOOL darkTheme_p2, tyProc__tSwYc9c3RfPWZgS79a031fRA* startupEvents_p3, NI startupEvents_p3Len_0, tyProc__tSwYc9c3RfPWZgS79a031fRA* shutdownEvents_p4, NI shutdownEvents_p4Len_0, tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ** stylesheets_p5, NI stylesheets_p5Len_0) {
	tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg config_1;
	tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w* colontmpD_;
	NIM_BOOL colontmpD__2;
	tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state_1;
	tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg context_1;
	tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* colontmpD__3;
	tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg blitTmp_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("brew", "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&config_1), sizeof(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg));
	config_1.Sup.m_type = (&NTIv2__d3JyYBq9cZSEhh9aSu6NKSzg_);
	colontmpD_ = NIM_NIL;
	colontmpD__2 = (NIM_BOOL)0;
	state_1 = NIM_NIL;
	nimZeroMem((void*)(&context_1), sizeof(tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg));
	context_1.config = TM__VTiXQbKeDMC62y9cSETFqNA_2.config;
	context_1.state = TM__VTiXQbKeDMC62y9cSETFqNA_2.state;
	context_1.startupEvents = TM__VTiXQbKeDMC62y9cSETFqNA_2.startupEvents;
	context_1.shutdownEvents = TM__VTiXQbKeDMC62y9cSETFqNA_2.shutdownEvents;
	colontmpD__3 = NIM_NIL;
	nimlf_(161, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle.nim");	gtk_init();
	nimln_(162);	config_1.Sup.m_type = (&NTIv2__d3JyYBq9cZSEhh9aSu6NKSzg_);
	nimln_(163);	nimlf_(78, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\widgetdef.nim");	colontmpD_ = eqdup___pkgZowlkettleZwidgetdef_u252(widget_p0, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	config_1.widget = colontmpD_;
	nimlf_(164, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle.nim");	config_1.icons = at___pkgZowlkettle_u378(icons_p1, icons_p1Len_0);
	nimln_(165);	colontmpD__2 = darkTheme_p2;
	config_1.darkTheme = colontmpD__2;
	nimln_(166);	config_1.stylesheets = at___pkgZowlkettle_u398(stylesheets_p5, stylesheets_p5Len_0);
	nimln_(169);	state_1 = setupApp__pkgZowlkettleZmainloop_u124((&config_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(171);	context_1.config = TM__VTiXQbKeDMC62y9cSETFqNA_2.config;
	context_1.state = TM__VTiXQbKeDMC62y9cSETFqNA_2.state;
	context_1.startupEvents = TM__VTiXQbKeDMC62y9cSETFqNA_2.startupEvents;
	context_1.shutdownEvents = TM__VTiXQbKeDMC62y9cSETFqNA_2.shutdownEvents;
	nimZeroMem((void*)(&blitTmp_1), sizeof(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg));
	blitTmp_1.Sup.m_type = (&NTIv2__d3JyYBq9cZSEhh9aSu6NKSzg_);
	nimln_(172);	blitTmp_1 = config_1;
	nimln_(162);	eqwasMoved___pkgZowlkettle_u692((&config_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	context_1.config = blitTmp_1;
	nimln_(173);	nimlf_(68, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\widgetdef.nim");	colontmpD__3 = eqdup___pkgZowlkettleZwidgetdef_u80(state_1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	context_1.state = colontmpD__3;
	nimlf_(174, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle.nim");	context_1.startupEvents = at___pkgZowlkettle_u434(startupEvents_p3, startupEvents_p3Len_0);
	nimln_(175);	context_1.shutdownEvents = at___pkgZowlkettle_u434(shutdownEvents_p4, shutdownEvents_p4Len_0);
	nimln_(177);	execStartupEvents__pkgZowlkettle_u637((&context_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(178);	runMainloop__pkgZowlkettleZmainloop_u360(state_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(179);	execShutdownEvents__pkgZowlkettle_u683((&context_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimln_(171);		eqdestroy___pkgZowlkettle_u728((&context_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(68, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\widgetdef.nim");		eqdestroy___pkgZowlkettleZwidgetdef_u73(state_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(162, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle.nim");		eqdestroy___pkgZowlkettle_u695((&config_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
