/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@nowlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38@sowlkettle@smainloop.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@nowlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38@sowlkettle@smainloop.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_GErrorObj__8Fbeg1Xd1z6er1elvlzfNg tyObject_GErrorObj__8Fbeg1Xd1z6er1elvlzfNg;
typedef struct tyObject_IOError__7e1hGsGCURJ49crk3N7NP2g tyObject_IOError__7e1hGsGCURJ49crk3N7NP2g;
typedef struct tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ tySequence__Eio1jF59abEpv9bLmutTDQvQ;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content;
typedef struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg;
typedef struct tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg;
typedef struct tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ;
typedef struct tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ_Content tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ_Content;
typedef struct tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg;
typedef struct tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg;
typedef struct tyTuple__R7ylOuMV2EoTykm7WC15Zw tyTuple__R7ylOuMV2EoTykm7WC15Zw;
typedef struct tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ;
typedef struct tyObject_GValue__3log3bGi9aBaKzbI4qnjlRw tyObject_GValue__3log3bGi9aBaKzbI4qnjlRw;
typedef struct tyObject_ViewablecolonObjectType___5ypD6KO2IGn9cE0Dd8dU9bCA tyObject_ViewablecolonObjectType___5ypD6KO2IGn9cE0Dd8dU9bCA;
typedef struct tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg;
typedef struct tySequence__9b8bGX47ze3DmGLcMhkil5Q tySequence__9b8bGX47ze3DmGLcMhkil5Q;
typedef struct tySequence__9b8bGX47ze3DmGLcMhkil5Q_Content tySequence__9b8bGX47ze3DmGLcMhkil5Q_Content;
typedef struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ {
  NI len; tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__Eio1jF59abEpv9bLmutTDQvQ trace;
	Exception* up;
};
struct tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA {
	Exception Sup;
};
struct tyObject_IOError__7e1hGsGCURJ49crk3N7NP2g {
	tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA Sup;
};
struct tyObject_GErrorObj__8Fbeg1Xd1z6er1elvlzfNg {
	NU32 domain;
	int code;
	NCSTRING message;
};
struct tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ {
	void* provider;
	NI priority;
};
struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg {
	NI rc;
	NI rootIdx;
};
struct tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ {
  NI len; tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg {
	RootObj Sup;
	tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w* widget;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ icons;
	NIM_BOOL darkTheme;
	tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ stylesheets;
};
struct tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg {
	NI len;
	NI cap;
	tyTuple__R7ylOuMV2EoTykm7WC15Zw* d;
};
struct tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg {
	tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q traceStack;
	tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
typedef NU64 tyArray__NzKR9bw29cLPrd712Xt6Liiw[2];
struct tyObject_GValue__3log3bGi9aBaKzbI4qnjlRw {
	size_t typ;
	tyArray__NzKR9bw29cLPrd712Xt6Liiw data;
};
struct tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ {
	RootObj Sup;
	tyObject_ViewablecolonObjectType___5ypD6KO2IGn9cE0Dd8dU9bCA* app;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state_p0, void* ClE_0);
void* ClE_0;
} tyProc__tSwYc9c3RfPWZgS79a031fRA;
struct tySequence__9b8bGX47ze3DmGLcMhkil5Q {
  NI len; tySequence__9b8bGX47ze3DmGLcMhkil5Q_Content* p;
};
struct tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg {
	tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg config;
	tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state;
	tySequence__9b8bGX47ze3DmGLcMhkil5Q startupEvents;
	tySequence__9b8bGX47ze3DmGLcMhkil5Q shutdownEvents;
};
typedef N_CLOSURE_PTR(void, TM__6X3lwOrRk1bjE4TSTx9acjQ_6) (tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state_p0);
typedef N_CLOSURE_PTR(void, TM__6X3lwOrRk1bjE4TSTx9acjQ_8) (tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state_p0);
struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content { NI cap; tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw data[SEQ_DECL_SIZE]; };
struct tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ_Content { NI cap; tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ* data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__9b8bGX47ze3DmGLcMhkil5Q_Content { NI cap; tyProc__tSwYc9c3RfPWZgS79a031fRA data[SEQ_DECL_SIZE]; };
N_CDECL(void*, gtk_css_provider_new)(void);
N_CDECL(int, gtk_css_provider_load_from_path)(void* cssProvider_p0, NCSTRING path_p1, tyObject_GErrorObj__8Fbeg1Xd1z6er1elvlzfNg** error_p2);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZmainloop_u9)(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ stylesheet_p0);
N_CDECL(void, g_object_unref)(void* obj_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZowlkettleZmainloop_u366)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettle_u695)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZmainloop_u234)(tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3734)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3431)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZowlkettle_u707)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u2971)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u2979)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
N_CDECL(void*, gtk_settings_get_default)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_GValue__3log3bGi9aBaKzbI4qnjlRw, g_value_new__pkgZowlkettleZbindingsZgtk_u2375)(NIM_BOOL value_p0);
N_CDECL(void, g_object_set_property)(void* obj_p0, NCSTRING name_p1, tyObject_GValue__3log3bGi9aBaKzbI4qnjlRw* value_p2);
N_CDECL(void, g_value_unset)(tyObject_GValue__3log3bGi9aBaKzbI4qnjlRw* value_p0);
N_CDECL(void*, gdk_display_get_default)(void);
N_CDECL(void*, gtk_icon_theme_get_for_display)(void* display_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_CDECL(void, gtk_icon_theme_add_search_path)(void* theme_p0, NCSTRING path_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ*, build__pkgZowlkettleZwidgetdef_u29)(tyObject_WidgetcolonObjectType___o9bcLE9cxXiD0OjqH5ftCo2w* widget_p0);
N_CDECL(void, gtk_style_context_add_provider_for_display)(void* display_p0, void* provider_p1, unsigned int priority_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
N_CDECL(void, gtk_window_present)(void* window_p0);
N_LIB_PRIVATE N_NIMCALL(void*, unwrapInternalWidget__pkgZowlkettleZwidgetdef_u231)(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state_p0);
N_CDECL(unsigned int, g_list_model_get_n_items)(void* list_p0);
N_CDECL(void*, gtk_window_get_toplevels)(void);
N_CDECL(int, g_main_context_iteration)(void* ctx_p0, int blocking_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettle_u585)(tySequence__9b8bGX47ze3DmGLcMhkil5Q dest_p0);
extern TNimTypeV2 NTIv2__7e1hGsGCURJ49crk3N7NP2g_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__d3JyYBq9cZSEhh9aSu6NKSzg_;
static const struct {
  NI cap; NIM_CHAR data[120+1];
} TM__6X3lwOrRk1bjE4TSTx9acjQ_3 = { 120 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__6X3lwOrRk1bjE4TSTx9acjQ_4 = {120, (NimStrPayload*)&TM__6X3lwOrRk1bjE4TSTx9acjQ_3};
static const NimStringV2 TM__6X3lwOrRk1bjE4TSTx9acjQ_5 = {120, (NimStrPayload*)&TM__6X3lwOrRk1bjE4TSTx9acjQ_3};
static const NimStringV2 TM__6X3lwOrRk1bjE4TSTx9acjQ_7 = {120, (NimStrPayload*)&TM__6X3lwOrRk1bjE4TSTx9acjQ_3};
static const NimStringV2 TM__6X3lwOrRk1bjE4TSTx9acjQ_9 = {120, (NimStrPayload*)&TM__6X3lwOrRk1bjE4TSTx9acjQ_3};
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
static NIM_CONST NU32 TM__6X3lwOrRk1bjE4TSTx9acjQ_2[2] = {3701606400, 1920098304};
N_LIB_PRIVATE TNimTypeV2 NTIv2__d3JyYBq9cZSEhh9aSu6NKSzg_ = {.destructor = (void*)rttiDestroy__pkgZowlkettleZmainloop_u366, .size = sizeof(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg), .align = (NI16) NIM_ALIGNOF(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg), .depth = 1, .display = TM__6X3lwOrRk1bjE4TSTx9acjQ_2, .traceImpl = (void*)eqtrace___pkgZowlkettle_u707, .flags = 0};
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ*, loadStylesheet__pkgZowlkettleZmainloop_u81)(NimStringV2 path_p0, NI priority_p1) {
	tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ* result;
	NI colontmpD_;
	tyObject_GErrorObj__8Fbeg1Xd1z6er1elvlzfNg* error_1;
	void* provider_1;
	int T1_;
	tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ* T7_;
	nimfr_("loadStylesheet", "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");
{	result = NIM_NIL;
	colontmpD_ = (NI)0;
	error_1 = (tyObject_GErrorObj__8Fbeg1Xd1z6er1elvlzfNg*)0;
	nimlf_(62, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");	provider_1 = gtk_css_provider_new();
	nimln_(63);	T1_ = (int)0;
	T1_ = gtk_css_provider_load_from_path(provider_1, nimToCStringConv(path_p0), &error_1);
	(void)(T1_);
	nimln_(64);	{
		tyObject_IOError__7e1hGsGCURJ49crk3N7NP2g* T6_;
		if (!!((error_1 == 0))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_IOError__7e1hGsGCURJ49crk3N7NP2g*) nimNewObj(sizeof(tyObject_IOError__7e1hGsGCURJ49crk3N7NP2g), NIM_ALIGNOF(tyObject_IOError__7e1hGsGCURJ49crk3N7NP2g));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__7e1hGsGCURJ49crk3N7NP2g_);
		(*T6_).Sup.Sup.name = "IOError";
		nimln_(65);		(*T6_).Sup.Sup.message = cstrToNimstr((*error_1).message);
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "IOError", "loadStylesheet", "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim", 65);
goto BeforeRet_;
	}
LA4_: ;
	nimln_(66);	T7_ = NIM_NIL;
	T7_ = (tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ*) nimNewObjUninit(sizeof(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ), NIM_ALIGNOF(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ));
	(*T7_).provider = provider_1;
	colontmpD_ = priority_p1;
	(*T7_).priority = colontmpD_;
	result = T7_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimlf_(364, "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");
	nimlf_(219, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");	result = NIM_FALSE;
	nimln_(220);	{
		tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(221);		nimln_(60);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T5_));
		nimln_(235);		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4))) == ((NI)0))) goto LA8_;
			nimln_(236);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(86);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZmainloop_u9)(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ stylesheet_p0) {
	nimfr_("=destroy", "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\common.nim");
{	nimlf_(34, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");	{
		if (!(stylesheet_p0.provider == 0)) goto LA3_;
		nimln_(35);		goto BeforeRet_;
	}
LA3_: ;
	nimln_(37);	g_object_unref(stylesheet_p0.provider);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZmainloop_u59)(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pkgZowlkettleZmainloop_u9((*dest_p0));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZmainloop_u234)(tySequence__Vio2vs9a8Y9bf9aHczk3uY1UQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLast(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
				eqdestroy___pkgZowlkettleZmainloop_u9((*dest_p0.p->data[colontmp_]));
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ*));
}
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimlf_(518, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T5_));
		nimlf_(521, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3431(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettle_u695)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* dest_p0) {
	eqdestroy___pkgZowlkettleZmainloop_u234((*dest_p0).stylesheets);
	eqdestroy___system_u3734((*dest_p0).icons);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).widget);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).widget);
	}
LA4_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZowlkettleZmainloop_u366)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pkgZowlkettle_u695(((tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimlf_(353, "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");	nimln_(357);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u2971)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "K:\\Progz\\nim-2.2.6\\lib\\system\\cellseqs_v2.nim");
	nimlf_(28, "K:\\Progz\\nim-2.2.6\\lib\\system\\cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u2979(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimlf_(138, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg*) (env_p1));
		nimln_(141);		add__system_u2971((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZowlkettle_u707)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).widget, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZowlkettleZmainloop_u56)(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ** dest_p0) {
	(*dest_p0) = 0;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	nimfr_("nimIncRef", "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");
	nimlf_(88, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");	nimln_(60);	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	nimln_(60);	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	(*((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T2_))).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZowlkettleZmainloop_u62)(tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ** dest_p0, tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pkgZowlkettleZmainloop_u9((*(*dest_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ*, setupApp__pkgZowlkettleZmainloop_u124)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* config_p0) {
	tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* result;
	void* display_1;
	void* iconTheme_1;
NIM_BOOL* nimErr_;
	nimfr_("setupApp", "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(92, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");	{
		void* settings_1;
		tyObject_GValue__3log3bGi9aBaKzbI4qnjlRw value_1;
		if (!(*config_p0).darkTheme) goto LA3_;
		nimln_(93);		settings_1 = gtk_settings_get_default();
		nimln_(94);		value_1 = g_value_new__pkgZowlkettleZbindingsZgtk_u2375((*config_p0).darkTheme);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(95);		g_object_set_property(settings_1, "gtk-application-prefer-dark-theme", (&value_1));
		nimln_(96);		g_value_unset((&value_1));
	}
LA3_: ;
	nimln_(98);	display_1 = gdk_display_get_default();
	nimln_(99);	iconTheme_1 = gtk_icon_theme_get_for_display(display_1);
	{
		NimStringV2* path_1;
		NI i_1;
		NI L_1;
		NI T6_;
		path_1 = (NimStringV2*)0;
		nimlf_(249, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T6_ = (*config_p0).icons.len;
		L_1 = T6_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA8;
				nimlf_(100, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");				if (i_1 < 0 || i_1 >= (*config_p0).icons.len){ raiseIndexError2(i_1,(*config_p0).icons.len-1); goto BeforeRet_;
				}
				path_1 = (&(*config_p0).icons.p->data[i_1]);
				nimln_(101);				gtk_icon_theme_add_search_path(iconTheme_1, nimToCStringConv((*path_1)));
				nimlf_(13, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T11_;
					T11_ = (*config_p0).icons.len;
					if (!!((T11_ == L_1))) goto LA12_;
					failedAssertImpl__stdZassertions_u234(TM__6X3lwOrRk1bjE4TSTx9acjQ_4);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA12_: ;
			} LA8: ;
		}
	}
	nimlf_(102, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");	result = build__pkgZowlkettleZwidgetdef_u29((*config_p0).widget);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ** stylesheet_1;
		NI i_2;
		NI L_2;
		NI T15_;
		stylesheet_1 = (tyObject_StylesheetObj__hSsr5ePBjFYaoUFA9aThHVQ**)0;
		nimlf_(249, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");		i_2 = ((NI)0);
		nimln_(250);		T15_ = (*config_p0).stylesheets.len;
		L_2 = T15_;
		{
			nimln_(251);			while (1) {
				if (!(i_2 < L_2)) goto LA17;
				nimlf_(104, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");				if (i_2 < 0 || i_2 >= (*config_p0).stylesheets.len){ raiseIndexError2(i_2,(*config_p0).stylesheets.len-1); goto BeforeRet_;
				}
				stylesheet_1 = &(*config_p0).stylesheets.p->data[i_2];
				nimln_(105);				gtk_style_context_add_provider_for_display(display_1, (*(*stylesheet_1)).provider, ((unsigned int) ((*(*stylesheet_1)).priority)));
				nimlf_(13, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");				i_2 += ((NI)1);
				nimln_(254);				{
					NI T20_;
					T20_ = (*config_p0).stylesheets.len;
					if (!!((T20_ == L_2))) goto LA21_;
					failedAssertImpl__stdZassertions_u234(TM__6X3lwOrRk1bjE4TSTx9acjQ_5);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA21_: ;
			} LA17: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZowlkettle_u692)(tyObject_AppConfig__d3JyYBq9cZSEhh9aSu6NKSzg* dest_p0) {
	(*dest_p0).widget = 0;
	(*dest_p0).icons.len = 0; (*dest_p0).icons.p = NIM_NIL;
	(*dest_p0).darkTheme = 0;
	(*dest_p0).stylesheets.len = 0; (*dest_p0).stylesheets.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettle_u524)(tyProc__tSwYc9c3RfPWZgS79a031fRA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).ClE_0);
	}
LA4_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZowlkettle_u521)(tyProc__tSwYc9c3RfPWZgS79a031fRA* dest_p0) {
	nimZeroMem((void*)(&(*dest_p0)), sizeof(tyProc__tSwYc9c3RfPWZgS79a031fRA));
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* h_1;
	NI T1_;
	nimfr_("nimIncRefCyclic", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimlf_(47, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	h_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T1_));
	nimlf_(48, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZowlkettle_u527)(tyProc__tSwYc9c3RfPWZgS79a031fRA* dest_p0, tyProc__tSwYc9c3RfPWZgS79a031fRA src_p1, NIM_BOOL cyclic_p2) {
	void* colontmp_;
	colontmp_ = (*dest_p0).ClE_0;
	{
		if (!src_p1.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p1.ClE_0, cyclic_p2);
	}
LA3_: ;
	(*dest_p0).ClE_0 = src_p1.ClE_0;
	(*dest_p0).ClP_0 = src_p1.ClP_0;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, execStartupEvents__pkgZowlkettle_u637)(tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg* context_p0) {
NIM_BOOL* nimErr_;
	nimfr_("execStartupEvents", "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");
{nimErr_ = nimErrorFlag();
	{
		tyProc__tSwYc9c3RfPWZgS79a031fRA* event_1;
		NI i_1;
		NI L_1;
		NI T2_;
		event_1 = (tyProc__tSwYc9c3RfPWZgS79a031fRA*)0;
		nimlf_(249, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = (*context_p0).startupEvents.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(84, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");				if (i_1 < 0 || i_1 >= (*context_p0).startupEvents.len){ raiseIndexError2(i_1,(*context_p0).startupEvents.len-1); goto BeforeRet_;
				}
				event_1 = (&(*context_p0).startupEvents.p->data[i_1]);
				nimln_(85);				(*event_1).ClE_0? (*event_1).ClP_0((*context_p0).state, (*event_1).ClE_0):((TM__6X3lwOrRk1bjE4TSTx9acjQ_6)((*event_1).ClP_0))((*context_p0).state);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T7_;
					T7_ = (*context_p0).startupEvents.len;
					if (!!((T7_ == L_1))) goto LA8_;
					failedAssertImpl__stdZassertions_u234(TM__6X3lwOrRk1bjE4TSTx9acjQ_7);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA8_: ;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, runMainloop__pkgZowlkettleZmainloop_u360)(tyObject_WidgetStatecolonObjectType___IHcHXiQd8FLGhqit6GwFmQ* state_p0) {
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("runMainloop", "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(112, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");	T1_ = (void*)0;
	T1_ = unwrapInternalWidget__pkgZowlkettleZwidgetdef_u231(state_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	gtk_window_present(T1_);
	{
		nimln_(113);		while (1) {
			void* T4_;
			unsigned int T5_;
			int T6_;
			T4_ = (void*)0;
			T4_ = gtk_window_get_toplevels();
			T5_ = (unsigned int)0;
			T5_ = g_list_model_get_n_items(T4_);
			if (!((NU32)(((NU32)0)) < (NU32)(T5_))) goto LA3;
			nimln_(114);			T6_ = (int)0;
			T6_ = g_main_context_iteration(((void*) (NIM_NIL)), ((int)1));
			(void)(T6_);
		} LA3: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, execShutdownEvents__pkgZowlkettle_u683)(tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg* context_p0) {
NIM_BOOL* nimErr_;
	nimfr_("execShutdownEvents", "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");
{nimErr_ = nimErrorFlag();
	{
		tyProc__tSwYc9c3RfPWZgS79a031fRA* event_1;
		NI i_1;
		NI L_1;
		NI T2_;
		event_1 = (tyProc__tSwYc9c3RfPWZgS79a031fRA*)0;
		nimlf_(249, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = (*context_p0).shutdownEvents.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(88, "C:\\Users\\n1ght\\.nimble\\pkgs2\\owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38\\owlkettle\\mainloop.nim");				if (i_1 < 0 || i_1 >= (*context_p0).shutdownEvents.len){ raiseIndexError2(i_1,(*context_p0).shutdownEvents.len-1); goto BeforeRet_;
				}
				event_1 = (&(*context_p0).shutdownEvents.p->data[i_1]);
				nimln_(89);				(*event_1).ClE_0? (*event_1).ClP_0((*context_p0).state, (*event_1).ClE_0):((TM__6X3lwOrRk1bjE4TSTx9acjQ_8)((*event_1).ClP_0))((*context_p0).state);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T7_;
					T7_ = (*context_p0).shutdownEvents.len;
					if (!!((T7_ == L_1))) goto LA8_;
					failedAssertImpl__stdZassertions_u234(TM__6X3lwOrRk1bjE4TSTx9acjQ_9);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA8_: ;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettle_u728)(tyObject_AppContext__yHxZK9cu7wXISHpmZUJybAg* dest_p0) {
	eqdestroy___pkgZowlkettle_u585((*dest_p0).shutdownEvents);
	eqdestroy___pkgZowlkettle_u585((*dest_p0).startupEvents);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).state);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).state);
	}
LA4_: ;
	eqdestroy___pkgZowlkettleZmainloop_u234((*dest_p0).config.stylesheets);
	eqdestroy___system_u3734((*dest_p0).config.icons);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).config.widget);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).config.widget);
	}
LA9_: ;
}
