/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@powlkettleEnhanced@senhance.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@powlkettleEnhanced@senhance.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw;
typedef struct tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg;
typedef struct tySequence__9clQuZ6vR9aegLYewjCfDuSQ tySequence__9clQuZ6vR9aegLYewjCfDuSQ;
typedef struct tySequence__9clQuZ6vR9aegLYewjCfDuSQ_Content tySequence__9clQuZ6vR9aegLYewjCfDuSQ_Content;
typedef struct tySequence__PeOPK4xtHMbHys9bYUhFLJg tySequence__PeOPK4xtHMbHys9bYUhFLJg;
typedef struct tySequence__PeOPK4xtHMbHys9bYUhFLJg_Content tySequence__PeOPK4xtHMbHys9bYUhFLJg_Content;
typedef struct tyTuple__fXFNu89aKPinEjbDbEkRPCg tyTuple__fXFNu89aKPinEjbDbEkRPCg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw {
	NIM_BOOL disableTitlebar;
	NIM_BOOL useThemeStylesheet;
	NIM_BOOL disableStretchingBoxes;
};
typedef NU8 tyEnum_JsonNodeKind__pIgEqBN9caKLXmVQcXgyYkg;
struct tySequence__9clQuZ6vR9aegLYewjCfDuSQ {
  NI len; tySequence__9clQuZ6vR9aegLYewjCfDuSQ_Content* p;
};
struct tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg {
	tySequence__9clQuZ6vR9aegLYewjCfDuSQ data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__PeOPK4xtHMbHys9bYUhFLJg {
  NI len; tySequence__PeOPK4xtHMbHys9bYUhFLJg_Content* p;
};
struct tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__pIgEqBN9caKLXmVQcXgyYkg kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg fields;
} _kind_6;
	struct {
	tySequence__PeOPK4xtHMbHys9bYUhFLJg elems;
} _kind_7;
};
};
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NimStringV2 tyArray__haiLFy0nBviVTKFGuwztzQ[5];
struct tyTuple__fXFNu89aKPinEjbDbEkRPCg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* Field3;
};
struct tySequence__9clQuZ6vR9aegLYewjCfDuSQ_Content { NI cap; tyTuple__fXFNu89aKPinEjbDbEkRPCg data[SEQ_DECL_SIZE]; };
struct tySequence__PeOPK4xtHMbHys9bYUhFLJg_Content { NI cap; tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw, defaultOwlkettleEnhanceConfig__OOZOOZOOZsrcZowlkettle69nhancedZenhance_u6)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw*, loadConfigNode__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u86)(NimStringV2 pathOfConfig_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, asBoolOr__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u105)(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* n_p0, NIM_BOOL d_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw*, pickNode__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u93)(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* n_p0, NimStringV2* keys_p1, NI keys_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_3 = { 16 | NIM_STRLIT_FLAG, "disable_titlebar" };
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_4 = { 15 | NIM_STRLIT_FLAG, "disableTitlebar" };
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_5 = { 16 | NIM_STRLIT_FLAG, "disable titlebar" };
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_7 = { 20 | NIM_STRLIT_FLAG, "use_theme_stylesheet" };
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_8 = { 18 | NIM_STRLIT_FLAG, "useThemeStylesheet" };
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_9 = { 20 | NIM_STRLIT_FLAG, "use theme stylesheet" };
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_11 = { 24 | NIM_STRLIT_FLAG, "disable_stretching_boxes" };
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_12 = { 22 | NIM_STRLIT_FLAG, "disableStretchingBoxes" };
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_13 = { 24 | NIM_STRLIT_FLAG, "disable stretching boxes" };
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_14 = { 22 | NIM_STRLIT_FLAG, "disable_stretch_layout" };
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__sVUNC8LZTLeNYA3oivpN9cw_15 = { 20 | NIM_STRLIT_FLAG, "disableStretchLayout" };
static NIM_CONST tyArray__24KAM9afIUgUaqBaEBB6r9bg TM__sVUNC8LZTLeNYA3oivpN9cw_2 = {{16, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_3},
{15, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_4},
{16, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_5}}
;
static NIM_CONST tyArray__24KAM9afIUgUaqBaEBB6r9bg TM__sVUNC8LZTLeNYA3oivpN9cw_6 = {{20, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_7},
{18, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_8},
{20, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_9}}
;
static NIM_CONST tyArray__haiLFy0nBviVTKFGuwztzQ TM__sVUNC8LZTLeNYA3oivpN9cw_10 = {{24, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_11},
{22, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_12},
{24, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_13},
{22, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_14},
{20, (NimStrPayload*)&TM__sVUNC8LZTLeNYA3oivpN9cw_15}}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw, defaultOwlkettleEnhanceConfig__OOZOOZOOZsrcZowlkettle69nhancedZenhance_u6)(void) {
	tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw result;
	nimfr_("defaultOwlkettleEnhanceConfig", "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\enhance.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw));
	nimlf_(17, "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\enhance.nim");	result.disableTitlebar = NIM_FALSE;
	nimln_(18);	result.useThemeStylesheet = NIM_TRUE;
	nimln_(19);	result.disableStretchingBoxes = NIM_TRUE;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw, enhance__OOZOOZOOZsrcZowlkettle69nhancedZenhance_u8)(NimStringV2 pathOfConfig_p0) {
	tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw result;
	tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* n_1;
	tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* colontmpD_;
	tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* colontmpD__2;
	tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* colontmpD__3;
	tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw cfg_1;
	NIM_BOOL T2_;
	NIM_BOOL T3_;
	NIM_BOOL T4_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("enhance", "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\enhance.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_OwlkettleEnhanceConfig__ZpEwiuerosuZamUv8pVyOw));
	n_1 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	nimln_(25);	cfg_1 = defaultOwlkettleEnhanceConfig__OOZOOZOOZsrcZowlkettle69nhancedZenhance_u6();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(26);	n_1 = loadConfigNode__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u86(pathOfConfig_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(28);	nimln_(29);	colontmpD_ = pickNode__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u93(n_1, TM__sVUNC8LZTLeNYA3oivpN9cw_2, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(28);	T2_ = (NIM_BOOL)0;
	T2_ = asBoolOr__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u105(colontmpD_, cfg_1.disableTitlebar);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	cfg_1.disableTitlebar = T2_;
	nimln_(37);	nimln_(38);	colontmpD__2 = pickNode__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u93(n_1, TM__sVUNC8LZTLeNYA3oivpN9cw_6, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(37);	T3_ = (NIM_BOOL)0;
	T3_ = asBoolOr__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u105(colontmpD__2, cfg_1.useThemeStylesheet);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	cfg_1.useThemeStylesheet = T3_;
	nimln_(46);	nimln_(47);	colontmpD__3 = pickNode__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u93(n_1, TM__sVUNC8LZTLeNYA3oivpN9cw_10, 5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(46);	T4_ = (NIM_BOOL)0;
	T4_ = asBoolOr__OOZOOZOOZsrcZlibZlevel0Zconfig95source95parser_u105(colontmpD__3, cfg_1.disableStretchingBoxes);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	cfg_1.disableStretchingBoxes = T4_;
	nimln_(57);	result = cfg_1;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(934, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(n_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
