/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@powlkettleEnhanced@sshared@sui_helpers.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@powlkettleEnhanced@sshared@sui_helpers.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NimStringV2 tyArray__haiLFy0nBviVTKFGuwztzQ[5];
typedef NimStringV2 tyArray__yt5VDPNtUGx9cBkOVakHwdQ[6];
typedef NimStringV2 tyArray__DLxB9cOndPvLDyky9bY9ccM3g[7];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2661)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NimStringV2, X5BX5D___OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u179)(tyArray__sMpvt1sOxOJ3LFGulnbeMQ a_p0, NI i_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppDir)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPathOpenArray)(NimStringV2* parts_p0, NI parts_p0Len_0);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3734)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_2 = { 8 | NIM_STRLIT_FLAG, "Overview" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_3 = { 9 | NIM_STRLIT_FLAG, "Workspace" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_4 = { 7 | NIM_STRLIT_FLAG, "Metrics" };
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_5 = { 12 | NIM_STRLIT_FLAG, "Docs / Notes" };
static const struct {
  NI cap; NIM_CHAR data[47+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_8 = { 47 | NIM_STRLIT_FLAG, "Custom-titlebar dashboard with Atlas-like grid." };
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_9 = { 34 | NIM_STRLIT_FLAG, "Board + properties + split queues." };
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_10 = { 37 | NIM_STRLIT_FLAG, "Operational performance and controls." };
static const struct {
  NI cap; NIM_CHAR data[40+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_11 = { 40 | NIM_STRLIT_FLAG, "Implementation notes and file structure." };
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_12 = { 29 | NIM_STRLIT_FLAG, "assets/themes/theme_white.css" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_13 = {29, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_12};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_14 = { 32 | NIM_STRLIT_FLAG, "../assets/themes/theme_white.css" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_15 = {32, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_14};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_16 = { 35 | NIM_STRLIT_FLAG, "../../assets/themes/theme_white.css" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_17 = {35, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_16};
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_18 = { 38 | NIM_STRLIT_FLAG, "../../../assets/themes/theme_white.css" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_19 = {38, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_18};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_20 = { 6 | NIM_STRLIT_FLAG, "assets" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_21 = {6, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_20};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_22 = { 6 | NIM_STRLIT_FLAG, "themes" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_23 = {6, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_22};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_24 = { 15 | NIM_STRLIT_FLAG, "theme_white.css" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_25 = {15, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_24};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_26 = { 2 | NIM_STRLIT_FLAG, ".." };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_27 = {2, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_26};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_28 = {6, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_20};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_29 = {6, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_22};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_30 = {15, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_24};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_31 = {2, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_26};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_32 = {2, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_26};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_33 = {6, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_20};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_34 = {6, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_22};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_35 = {15, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_24};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_36 = {2, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_26};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_37 = {2, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_26};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_38 = {2, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_26};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_39 = {6, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_20};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_40 = {6, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_22};
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_41 = {15, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_24};
static const struct {
  NI cap; NIM_CHAR data[120+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_42 = { 120 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_43 = {120, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_42};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__mFLEL2Shy1e9caFDF9bVxpHQ_44 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__mFLEL2Shy1e9caFDF9bVxpHQ_45 = {0, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_44};
N_LIB_PRIVATE NIM_CONST tyArray__sMpvt1sOxOJ3LFGulnbeMQ OwlPageNames__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u2 = {{8, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_2},
{9, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_3},
{7, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_4},
{12, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_5}}
;
N_LIB_PRIVATE NIM_CONST tyArray__sMpvt1sOxOJ3LFGulnbeMQ OwlCustomPageTaglines__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u4 = {{47, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_8},
{34, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_9},
{37, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_10},
{40, (NimStrPayload*)&TM__mFLEL2Shy1e9caFDF9bVxpHQ_11}}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
static N_INLINE(NimStringV2, X5BX5D___OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u179)(tyArray__sMpvt1sOxOJ3LFGulnbeMQ a_p0, NI i_p1) {
	NimStringV2 result;
	NI TM__mFLEL2Shy1e9caFDF9bVxpHQ_6;
	NI TM__mFLEL2Shy1e9caFDF9bVxpHQ_7;
	nimfr_("[]", "K:\\Progz\\nim-2.2.6\\lib\\system\\indices.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");	nimlf_(26, "K:\\Progz\\nim-2.2.6\\lib\\system\\indices.nim");	if (nimSubInt(((NI)4), i_p1, &TM__mFLEL2Shy1e9caFDF9bVxpHQ_6)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__mFLEL2Shy1e9caFDF9bVxpHQ_6), ((NI)0), &TM__mFLEL2Shy1e9caFDF9bVxpHQ_7)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__mFLEL2Shy1e9caFDF9bVxpHQ_7)) < ((NI)0) || ((NI)(TM__mFLEL2Shy1e9caFDF9bVxpHQ_7)) > ((NI)3)){ raiseRangeErrorI((NI)(TM__mFLEL2Shy1e9caFDF9bVxpHQ_7), ((NI)0), ((NI)3)); goto BeforeRet_;
	}
	nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");	eqcopy___system_u2661((&result), a_p0[(((NI)(TM__mFLEL2Shy1e9caFDF9bVxpHQ_7)))- 0]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, pageTitle__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u168)(NI i_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("pageTitle", "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(57, "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= i_p0);
		if (!(T3_)) goto LA4_;
		T3_ = (i_p0 < ((NI)4));
LA4_: ;
		if (!T3_) goto LA5_;
		nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		if ((NU)(i_p0) > (NU)(3)){ raiseIndexError2(i_p0, 3); goto BeforeRet_;
		}
		eqcopy___system_u2661((&result), OwlPageNames__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u2[(i_p0)- 0]);
	}
	goto LA1_;
LA5_: ;
	{
		nimlf_(60, "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");		result = X5BX5D___OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u179(OwlPageNames__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u2, ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, pageTaglineCustom__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u230)(NI i_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("pageTaglineCustom", "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(71);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= i_p0);
		if (!(T3_)) goto LA4_;
		T3_ = (i_p0 < ((NI)4));
LA4_: ;
		if (!T3_) goto LA5_;
		nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		if ((NU)(i_p0) > (NU)(3)){ raiseIndexError2(i_p0, 3); goto BeforeRet_;
		}
		eqcopy___system_u2661((&result), OwlCustomPageTaglines__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u4[(i_p0)- 0]);
	}
	goto LA1_;
LA5_: ;
	{
		nimlf_(74, "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");		result = X5BX5D___OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u179(OwlCustomPageTaglines__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u4, ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, presetToSliderValue__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u165)(NI i_p0) {
	NF result;
	nimfr_("presetToSliderValue", "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");
	nimln_(45);	switch (i_p0) {
	case ((NI)0):
	{
		nimln_(47);		result = 15.0;
	}
	break;
	case ((NI)1):
	{
		nimln_(49);		result = 50.0;
	}
	break;
	case ((NI)2):
	{
		nimln_(51);		result = 85.0;
	}
	break;
	default:
	{
		nimln_(53);		result = 42.0;
	}
	break;
	}
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "K:\\Progz\\nim-2.2.6\\lib\\system.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, resolveStylesheetPath__OOZOOZOOZsrcZowlkettle69nhancedZsharedZui95helpers_u5)(void) {
	NimStringV2 result;
	NimStringV2 t0_1;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ ts_1;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ T2_;
	NimStringV2 T3_;
	tyArray__haiLFy0nBviVTKFGuwztzQ T4_;
	NimStringV2 T5_;
	tyArray__yt5VDPNtUGx9cBkOVakHwdQ T6_;
	NimStringV2 T7_;
	tyArray__DLxB9cOndPvLDyky9bY9ccM3g T8_;
	NimStringV2 T9_;
NIM_BOOL* nimErr_;
	nimfr_("resolveStylesheetPath", "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	t0_1.len = 0; t0_1.p = NIM_NIL;
	ts_1.len = 0; ts_1.p = NIM_NIL;
	nimln_(27);	t0_1 = nosgetAppDir();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(28);	ts_1.len = 8; ts_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(8, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	ts_1.p->data[0] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_13;
	ts_1.p->data[1] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_15;
	ts_1.p->data[2] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_17;
	ts_1.p->data[3] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_19;
	nimln_(33);	T2_[0] = t0_1;
	T2_[1] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_21;
	T2_[2] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_23;
	T2_[3] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_25;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = nosjoinPathOpenArray(T2_, 4);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T3_); goto LA1_;}
	ts_1.p->data[4] = T3_;
	nimln_(34);	T4_[0] = t0_1;
	T4_[1] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_27;
	T4_[2] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_28;
	T4_[3] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_29;
	T4_[4] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_30;
	T5_.len = 0; T5_.p = NIM_NIL;
	T5_ = nosjoinPathOpenArray(T4_, 5);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T5_); goto LA1_;}
	ts_1.p->data[5] = T5_;
	nimln_(35);	T6_[0] = t0_1;
	T6_[1] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_31;
	T6_[2] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_32;
	T6_[3] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_33;
	T6_[4] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_34;
	T6_[5] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_35;
	T7_.len = 0; T7_.p = NIM_NIL;
	T7_ = nosjoinPathOpenArray(T6_, 6);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T7_); goto LA1_;}
	ts_1.p->data[6] = T7_;
	nimln_(36);	T8_[0] = t0_1;
	T8_[1] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_36;
	T8_[2] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_37;
	T8_[3] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_38;
	T8_[4] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_39;
	T8_[5] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_40;
	T8_[6] = TM__mFLEL2Shy1e9caFDF9bVxpHQ_41;
	T9_.len = 0; T9_.p = NIM_NIL;
	T9_ = nosjoinPathOpenArray(T8_, 7);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T9_); goto LA1_;}
	ts_1.p->data[7] = T9_;
	{
		NimStringV2* t_1;
		NI i_1;
		NI L_1;
		NI T11_;
		t_1 = (NimStringV2*)0;
		nimlf_(249, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T11_ = ts_1.len;
		L_1 = T11_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA13;
				nimlf_(38, "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");				if (i_1 < 0 || i_1 >= ts_1.len){ raiseIndexError2(i_1,ts_1.len-1); goto LA1_;
				}
				t_1 = (&ts_1.p->data[i_1]);
				nimln_(39);				{
					NIM_BOOL T16_;
					T16_ = (NIM_BOOL)0;
					T16_ = nosfileExists((*t_1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T16_) goto LA17_;
					nimln_(40);					nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");					eqcopy___system_u2661((&result), (*t_1));
					nimln_(2128);					eqdestroy___system_u3734(ts_1);
					nimln_(394);					if (t0_1.p && !(t0_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(t0_1.p);
}
					goto BeforeRet_;
				}
LA17_: ;
				nimlf_(13, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T21_;
					T21_ = ts_1.len;
					if (!!((T21_ == L_1))) goto LA22_;
					failedAssertImpl__stdZassertions_u234(TM__mFLEL2Shy1e9caFDF9bVxpHQ_43);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA22_: ;
			} LA13: ;
		}
	}
	nimlf_(41, "f:\\CodingMain\\proto-ViableNimUIs\\src\\owlkettleEnhanced\\shared\\ui_helpers.nim");	result = TM__mFLEL2Shy1e9caFDF9bVxpHQ_45;
	{
		LA1_:;
	}
	{
		nimlf_(2128, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		eqdestroy___system_u3734(ts_1);
		nimln_(394);		if (t0_1.p && !(t0_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(t0_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
