/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@psets.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@psets.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw;
typedef struct tyObject_NimRawSeq__jJwHR8yLLwvKfi1jy4PrXw tyObject_NimRawSeq__jJwHR8yLLwvKfi1jy4PrXw;
typedef struct tySequence__obI9bdO3X9b7Cr16WOB6i6qw tySequence__obI9bdO3X9b7Cr16WOB6i6qw;
typedef struct tySequence__obI9bdO3X9b7Cr16WOB6i6qw_Content tySequence__obI9bdO3X9b7Cr16WOB6i6qw_Content;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg;
typedef struct tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg;
typedef struct tyTuple__R7ylOuMV2EoTykm7WC15Zw tyTuple__R7ylOuMV2EoTykm7WC15Zw;
typedef struct tyTuple__p6sxP3CYOYBGz8nnL1OXGQ tyTuple__p6sxP3CYOYBGz8nnL1OXGQ;
typedef struct tyObject_TextBufferEventObj__8t5KEL9cln9cTzko48rumWDg tyObject_TextBufferEventObj__8t5KEL9cln9cTzko48rumWDg;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ tySequence__8Np6tlClE5az1CyqZdN19bQ;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content tySequence__8Np6tlClE5az1CyqZdN19bQ_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A;
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
struct tyObject_NimRawSeq__jJwHR8yLLwvKfi1jy4PrXw {
	NI len;
	void* p;
};
struct tySequence__obI9bdO3X9b7Cr16WOB6i6qw {
  NI len; tySequence__obI9bdO3X9b7Cr16WOB6i6qw_Content* p;
};
struct tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg {
	NI len;
	NI cap;
	tyTuple__R7ylOuMV2EoTykm7WC15Zw* d;
};
struct tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg {
	tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q traceStack;
	tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyTuple__p6sxP3CYOYBGz8nnL1OXGQ {
	NI Field0;
	tyObject_TextBufferEventObj__8t5KEL9cln9cTzko48rumWDg* Field1;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tySequence__8Np6tlClE5az1CyqZdN19bQ {
  NI len; tySequence__8Np6tlClE5az1CyqZdN19bQ_Content* p;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A {
	tySequence__8Np6tlClE5az1CyqZdN19bQ data;
	NI counter;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE]; };
struct tySequence__obI9bdO3X9b7Cr16WOB6i6qw_Content { NI cap; tyTuple__p6sxP3CYOYBGz8nnL1OXGQ data[SEQ_DECL_SIZE]; };
struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content { NI cap; tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw, initHashSet__pkgZowlkettleZwidgets_u366)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, init__pkgZowlkettleZwidgets_u380)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, NI initialSize_p1);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u249)(NI x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pkgZowlkettleZwidgets_u396)(tySequence__4eRCaZmrYLLw2k30GPTiMw* s_p0, NI len_p1);
N_LIB_PRIVATE N_NIMCALL(NI, len__pkgZowlkettleZwidgets_u630)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw s_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2661)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pkgZowlkettleZwidgets_u879)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw s_p0, NimStringV2 key_p1);
static N_INLINE(NI, rawGet__pkgZowlkettleZwidgets_u892)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u601)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1);
N_LIB_PRIVATE N_NIMCALL(void, incl__pkgZowlkettleZwidgets_u1142)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, NimStringV2 key_p1);
static N_INLINE(NIM_BOOL, mustRehash__pkgZowlkettleZwidgets_u1231)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pkgZowlkettleZwidgets_u1413)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0);
static N_INLINE(NI, rawGetKnownHC__pkgZowlkettleZwidgets_u1648)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0, NimStringV2 key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pkgZowlkettleZwidgets_u1986)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw* data_p1, NimStringV2 key_p2, NI hc_p3, NI h_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZwidgets_u518)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZowlkettleZwidgets_u521)(tySequence__4eRCaZmrYLLw2k30GPTiMw* dest_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pkgZowlkettleZwidgets_u404)(tySequence__4eRCaZmrYLLw2k30GPTiMw* s_p0, NI newlen_p1);
static N_INLINE(void, nimTraceRef)(void* q_p0, TNimTypeV2* desc_p1, void* env_p2);
static N_INLINE(void, add__system_u2971)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u2979)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A, initHashSet__pkgZowlkettleZwidgets_u26026)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, init__pkgZowlkettleZwidgets_u26040)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, NI initialSize_p1);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pkgZowlkettleZwidgets_u26056)(tySequence__8Np6tlClE5az1CyqZdN19bQ* s_p0, NI len_p1);
N_LIB_PRIVATE N_NIMCALL(NI, len__pkgZowlkettleZwidgets_u26247)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pkgZowlkettleZwidgets_u26493)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A s_p0, NI key_p1);
static N_INLINE(NI, rawGet__pkgZowlkettleZwidgets_u26506)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A t_p0, NI key_p1, NI* hc_p2);
static N_INLINE(NI, hash__pureZhashes_u131)(NI x_p0);
static N_INLINE(NI, hashWangYi1__pureZhashes_u139)(NU64 x_p0);
static N_INLINE(NU64, hiXorLo__pureZhashes_u80)(NU64 a_p0, NU64 b_p1);
N_LIB_PRIVATE N_NIMCALL(void, incl__pkgZowlkettleZwidgets_u26759)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, NI key_p1);
static N_INLINE(NIM_BOOL, mustRehash__pkgZowlkettleZwidgets_u26848)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A t_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pkgZowlkettleZwidgets_u27030)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0);
static N_INLINE(NI, rawGetKnownHC__pkgZowlkettleZwidgets_u27265)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A t_p0, NI key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pkgZowlkettleZwidgets_u27603)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, tySequence__8Np6tlClE5az1CyqZdN19bQ* data_p1, NI key_p2, NI hc_p3, NI h_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZwidgets_u26136)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZowlkettleZwidgets_u26139)(tySequence__8Np6tlClE5az1CyqZdN19bQ* dest_p0, tySequence__8Np6tlClE5az1CyqZdN19bQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pkgZowlkettleZwidgets_u26064)(tySequence__8Np6tlClE5az1CyqZdN19bQ* s_p0, NI newlen_p1);
static N_INLINE(NIM_BOOL, exclImpl__pkgZowlkettleZwidgets_u38123)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, NI key_p1);
N_LIB_PRIVATE N_NIMCALL(void, reset__pkgZowlkettleZwidgets_u38253)(NI* obj_p0);
static N_INLINE(NIM_BOOL, isEmpty__pureZcollectionsZsets_u36)(NI hcode_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u6065)(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[87+1];
} TM__0JXiWyhP5OCO8jWMA6sb1w_6 = { 87 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim(34, 9) `\012t.counter < t.dataLen` " };
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_7 = {87, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_6};
static const struct {
  NI cap; NIM_CHAR data[134+1];
} TM__0JXiWyhP5OCO8jWMA6sb1w_16 = { 134 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim(272, 13) `len(s) == length` the length of the HashSet changed while iterating over it" };
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_17 = {134, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_16};
extern TNimTypeV2 NTIv2__8t5KEL9cln9cTzko48rumWDg_;
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_20 = {87, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_6};
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_29 = {134, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_16};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZwidgets_u518)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field1.p && !(dest_p0.p->data[colontmp_].Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field1.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));
}
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0) {
	NI result;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_2;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_3;
NIM_BOOL* nimErr_;
	nimfr_("slotsNeeded", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(39, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	if (nimAddInt((NI)((count_p0) / (((NI)2))), count_p0, &TM__0JXiWyhP5OCO8jWMA6sb1w_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_2), ((NI)4), &TM__0JXiWyhP5OCO8jWMA6sb1w_3)) { raiseOverflow(); goto BeforeRet_;
	};
	result = nextPowerOfTwo__pureZmath_u249((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_3));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZwidgets_u474)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0) {
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZowlkettleZwidgets_u471)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1.len = 0; (*dest_p0).Field1.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, init__pkgZowlkettleZwidgets_u380)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, NI initialSize_p1) {
	NI correctSizeX60gensym6__1;
NIM_BOOL* nimErr_;
	nimfr_("init", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(19, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");	if ((initialSize_p1) < ((NI)0) || (initialSize_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	correctSizeX60gensym6__1 = slotsNeeded__pureZcollectionsZsets_u50((initialSize_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(23);	(*s_p0).counter = ((NI)0);
	nimlf_(115, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	if ((correctSizeX60gensym6__1) < ((NI)0) || (correctSizeX60gensym6__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym6__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__pkgZowlkettleZwidgets_u396((&(*s_p0).data), (correctSizeX60gensym6__1));
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw, initHashSet__pkgZowlkettleZwidgets_u366)(NI initialSize_p0) {
	tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw result;
NIM_BOOL* nimErr_;
	nimfr_("initHashSet", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimln_(133);	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw));
	nimln_(134);	init__pkgZowlkettleZwidgets_u380((&result), initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__pkgZowlkettleZwidgets_u630)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw s_p0) {
	NI result;
	nimfr_("len", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
	nimln_(184);	result = s_p0.counter;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isFilled", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
	nimlf_(27, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	result = !((hcode_p0 == ((NI)0)));
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "K:\\Progz\\nim-2.2.6\\lib\\system\\strmantle.nim");
{	nimlf_(33, "K:\\Progz\\nim-2.2.6\\lib\\system\\strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1749(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1) {
	NI result;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_4;
	nimfr_("nextTry", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{	result = (NI)0;
	nimlf_(30, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	if (nimAddInt(h_p0, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_4)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_4) & maxHash_p1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGet__pkgZowlkettleZwidgets_u892)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_5;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(72);	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u601(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = t_p0.data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimln_(75);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = (t_p0.data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimln_(75);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_5)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_5);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pkgZowlkettleZwidgets_u879)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw s_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("contains", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc_1 = (NI)0;
	nimlf_(169, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	index_1 = rawGet__pkgZowlkettleZwidgets_u892(s_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(170);	result = (((NI)0) <= index_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__pkgZowlkettleZwidgets_u1231)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_8;
	NI T9_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_9;
NIM_BOOL* nimErr_;
	nimfr_("mustRehash", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(34, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!!((t_p0.counter < T3_))) goto LA4_;
		failedAssertImpl__stdZassertions_u234(TM__0JXiWyhP5OCO8jWMA6sb1w_7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimln_(35);	T6_ = (NIM_BOOL)0;
	T7_ = t_p0.data.len;
	if (nimAddInt(t_p0.counter, (NI)((t_p0.counter) / (((NI)2))), &TM__0JXiWyhP5OCO8jWMA6sb1w_8)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = (T7_ < (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_8));
	if (T6_) goto LA8_;
	T9_ = t_p0.data.len;
	if (nimSubInt(T9_, t_p0.counter, &TM__0JXiWyhP5OCO8jWMA6sb1w_9)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_9) < ((NI)4));
LA8_: ;
	result = T6_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGetKnownHC__pkgZowlkettleZwidgets_u1648)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0, NimStringV2 key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_11;
NIM_BOOL* nimErr_;
	nimfr_("rawGetKnownHC", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(42);	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(43);		nimln_(55);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(44);	T6_ = (t_p0.data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			nimln_(50);			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				nimln_(51);				nimln_(55);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			nimln_(52);			T16_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_11)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_11);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pkgZowlkettleZwidgets_u1986)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw* data_p1, NimStringV2 key_p2, NI hc_p3, NI h_p4) {
NIM_BOOL* nimErr_;
	nimfr_("rawInsert", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(27, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym18__1;
		T3_ = (*data_p1).len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(19);		correctSizeX60gensym18__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(23);		(*s_p0).counter = ((NI)0);
		nimln_(28);		if ((correctSizeX60gensym18__1) < ((NI)0) || (correctSizeX60gensym18__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym18__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__pkgZowlkettleZwidgets_u396((&(*s_p0).data), (correctSizeX60gensym18__1));
	}
LA4_: ;
	nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");	if (h_p4 < 0 || h_p4 >= (*data_p1).len){ raiseIndexError2(h_p4,(*data_p1).len-1); goto BeforeRet_;
	}
	eqcopy___system_u2661((&(*data_p1).p->data[h_p4].Field1), key_p2);
	nimlf_(30, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");	if (h_p4 < 0 || h_p4 >= (*data_p1).len){ raiseIndexError2(h_p4,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p4].Field0 = hc_p3;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pkgZowlkettleZwidgets_u1413)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0) {
	tySequence__4eRCaZmrYLLw2k30GPTiMw n_1;
	NI T1_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_10;
	tySequence__4eRCaZmrYLLw2k30GPTiMw T2_;
NIM_BOOL* nimErr_;
	nimfr_("enlarge", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	nimln_(38);	T1_ = (*s_p0).data.len;
	if (nimMulInt(T1_, ((NI)2), &TM__0JXiWyhP5OCO8jWMA6sb1w_10)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)) < ((NI)0) || ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__pkgZowlkettleZwidgets_u396((&n_1), ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)));
	nimln_(39);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*s_p0).data;
	(*s_p0).data = n_1;
	n_1 = T2_;
	{
		NI i_1;
		NI colontmp_;
		NI T4_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(46, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		nimlf_(40, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");		T4_ = (n_1.len-1);
		colontmp_ = T4_;
		nimlf_(68, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(69);			while (1) {
				NI TM__0JXiWyhP5OCO8jWMA6sb1w_13;
				if (!(res_1 <= colontmp_)) goto LA6;
				nimlf_(40, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");				i_1 = ((NI) (res_1));
				nimln_(41);				{
					NIM_BOOL T9_;
					NI j_1;
					NI T12_;
					NI TM__0JXiWyhP5OCO8jWMA6sb1w_12;
					tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* T13_;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZsets_u39(n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					nimln_(42);					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T12_ = (NI)0;
					T12_ = rawGetKnownHC__pkgZowlkettleZwidgets_u1648((*s_p0), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimSubInt(((NI)-1), T12_, &TM__0JXiWyhP5OCO8jWMA6sb1w_12)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_12);
					nimln_(43);					T13_ = (tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw*)0;
					T13_ = s_p0;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					rawInsert__pkgZowlkettleZwidgets_u1986(T13_, (&(*s_p0).data), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0, j_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA10_: ;
				nimlf_(74, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_13)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_13);
			} LA6: ;
		}
	}
	nimlf_(115, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	eqdestroy___pkgZowlkettleZwidgets_u518(n_1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, incl__pkgZowlkettleZwidgets_u1142)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, NimStringV2 key_p1) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("incl", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(46, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym11__1;
		T3_ = (*s_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(19);		correctSizeX60gensym11__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(23);		(*s_p0).counter = ((NI)0);
		nimln_(47);		if ((correctSizeX60gensym11__1) < ((NI)0) || (correctSizeX60gensym11__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym11__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__pkgZowlkettleZwidgets_u396((&(*s_p0).data), (correctSizeX60gensym11__1));
	}
LA4_: ;
	hc_1 = (NI)0;
	nimln_(49);	index_1 = rawGet__pkgZowlkettleZwidgets_u892((*s_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(208, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	{
		tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* T15_;
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_14;
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_15;
		nimlf_(50, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");		if (!(index_1 < ((NI)0))) goto LA8_;
		nimln_(51);		{
			NIM_BOOL T12_;
			T12_ = (NIM_BOOL)0;
			T12_ = mustRehash__pkgZowlkettleZwidgets_u1231((*s_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T12_) goto LA13_;
			nimln_(52);			enlarge__pkgZowlkettleZwidgets_u1413(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(53);			index_1 = rawGetKnownHC__pkgZowlkettleZwidgets_u1648((*s_p0), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA13_: ;
		nimln_(54);		T15_ = (tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw*)0;
		T15_ = s_p0;
		if (nimSubInt(((NI)-1), index_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_14)) { raiseOverflow(); goto BeforeRet_;
		};
		rawInsert__pkgZowlkettleZwidgets_u1986(T15_, (&(*s_p0).data), key_p1, hc_1, (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_14));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(55);		if (nimAddInt((*s_p0).counter, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_15)) { raiseOverflow(); goto BeforeRet_;
		};
		(*s_p0).counter = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_15);
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw, difference__pkgZowlkettleZwidgets_u352)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw s1_p0, tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw s2_p1) {
	tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw result;
NIM_BOOL* nimErr_;
	nimfr_("difference", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw));
	nimlf_(462, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	result = initHashSet__pkgZowlkettleZwidgets_u366(((NI)64));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2 item_1;
		NI length_1;
		item_1.len = 0; item_1.p = NIM_NIL;
		nimln_(268);		length_1 = len__pkgZowlkettleZwidgets_u630(s1_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			NI h_1;
			NI colontmp_;
			NI T3_;
			NI res_1;
			h_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");			nimlf_(269, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");			T3_ = (s1_p0.data.len-1);
			colontmp_ = T3_;
			nimlf_(96, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NI TM__0JXiWyhP5OCO8jWMA6sb1w_18;
					if (!(res_1 <= colontmp_)) goto LA5;
					nimlf_(269, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");					h_1 = ((NI) (res_1));
					nimln_(270);					{
						NIM_BOOL T8_;
						if (h_1 < 0 || h_1 >= s1_p0.data.len){ raiseIndexError2(h_1,s1_p0.data.len-1); goto BeforeRet_;
						}
						T8_ = (NIM_BOOL)0;
						T8_ = isFilled__pureZcollectionsZsets_u39(s1_p0.data.p->data[h_1].Field0);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T8_) goto LA9_;
						nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");						if (h_1 < 0 || h_1 >= s1_p0.data.len){ raiseIndexError2(h_1,s1_p0.data.len-1); goto BeforeRet_;
						}
						eqcopy___system_u2661((&item_1), s1_p0.data.p->data[h_1].Field1);
						nimlf_(464, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");						{
							NIM_BOOL T13_;
							T13_ = (NIM_BOOL)0;
							T13_ = contains__pkgZowlkettleZwidgets_u879(s2_p1, item_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!!(T13_)) goto LA14_;
							nimln_(465);							incl__pkgZowlkettleZwidgets_u1142((&result), item_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA14_: ;
						nimln_(272);						{
							NI T18_;
							T18_ = (NI)0;
							T18_ = len__pkgZowlkettleZwidgets_u630(s1_p0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!!((T18_ == length_1))) goto LA19_;
							failedAssertImpl__stdZassertions_u234(TM__0JXiWyhP5OCO8jWMA6sb1w_17);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA19_: ;
					}
LA9_: ;
					nimlf_(102, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_18)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_18);
				} LA5: ;
			}
		}
		nimlf_(394, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		if (item_1.p && !(item_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(item_1.p);
}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZwidgets_u558)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* dest_p0) {
	eqdestroy___pkgZowlkettleZwidgets_u518((*dest_p0).data);
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__jJwHR8yLLwvKfi1jy4PrXw*) (x_p0))).p == (*((tyObject_NimRawSeq__jJwHR8yLLwvKfi1jy4PrXw*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZowlkettleZwidgets_u521)(tySequence__4eRCaZmrYLLw2k30GPTiMw* dest_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw src_p1) {
	NI T6_;
	NI colontmp_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__pkgZowlkettleZwidgets_u404((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			(*dest_p0).p->data[colontmp_].Field0 = src_p1.p->data[colontmp_].Field0;
			eqcopy___system_u2661((&(*dest_p0).p->data[colontmp_].Field1), src_p1.p->data[colontmp_].Field1);
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZowlkettleZwidgets_u561)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* dest_p0, tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw src_p1) {
	eqcopy___pkgZowlkettleZwidgets_u521((&(*dest_p0).data), src_p1.data);
	(*dest_p0).counter = src_p1.counter;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimlf_(353, "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");	nimln_(357);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u2971)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "K:\\Progz\\nim-2.2.6\\lib\\system\\cellseqs_v2.nim");
	nimlf_(28, "K:\\Progz\\nim-2.2.6\\lib\\system\\cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u2979(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRef)(void* q_p0, TNimTypeV2* desc_p1, void* env_p2) {
	void** p_1;
	nimfr_("nimTraceRef", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimlf_(129, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(130);	{
		tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(134);		j_1 = ((tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg*) (env_p2));
		nimln_(135);		add__system_u2971((&(*j_1).traceStack), p_1, desc_p1);
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZowlkettleZwidgets_u22738)(tySequence__obI9bdO3X9b7Cr16WOB6i6qw* dest_p0, void* env_p1) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest_p0).len;
			if (!(colontmp_ < T3_)) goto LA2;
			nimTraceRef(&(*dest_p0).p->data[colontmp_].Field1, ((TNimTypeV2*) ((&NTIv2__8t5KEL9cln9cTzko48rumWDg_))), env_p1);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZwidgets_u26136)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, init__pkgZowlkettleZwidgets_u26040)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, NI initialSize_p1) {
	NI correctSizeX60gensym488__1;
NIM_BOOL* nimErr_;
	nimfr_("init", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(19, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");	if ((initialSize_p1) < ((NI)0) || (initialSize_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	correctSizeX60gensym488__1 = slotsNeeded__pureZcollectionsZsets_u50((initialSize_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(23);	(*s_p0).counter = ((NI)0);
	nimlf_(115, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	if ((correctSizeX60gensym488__1) < ((NI)0) || (correctSizeX60gensym488__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym488__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__pkgZowlkettleZwidgets_u26056((&(*s_p0).data), (correctSizeX60gensym488__1));
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A, initHashSet__pkgZowlkettleZwidgets_u26026)(NI initialSize_p0) {
	tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A result;
NIM_BOOL* nimErr_;
	nimfr_("initHashSet", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimln_(133);	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A));
	nimln_(134);	init__pkgZowlkettleZwidgets_u26040((&result), initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__pkgZowlkettleZwidgets_u26247)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A s_p0) {
	NI result;
	nimfr_("len", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
	nimln_(184);	result = s_p0.counter;
	popFrame();
	return result;
}
static N_INLINE(NU64, hiXorLo__pureZhashes_u80)(NU64 a_p0, NU64 b_p1) {
	NU64 result;
	nimfr_("hiXorLo", "K:\\Progz\\nim-2.2.6\\lib\\pure\\hashes.nim");
	result = (NU64)0;
	nimlf_(125, "K:\\Progz\\nim-2.2.6\\lib\\pure\\hashes.nim");	result = 0ULL;
	nimln_(126);	__uint128_t r = a_p0; r *= b_p1; result = (r >> 64) ^ r;
	popFrame();
	return result;
}
static N_INLINE(NI, hashWangYi1__pureZhashes_u139)(NU64 x_p0) {
	NI result;
	NU64 T1_;
	NU64 T2_;
NIM_BOOL* nimErr_;
	nimfr_("hashWangYi1", "K:\\Progz\\nim-2.2.6\\lib\\pure\\hashes.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(187);	nimln_(174);	T1_ = (NU64)0;
	T1_ = hiXorLo__pureZhashes_u80(11562461410679940143ULL, (NU64)(x_p0 ^ 16646288086500911323ULL));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(187);	T2_ = (NU64)0;
	T2_ = hiXorLo__pureZhashes_u80(T1_, 16952864883938283885ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T2_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, hash__pureZhashes_u131)(NI x_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("hash", "K:\\Progz\\nim-2.2.6\\lib\\pure\\hashes.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(215);	nimln_(216);	result = hashWangYi1__pureZhashes_u139(((NU64) (x_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGet__pkgZowlkettleZwidgets_u26506)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A t_p0, NI key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_19;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(72, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u131(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = t_p0.data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimln_(75);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = (t_p0.data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = (t_p0.data.p->data[h_1].Field1 == key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimln_(75);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_19)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_19);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pkgZowlkettleZwidgets_u26493)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A s_p0, NI key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("contains", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc_1 = (NI)0;
	nimlf_(169, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	index_1 = rawGet__pkgZowlkettleZwidgets_u26506(s_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(170);	result = (((NI)0) <= index_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__pkgZowlkettleZwidgets_u26848)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A t_p0) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_21;
	NI T9_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_22;
NIM_BOOL* nimErr_;
	nimfr_("mustRehash", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(34, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!!((t_p0.counter < T3_))) goto LA4_;
		failedAssertImpl__stdZassertions_u234(TM__0JXiWyhP5OCO8jWMA6sb1w_20);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimln_(35);	T6_ = (NIM_BOOL)0;
	T7_ = t_p0.data.len;
	if (nimAddInt(t_p0.counter, (NI)((t_p0.counter) / (((NI)2))), &TM__0JXiWyhP5OCO8jWMA6sb1w_21)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = (T7_ < (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_21));
	if (T6_) goto LA8_;
	T9_ = t_p0.data.len;
	if (nimSubInt(T9_, t_p0.counter, &TM__0JXiWyhP5OCO8jWMA6sb1w_22)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_22) < ((NI)4));
LA8_: ;
	result = T6_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGetKnownHC__pkgZowlkettleZwidgets_u27265)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A t_p0, NI key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_24;
NIM_BOOL* nimErr_;
	nimfr_("rawGetKnownHC", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(42);	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(43);		nimln_(55);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(44);	T6_ = (t_p0.data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			nimln_(50);			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = (t_p0.data.p->data[h_1].Field1 == key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				nimln_(51);				nimln_(55);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			nimln_(52);			T16_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_24)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_24);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pkgZowlkettleZwidgets_u27603)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, tySequence__8Np6tlClE5az1CyqZdN19bQ* data_p1, NI key_p2, NI hc_p3, NI h_p4) {
NIM_BOOL* nimErr_;
	nimfr_("rawInsert", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(27, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym500__1;
		T3_ = (*data_p1).len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(19);		correctSizeX60gensym500__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(23);		(*s_p0).counter = ((NI)0);
		nimln_(28);		if ((correctSizeX60gensym500__1) < ((NI)0) || (correctSizeX60gensym500__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym500__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__pkgZowlkettleZwidgets_u26056((&(*s_p0).data), (correctSizeX60gensym500__1));
	}
LA4_: ;
	nimln_(29);	if (h_p4 < 0 || h_p4 >= (*data_p1).len){ raiseIndexError2(h_p4,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p4].Field1 = key_p2;
	nimln_(30);	if (h_p4 < 0 || h_p4 >= (*data_p1).len){ raiseIndexError2(h_p4,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p4].Field0 = hc_p3;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pkgZowlkettleZwidgets_u27030)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0) {
	tySequence__8Np6tlClE5az1CyqZdN19bQ n_1;
	NI T1_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_23;
	tySequence__8Np6tlClE5az1CyqZdN19bQ T2_;
NIM_BOOL* nimErr_;
	nimfr_("enlarge", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	nimln_(38);	T1_ = (*s_p0).data.len;
	if (nimMulInt(T1_, ((NI)2), &TM__0JXiWyhP5OCO8jWMA6sb1w_23)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_23)) < ((NI)0) || ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_23)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_23), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__pkgZowlkettleZwidgets_u26056((&n_1), ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_23)));
	nimln_(39);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*s_p0).data;
	(*s_p0).data = n_1;
	n_1 = T2_;
	{
		NI i_1;
		NI colontmp_;
		NI T4_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(46, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		nimlf_(40, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");		T4_ = (n_1.len-1);
		colontmp_ = T4_;
		nimlf_(68, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(69);			while (1) {
				NI TM__0JXiWyhP5OCO8jWMA6sb1w_26;
				if (!(res_1 <= colontmp_)) goto LA6;
				nimlf_(40, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");				i_1 = ((NI) (res_1));
				nimln_(41);				{
					NIM_BOOL T9_;
					NI j_1;
					NI T12_;
					NI TM__0JXiWyhP5OCO8jWMA6sb1w_25;
					tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* T13_;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZsets_u39(n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					nimln_(42);					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T12_ = (NI)0;
					T12_ = rawGetKnownHC__pkgZowlkettleZwidgets_u27265((*s_p0), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimSubInt(((NI)-1), T12_, &TM__0JXiWyhP5OCO8jWMA6sb1w_25)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_25);
					nimln_(43);					T13_ = (tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A*)0;
					T13_ = s_p0;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					rawInsert__pkgZowlkettleZwidgets_u27603(T13_, (&(*s_p0).data), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0, j_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA10_: ;
				nimlf_(74, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_26)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_26);
			} LA6: ;
		}
	}
	nimlf_(115, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	eqdestroy___pkgZowlkettleZwidgets_u26136(n_1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, incl__pkgZowlkettleZwidgets_u26759)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, NI key_p1) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("incl", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(46, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym493__1;
		T3_ = (*s_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(19);		correctSizeX60gensym493__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(23);		(*s_p0).counter = ((NI)0);
		nimln_(47);		if ((correctSizeX60gensym493__1) < ((NI)0) || (correctSizeX60gensym493__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym493__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__pkgZowlkettleZwidgets_u26056((&(*s_p0).data), (correctSizeX60gensym493__1));
	}
LA4_: ;
	hc_1 = (NI)0;
	nimln_(49);	index_1 = rawGet__pkgZowlkettleZwidgets_u26506((*s_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(208, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	{
		tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* T15_;
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_27;
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_28;
		nimlf_(50, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");		if (!(index_1 < ((NI)0))) goto LA8_;
		nimln_(51);		{
			NIM_BOOL T12_;
			T12_ = (NIM_BOOL)0;
			T12_ = mustRehash__pkgZowlkettleZwidgets_u26848((*s_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T12_) goto LA13_;
			nimln_(52);			enlarge__pkgZowlkettleZwidgets_u27030(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(53);			index_1 = rawGetKnownHC__pkgZowlkettleZwidgets_u27265((*s_p0), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA13_: ;
		nimln_(54);		T15_ = (tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A*)0;
		T15_ = s_p0;
		if (nimSubInt(((NI)-1), index_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_27)) { raiseOverflow(); goto BeforeRet_;
		};
		rawInsert__pkgZowlkettleZwidgets_u27603(T15_, (&(*s_p0).data), key_p1, hc_1, (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_27));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(55);		if (nimAddInt((*s_p0).counter, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_28)) { raiseOverflow(); goto BeforeRet_;
		};
		(*s_p0).counter = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_28);
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A, difference__pkgZowlkettleZwidgets_u26012)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A s1_p0, tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A s2_p1) {
	tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A result;
NIM_BOOL* nimErr_;
	nimfr_("difference", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A));
	nimlf_(462, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	result = initHashSet__pkgZowlkettleZwidgets_u26026(((NI)64));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI item_1;
		NI length_1;
		item_1 = (NI)0;
		nimln_(268);		length_1 = len__pkgZowlkettleZwidgets_u26247(s1_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			NI h_1;
			NI colontmp_;
			NI T3_;
			NI res_1;
			h_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");			nimlf_(269, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");			T3_ = (s1_p0.data.len-1);
			colontmp_ = T3_;
			nimlf_(96, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NI TM__0JXiWyhP5OCO8jWMA6sb1w_30;
					if (!(res_1 <= colontmp_)) goto LA5;
					nimlf_(269, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");					h_1 = ((NI) (res_1));
					nimln_(270);					{
						NIM_BOOL T8_;
						if (h_1 < 0 || h_1 >= s1_p0.data.len){ raiseIndexError2(h_1,s1_p0.data.len-1); goto BeforeRet_;
						}
						T8_ = (NIM_BOOL)0;
						T8_ = isFilled__pureZcollectionsZsets_u39(s1_p0.data.p->data[h_1].Field0);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T8_) goto LA9_;
						nimln_(463);						if (h_1 < 0 || h_1 >= s1_p0.data.len){ raiseIndexError2(h_1,s1_p0.data.len-1); goto BeforeRet_;
						}
						item_1 = s1_p0.data.p->data[h_1].Field1;
						nimln_(464);						{
							NIM_BOOL T13_;
							T13_ = (NIM_BOOL)0;
							T13_ = contains__pkgZowlkettleZwidgets_u26493(s2_p1, item_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!!(T13_)) goto LA14_;
							nimln_(465);							incl__pkgZowlkettleZwidgets_u26759((&result), item_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA14_: ;
						nimln_(272);						{
							NI T18_;
							T18_ = (NI)0;
							T18_ = len__pkgZowlkettleZwidgets_u26247(s1_p0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!!((T18_ == length_1))) goto LA19_;
							failedAssertImpl__stdZassertions_u234(TM__0JXiWyhP5OCO8jWMA6sb1w_29);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA19_: ;
					}
LA9_: ;
					nimlf_(102, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_30)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_30);
				} LA5: ;
			}
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZowlkettleZwidgets_u26175)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* dest_p0) {
	eqdestroy___pkgZowlkettleZwidgets_u26136((*dest_p0).data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZowlkettleZwidgets_u26139)(tySequence__8Np6tlClE5az1CyqZdN19bQ* dest_p0, tySequence__8Np6tlClE5az1CyqZdN19bQ src_p1) {
	NI T6_;
	NI colontmp_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__pkgZowlkettleZwidgets_u26064((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			(*dest_p0).p->data[colontmp_].Field0 = src_p1.p->data[colontmp_].Field0;
			(*dest_p0).p->data[colontmp_].Field1 = src_p1.p->data[colontmp_].Field1;
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZowlkettleZwidgets_u26178)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* dest_p0, tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A src_p1) {
	eqcopy___pkgZowlkettleZwidgets_u26139((&(*dest_p0).data), src_p1.data);
	(*dest_p0).counter = src_p1.counter;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZowlkettleZwidgets_u26172)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* dest_p0) {
	(*dest_p0).data.len = 0; (*dest_p0).data.p = NIM_NIL;
	(*dest_p0).counter = 0;
}
static N_INLINE(NIM_BOOL, isEmpty__pureZcollectionsZsets_u36)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isEmpty", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
	nimlf_(24, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	result = (hcode_p0 == ((NI)0));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, exclImpl__pkgZowlkettleZwidgets_u38123)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, NI key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI i_1;
	NI msk_1;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("exclImpl", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc_1 = (NI)0;
	nimlf_(79, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\setimpl.nim");	i_1 = rawGet__pkgZowlkettleZwidgets_u26506((*s_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(80);	T1_ = ((*s_p0).data.len-1);
	msk_1 = T1_;
	nimln_(81);	result = NIM_TRUE;
	nimln_(83);	{
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_31;
		if (!(((NI)0) <= i_1)) goto LA4_;
		nimln_(84);		result = NIM_FALSE;
		nimln_(85);		if (nimSubInt((*s_p0).counter, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_31)) { raiseOverflow(); goto BeforeRet_;
		};
		(*s_p0).counter = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_31);
		{
			nimln_(86);			while (1) {
				NI j_1;
				NI r_1;
				nimln_(87);				j_1 = i_1;
				nimln_(88);				r_1 = j_1;
				nimln_(89);				if (i_1 < 0 || i_1 >= (*s_p0).data.len){ raiseIndexError2(i_1,(*s_p0).data.len-1); goto BeforeRet_;
				}
				(*s_p0).data.p->data[i_1].Field0 = ((NI)0);
				nimln_(91);				if (i_1 < 0 || i_1 >= (*s_p0).data.len){ raiseIndexError2(i_1,(*s_p0).data.len-1); goto BeforeRet_;
				}
				reset__pkgZowlkettleZwidgets_u38253((&(*s_p0).data.p->data[i_1].Field1));
				{
					nimln_(93);					while (1) {
						NI TM__0JXiWyhP5OCO8jWMA6sb1w_32;
						nimln_(94);						if (nimAddInt(i_1, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_32)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_32) & msk_1);
						nimln_(95);						{
							NIM_BOOL T12_;
							if (i_1 < 0 || i_1 >= (*s_p0).data.len){ raiseIndexError2(i_1,(*s_p0).data.len-1); goto BeforeRet_;
							}
							T12_ = (NIM_BOOL)0;
							T12_ = isEmpty__pureZcollectionsZsets_u36((*s_p0).data.p->data[i_1].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T12_) goto LA13_;
							nimln_(96);							goto BeforeRet_;
						}
LA13_: ;
						nimln_(97);						if (i_1 < 0 || i_1 >= (*s_p0).data.len){ raiseIndexError2(i_1,(*s_p0).data.len-1); goto BeforeRet_;
						}
						r_1 = (NI)((*s_p0).data.p->data[i_1].Field0 & msk_1);
						nimln_(75);						{
							NIM_BOOL T17_;
							NIM_BOOL T18_;
							NIM_BOOL T19_;
							NIM_BOOL T22_;
							NIM_BOOL T25_;
							nimln_(93);							T17_ = (NIM_BOOL)0;
							T18_ = (NIM_BOOL)0;
							T19_ = (NIM_BOOL)0;
							T19_ = (r_1 <= i_1);
							if (!(T19_)) goto LA20_;
							T19_ = (j_1 < r_1);
LA20_: ;
							T18_ = T19_;
							if (T18_) goto LA21_;
							T22_ = (NIM_BOOL)0;
							T22_ = (j_1 < r_1);
							if (!(T22_)) goto LA23_;
							T22_ = (i_1 < j_1);
LA23_: ;
							T18_ = T22_;
LA21_: ;
							T17_ = T18_;
							if (T17_) goto LA24_;
							T25_ = (NIM_BOOL)0;
							T25_ = (i_1 < j_1);
							if (!(T25_)) goto LA26_;
							T25_ = (r_1 <= i_1);
LA26_: ;
							T17_ = T25_;
LA24_: ;
							if (!!(T17_)) goto LA27_;
							nimln_(75);							goto LA8;
						}
LA27_: ;
					}
				} LA8: ;
				nimln_(98);				if (j_1 < 0 || j_1 >= (*s_p0).data.len){ raiseIndexError2(j_1,(*s_p0).data.len-1); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= (*s_p0).data.len){ raiseIndexError2(i_1,(*s_p0).data.len-1); goto BeforeRet_;
				}
				(*s_p0).data.p->data[j_1] = (*s_p0).data.p->data[i_1];
				eqwasMoved___system_u6065((&(*s_p0).data.p->data[i_1]));
			}
		}
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, excl__pkgZowlkettleZwidgets_u38108)(tyObject_HashSet__DbqPK6M9a9cN6Aun4J0nkA5A* s_p0, NI key_p1) {
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
	nimfr_("excl", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(309, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\sets.nim");	T1_ = (NIM_BOOL)0;
	T1_ = exclImpl__pkgZowlkettleZwidgets_u38123(s_p0, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(T1_);
	}BeforeRet_: ;
	popFrame();
}
