/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@pstd@sprivate@sospaths2.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@pstd@sprivate@sospaths2.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, splitDrive__stdZprivateZntpath_u2)(NimStringV2 p_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2658)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2667)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8911)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8924)(NimStringV2 s_p0, NI first_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZntpath_u119)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u48)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2);
static N_INLINE(NIM_CHAR, X5BX5D___system_u8334)(NimStringV2 s_p0, NI i_p1);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8386)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2410)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u19)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addNormalizePath__pureZpathnorm_u87)(NimStringV2 x_p0, NimStringV2* result_p1, NI* state_p2, NIM_CHAR dirSep_p3);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_19 = { 1 | NIM_STRLIT_FLAG, "\\" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_20 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_19};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZosdirs_u85)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* dest_p0) {
	if ((*dest_p0).Field0.p && !((*dest_p0).Field0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field0.p);
}
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
	if ((*dest_p0).Field2.p && !((*dest_p0).Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field2.p);
}
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringV2 path_p0, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result) {
	tyTuple__UV3llMMYFckfui8YMBuUZA tmpTuple_1;
	NimStringV2 drive_1;
	NI namePos_1;
	NI dotPos_1;
	NI stop_1;
NIM_BOOL* nimErr_;
	nimfr_("splitFile", "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	nimZeroMem((void*)(&tmpTuple_1), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
	drive_1.len = 0; drive_1.p = NIM_NIL;
	nimlf_(643, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");	namePos_1 = ((NI)0);
	nimln_(644);	dotPos_1 = ((NI)0);
	nimln_(646);	splitDrive__stdZprivateZntpath_u2(path_p0, (&tmpTuple_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	drive_1 = tmpTuple_1.Field0;
	nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");	eqwasMoved___system_u2658((&tmpTuple_1.Field0));
	nimlf_(647, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");	stop_1 = drive_1.len;
	nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");	eqsink___system_u2667((&(*Result).Field0), drive_1);
	{
		NI i_1;
		NI colontmp_;
		NI TM__O1zDbSYyG8zQytyoZAh0dg_2;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(6, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		nimlf_(651, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");		if (nimSubInt(path_p0.len, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_2)) { raiseOverflow(); goto LA1_;
		};
		colontmp_ = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_2);
		nimlf_(33, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		res_1 = colontmp_;
		{
			nimln_(34);			while (1) {
				NI TM__O1zDbSYyG8zQytyoZAh0dg_9;
				if (!(stop_1 <= res_1)) goto LA4;
				nimlf_(651, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");				i_1 = ((NI) (res_1));
				nimln_(652);				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					if (i_1 < 0 || i_1 >= path_p0.len){ raiseIndexError2(i_1,path_p0.len-1); goto LA1_;
					}
					T7_ = (((NU8)(path_p0.p->data[i_1])) == ((NU8)(92)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)));
					if (T7_) goto LA8_;
					T7_ = (i_1 == ((NI)0));
LA8_: ;
					if (!T7_) goto LA9_;
					nimln_(653);					{
						NI colontmpD_;
						NI colontmpD__2;
						NI T15_;
						NimStringV2 T22_;
						NI TM__O1zDbSYyG8zQytyoZAh0dg_4;
						if (i_1 < 0 || i_1 >= path_p0.len){ raiseIndexError2(i_1,path_p0.len-1); goto LA1_;
						}
						if (!(((NU8)(path_p0.p->data[i_1])) == ((NU8)(92)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)))) goto LA13_;
						colontmpD_ = (NI)0;
						colontmpD__2 = (NI)0;
						nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");						nimlf_(654, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");						T15_ = (NI)0;
						{
							NIM_BOOL T18_;
							NI TM__O1zDbSYyG8zQytyoZAh0dg_3;
							nimlf_(1986, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");							nimlf_(654, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");							nimlf_(1986, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");							T18_ = (NIM_BOOL)0;
							T18_ = NIM_LIKELY((((NI)1) <= i_1));
							if (!T18_) goto LA19_;
							nimlf_(654, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");							if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_3)) { raiseOverflow(); goto LA1_;
							};
							colontmpD_ = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_3);
							T15_ = colontmpD_;
						}
						goto LA16_;
LA19_: ;
						{
							colontmpD__2 = ((NI)0);
							T15_ = colontmpD__2;
						}
LA16_: ;
						T22_.len = 0; T22_.p = NIM_NIL;
						T22_ = substr__system_u8911(path_p0, ((NI)0), T15_);
						nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");						eqsink___system_u2667((&(*Result).Field0), T22_);
						nimlf_(655, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");						if (nimAddInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_4)) { raiseOverflow(); goto LA1_;
						};
						namePos_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_4);
					}
LA13_: ;
					nimln_(656);					{
						NI TM__O1zDbSYyG8zQytyoZAh0dg_5;
						NimStringV2 T27_;
						NimStringV2 T28_;
						if (!(i_1 < dotPos_1)) goto LA25_;
						nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");						nimlf_(657, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");						if (nimSubInt(dotPos_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_5)) { raiseOverflow(); goto LA1_;
						};
						T27_.len = 0; T27_.p = NIM_NIL;
						T27_ = substr__system_u8911(path_p0, namePos_1, (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_5));
						nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");						eqsink___system_u2667((&(*Result).Field1), T27_);
						nimlf_(658, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");						T28_.len = 0; T28_.p = NIM_NIL;
						T28_ = substr__system_u8924(path_p0, dotPos_1);
						nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");						eqsink___system_u2667((&(*Result).Field2), T28_);
					}
					goto LA23_;
LA25_: ;
					{
						NimStringV2 T30_;
						nimlf_(660, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");						T30_.len = 0; T30_.p = NIM_NIL;
						T30_ = substr__system_u8924(path_p0, namePos_1);
						nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");						eqsink___system_u2667((&(*Result).Field1), T30_);
					}
LA23_: ;
					nimlf_(661, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");					goto LA2;
				}
				goto LA5_;
LA9_: ;
				{
					NIM_BOOL T32_;
					NIM_BOOL T33_;
					NIM_BOOL T34_;
					NIM_BOOL T35_;
					NIM_BOOL T36_;
					NI TM__O1zDbSYyG8zQytyoZAh0dg_6;
					NI TM__O1zDbSYyG8zQytyoZAh0dg_7;
					NI TM__O1zDbSYyG8zQytyoZAh0dg_8;
					nimln_(664);					T32_ = (NIM_BOOL)0;
					nimln_(663);					T33_ = (NIM_BOOL)0;
					nimln_(662);					T34_ = (NIM_BOOL)0;
					T35_ = (NIM_BOOL)0;
					T36_ = (NIM_BOOL)0;
					if (i_1 < 0 || i_1 >= path_p0.len){ raiseIndexError2(i_1,path_p0.len-1); goto LA1_;
					}
					T36_ = ((NU8)(path_p0.p->data[i_1]) == (NU8)(46));
					if (!(T36_)) goto LA37_;
					T36_ = (((NI)0) < i_1);
LA37_: ;
					T35_ = T36_;
					if (!(T35_)) goto LA38_;
					if (nimSubInt(path_p0.len, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_6)) { raiseOverflow(); goto LA1_;
					};
					T35_ = (i_1 < (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_6));
LA38_: ;
					T34_ = T35_;
					if (!(T34_)) goto LA39_;
					nimln_(663);					if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_7)) { raiseOverflow(); goto LA1_;
					};
					if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7) >= path_p0.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7),path_p0.len-1); goto LA1_;
					}
					T34_ = !((((NU8)(path_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7)])) == ((NU8)(92)) || ((NU8)(path_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_7)])) == ((NU8)(47))));
LA39_: ;
					T33_ = T34_;
					if (!(T33_)) goto LA40_;
					nimln_(664);					if (nimAddInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_8)) { raiseOverflow(); goto LA1_;
					};
					if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8) >= path_p0.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8),path_p0.len-1); goto LA1_;
					}
					T33_ = !(((NU8)(path_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_8)]) == (NU8)(46)));
LA40_: ;
					T32_ = T33_;
					if (!(T32_)) goto LA41_;
					T32_ = (dotPos_1 == ((NI)0));
LA41_: ;
					if (!T32_) goto LA42_;
					nimln_(665);					dotPos_1 = i_1;
				}
				goto LA5_;
LA42_: ;
LA5_: ;
				nimlf_(39, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");				if (nimSubInt(res_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_9)) { raiseOverflow(); goto LA1_;
				};
				res_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_9);
			} LA4: ;
		}
	} LA2: ;
	{
		LA1_:;
	}
	{
		nimlf_(31, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ntpath.nim");		eqdestroy___stdZprivateZntpath_u119((&tmpTuple_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_CHAR, X5BX5D___system_u8334)(NimStringV2 s_p0, NI i_p1) {
	NIM_CHAR result;
	NI TM__O1zDbSYyG8zQytyoZAh0dg_11;
	nimfr_("[]", "K:\\Progz\\nim-2.2.6\\lib\\system\\indices.nim");
{	result = (NIM_CHAR)0;
	if (nimSubInt(s_p0.len, i_p1, &TM__O1zDbSYyG8zQytyoZAh0dg_11)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_11) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_11) >= s_p0.len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_11),s_p0.len-1); goto BeforeRet_;
	}
	result = s_p0.p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_11)];
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2410(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8386)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	NI TM__O1zDbSYyG8zQytyoZAh0dg_12;
	nimfr_("[]", "K:\\Progz\\nim-2.2.6\\lib\\system\\indices.nim");
{	result = (NIM_CHAR*)0;
	nimPrepareStrMutationV2((&(*s_p0)));
	if (nimSubInt((*s_p0).len, i_p1, &TM__O1zDbSYyG8zQytyoZAh0dg_12)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12) >= (*s_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12),(*s_p0).len-1); goto BeforeRet_;
	}
	result = (&(*s_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_12)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	NI TM__O1zDbSYyG8zQytyoZAh0dg_18;
{	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_18)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_18);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u19)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1) {
	NI i_1;
	nimfr_("normalizePathEnd", "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");
{	nimlf_(51, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");	{
		if (!((*path_p0).len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(52);	i_1 = (*path_p0).len;
	{
		nimln_(53);		while (1) {
			if (!(((NI)1) <= i_1)) goto LA6;
			nimln_(54);			{
				NI TM__O1zDbSYyG8zQytyoZAh0dg_13;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_14;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_13)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_13) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_13) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_13),(*path_p0).len-1); goto BeforeRet_;
				}
				if (!(((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_13)])) == ((NU8)(92)) || ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_13)])) == ((NU8)(47)))) goto LA9_;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_14)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_14);
			}
			goto LA7_;
LA9_: ;
			{
				NIM_BOOL T12_;
				NIM_BOOL T13_;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_15;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_16;
				NI TM__O1zDbSYyG8zQytyoZAh0dg_17;
				nimln_(55);				T12_ = (NIM_BOOL)0;
				T13_ = (NIM_BOOL)0;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_15)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15),(*path_p0).len-1); goto BeforeRet_;
				}
				T13_ = ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_15)]) == (NU8)(46));
				if (!(T13_)) goto LA14_;
				T13_ = (((NI)2) <= i_1);
LA14_: ;
				T12_ = T13_;
				if (!(T12_)) goto LA15_;
				if (nimSubInt(i_1, ((NI)2), &TM__O1zDbSYyG8zQytyoZAh0dg_16)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_16) < 0 || (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_16) >= (*path_p0).len){ raiseIndexError2((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_16),(*path_p0).len-1); goto BeforeRet_;
				}
				T12_ = (((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_16)])) == ((NU8)(92)) || ((NU8)((*path_p0).p->data[(NI)(TM__O1zDbSYyG8zQytyoZAh0dg_16)])) == ((NU8)(47)));
LA15_: ;
				if (!T12_) goto LA16_;
				if (nimSubInt(i_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_17)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_17);
			}
			goto LA7_;
LA16_: ;
			{
				nimln_(56);				goto LA5;
			}
LA7_: ;
		} LA6: ;
	} LA5: ;
	nimln_(57);	{
		if (!trailingSep_p1) goto LA21_;
		nimln_(59);		if ((i_1) < ((NI)0) || (i_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&(*path_p0)), (i_1));
		nimln_(61);		nimAddCharV1((&(*path_p0)), 92);
	}
	goto LA19_;
LA21_: ;
	{
		nimln_(62);		if (!(((NI)0) < i_1)) goto LA24_;
		nimln_(64);		if ((i_1) < ((NI)0) || (i_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&(*path_p0)), (i_1));
	}
	goto LA19_;
LA24_: ;
	{
		nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		eqsink___system_u2667((&(*path_p0)), TM__O1zDbSYyG8zQytyoZAh0dg_20);
	}
LA19_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u48)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2) {
	NIM_BOOL trailingSep_1;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_CHAR T4_;
	NIM_BOOL T6_;
	NIM_BOOL T8_;
	NIM_CHAR* T10_;
NIM_BOOL* nimErr_;
	nimfr_("joinPathImpl", "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(85, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	nimln_(82);	T2_ = (((NI)0) < tail_p2.len);
	if (!(T2_)) goto LA3_;
	T4_ = (NIM_CHAR)0;
	T4_ = X5BX5D___system_u8334(tail_p2, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (((NU8)(T4_)) == ((NU8)(92)) || ((NU8)(T4_)) == ((NU8)(47)));
LA3_: ;
	T1_ = T2_;
	if (T1_) goto LA5_;
	nimln_(85);	T6_ = (NIM_BOOL)0;
	T6_ = (tail_p2.len == ((NI)0));
	if (!(T6_)) goto LA7_;
	T8_ = (NIM_BOOL)0;
	nimln_(82);	T8_ = (((NI)0) < (*result_p0).len);
	if (!(T8_)) goto LA9_;
	T10_ = (NIM_CHAR*)0;
	T10_ = X5BX5D___system_u8386(result_p0, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (((NU8)((*T10_))) == ((NU8)(92)) || ((NU8)((*T10_))) == ((NU8)(47)));
LA9_: ;
	T6_ = T8_;
LA7_: ;
	T1_ = T6_;
LA5_: ;
	trailingSep_1 = T1_;
	nimln_(86);	normalizePathEnd__stdZprivateZospaths2_u19(result_p0, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(87);	addNormalizePath__pureZpathnorm_u87(tail_p2, result_p0, state_p1, 92);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(88);	normalizePathEnd__stdZprivateZospaths2_u19(result_p0, trailingSep_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
	NI TM__O1zDbSYyG8zQytyoZAh0dg_10;
	NI state_1;
NIM_BOOL* nimErr_;
	nimfr_("joinPath", "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(116);	if (nimAddInt(head_p0.len, tail_p1.len, &TM__O1zDbSYyG8zQytyoZAh0dg_10)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10)) < ((NI)0) || ((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__O1zDbSYyG8zQytyoZAh0dg_10)));
	nimln_(117);	state_1 = ((NI)0);
	nimln_(118);	joinPathImpl__stdZprivateZospaths2_u48((&result), (&state_1), head_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(119);	joinPathImpl__stdZprivateZospaths2_u48((&result), (&state_1), tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPathOpenArray)(NimStringV2* parts_p0, NI parts_p0Len_0) {
	NimStringV2 result;
	NI estimatedLen_1;
	NI state_1;
NIM_BOOL* nimErr_;
	nimfr_("joinPath", "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(153);	estimatedLen_1 = ((NI)0);
	{
		NimStringV2* p_1;
		NI i_1;
		p_1 = (NimStringV2*)0;
		nimlf_(18, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(19);			while (1) {
				NI TM__O1zDbSYyG8zQytyoZAh0dg_21;
				if (!(i_1 < parts_p0Len_0)) goto LA3;
				nimlf_(154, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");				if (i_1 < 0 || i_1 >= parts_p0Len_0){ raiseIndexError2(i_1,parts_p0Len_0-1); goto BeforeRet_;
				}
				p_1 = (&parts_p0[i_1]);
				if (nimAddInt(estimatedLen_1, (*p_1).len, &TM__O1zDbSYyG8zQytyoZAh0dg_21)) { raiseOverflow(); goto BeforeRet_;
				};
				estimatedLen_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_21);
				nimlf_(13, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators.nim");				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(155, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");	if ((estimatedLen_1) < ((NI)0) || (estimatedLen_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(estimatedLen_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString((estimatedLen_1));
	nimln_(156);	state_1 = ((NI)0);
	{
		NI i_2;
		NI colontmp_;
		NI res_1;
		i_2 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		nimlf_(157, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");		colontmp_ = (parts_p0Len_0-1);
		nimlf_(96, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NI TM__O1zDbSYyG8zQytyoZAh0dg_22;
				if (!(res_1 <= colontmp_)) goto LA6;
				nimlf_(157, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\ospaths2.nim");				i_2 = ((NI) (res_1));
				nimln_(158);				if (i_2 < 0 || i_2 >= parts_p0Len_0){ raiseIndexError2(i_2,parts_p0Len_0-1); goto BeforeRet_;
				}
				joinPathImpl__stdZprivateZospaths2_u48((&result), (&state_1), parts_p0[i_2]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(102, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__O1zDbSYyG8zQytyoZAh0dg_22)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__O1zDbSYyG8zQytyoZAh0dg_22);
			} LA6: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
