/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@psystem@sdollars.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@psystem@sdollars.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u187)(NimStringV2* result_p0, NI64 x_p1);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, addFloat__system_u4907)(NimStringV2* result_p0, NF x_p1);
N_LIB_PRIVATE N_NIMCALL(void, addFloatRoundtrip__system_u4912)(NimStringV2* result_p0, NF x_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_3 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_6 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1) {
	nimfr_("addInt", "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\digitsutils.nim");
	nimlf_(116, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\digitsutils.nim");	addInt__stdZprivateZdigitsutils_u187(result_p0, ((NI64) (x_p1)));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0) {
	NimStringV2 result;
	nimfr_("$", "K:\\Progz\\nim-2.2.6\\lib\\system\\dollars.nim");
	nimlf_(20, "K:\\Progz\\nim-2.2.6\\lib\\system\\dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_4;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), xX60gensym0__p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u34)(NI64 xX60gensym4__p0) {
	NimStringV2 result;
	nimfr_("$", "K:\\Progz\\nim-2.2.6\\lib\\system\\dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u187((&result), xX60gensym4__p0);
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, addFloat__system_u4907)(NimStringV2* result_p0, NF x_p1) {
NIM_BOOL* nimErr_;
	nimfr_("addFloat", "K:\\Progz\\nim-2.2.6\\lib\\std\\formatfloat.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(142, "K:\\Progz\\nim-2.2.6\\lib\\std\\formatfloat.nim");	addFloatRoundtrip__system_u4912(result_p0, x_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_u4903)(NF x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "K:\\Progz\\nim-2.2.6\\lib\\system\\dollars.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(14, "K:\\Progz\\nim-2.2.6\\lib\\system\\dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_5;
	nimln_(15);	addFloat__system_u4907((&result), x_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0) {
	NimStringV2 result;
	nimfr_("$", "K:\\Progz\\nim-2.2.6\\lib\\system\\dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_6;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), ((NI) (xX60gensym3__p0)));
	popFrame();
	return result;
}
