/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@ptimes.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@ptimes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_Time__4WTh4uraGRwIK9abeHd66Xw tyObject_Time__4WTh4uraGRwIK9abeHd66Xw;
typedef struct tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg;
typedef struct tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg;
typedef struct tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg;
typedef struct tyTuple__R7ylOuMV2EoTykm7WC15Zw tyTuple__R7ylOuMV2EoTykm7WC15Zw;
typedef struct tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ;
typedef struct RootObj RootObj;
typedef struct tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w;
typedef struct tyTuple__9bDuq5lKllnHHKqT6vicMTA tyTuple__9bDuq5lKllnHHKqT6vicMTA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_Time__4WTh4uraGRwIK9abeHd66Xw x_p0, tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* Result, void* ClE_0);
void* ClE_0;
} tyProc__tcKV2iS3YOGzPD06HjxCSg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag {
	tyProc__tcKV2iS3YOGzPD06HjxCSg zonedTimeFromTimeImpl;
	tyProc__tcKV2iS3YOGzPD06HjxCSg zonedTimeFromAdjTimeImpl;
	NimStringV2 name;
};
struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg {
	NI rc;
	NI rootIdx;
};
struct tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg {
	NI len;
	NI cap;
	tyTuple__R7ylOuMV2EoTykm7WC15Zw* d;
};
struct tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg {
	tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q traceStack;
	tyObject_CellSeq__MjoVXz9anD2q8xrRCjG6XHg toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef NU8 tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw;
struct tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ {
	RootObj Sup;
	NI nanosecond;
	NI second;
	NI minute;
	NI hour;
	NI monthdayZero;
	NI monthZero;
	NI year;
	tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw weekday;
	NI yearday;
	NIM_BOOL isDst;
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* timezone;
	NI utcOffset;
};
struct tyObject_Time__4WTh4uraGRwIK9abeHd66Xw {
	NI64 seconds;
	NI nanosecond;
};
typedef NU8 tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg;
struct tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w {
	NI64 seconds;
	NI nanosecond;
};
typedef NU8 tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ;
typedef NI64 tyArray__MpDnbMAHoBSG9cUB0Gp9bYSw[8];
struct tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ {
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw time;
	NI utcOffset;
	NIM_BOOL isDst;
};
struct tyTuple__9bDuq5lKllnHHKqT6vicMTA {
	NI Field0;
	tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg Field1;
	NI Field2;
};
typedef NI tyArray__OJNtrzO4UatVMj5CiFeZ9ag[12];
typedef N_CLOSURE_PTR(void, TM__6NbDwwj5FY059b1gz2AsAZQ_103) (tyObject_Time__4WTh4uraGRwIK9abeHd66Xw x_p0, tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* Result);
typedef N_CLOSURE_PTR(void, TM__6NbDwwj5FY059b1gz2AsAZQ_106) (tyObject_Time__4WTh4uraGRwIK9abeHd66Xw time_p0, tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* Result, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM__6NbDwwj5FY059b1gz2AsAZQ_107) (tyObject_Time__4WTh4uraGRwIK9abeHd66Xw adjTime_p0, tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* Result, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZtimes_u5498)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u1570)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3431)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZtimes_u1582)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u2971)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u2979)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZtimes_u5500)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u1712)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZtimes_u1724)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRef)(void* q_p0, TNimTypeV2* desc_p1, void* env_p2);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NI64, toEpochDay__pureZtimes_u183)(NI monthday_p0, tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p1, NI year_p2);
static N_INLINE(void, assertValidDate__pureZtimes_u151)(NI monthday_p0, tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p1, NI year_p2);
N_LIB_PRIVATE N_NIMCALL(NI, getDaysInMonth__pureZtimes_u147)(tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p0, NI year_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isLeapYear__pureZtimes_u144)(NI year_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuIntToStr)(NI x_p0, NI minchars_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static N_INLINE(NI, monthday__pureZtimes_u1491)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dt_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg, month__pureZtimes_u1499)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dt_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, initTime__pureZtimes_u1200)(NI64 unix_p0, NI nanosecond_p1);
N_LIB_PRIVATE N_NIMCALL(void, initDateTime__pureZtimes_u1690)(tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* zt_p0, tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* zone_p1, tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, ntSubTime)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw a_p0, tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w b_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, normalize__pureZtimes_u1330)(NI64 seconds_p0, NI64 nanoseconds_p1);
static N_INLINE(NI64, convert__pureZtimes_u511)(tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ unitFrom_p0, tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ unitTo_p1, NI64 quantity_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2);
static N_INLINE(NI, convert__pureZtimes_u595)(tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ unitFrom_p0, tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ unitTo_p1, NI quantity_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w, initDuration__pureZtimes_u501)(NI64 nanoseconds_p0, NI64 microseconds_p1, NI64 milliseconds_p2, NI64 seconds_p3, NI64 minutes_p4, NI64 hours_p5, NI64 days_p6, NI64 weeks_p7);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w, normalize__pureZtimes_u580)(NI64 seconds_p0, NI64 nanoseconds_p1);
N_LIB_PRIVATE N_NIMCALL(NI64, floorDiv__pureZtimes_u317)(NI64 x_p0, NI64 y_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__9bDuq5lKllnHHKqT6vicMTA, fromEpochDay__pureZtimes_u203)(NI64 epochday_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw, getDayOfWeek__pureZtimes_u311)(NI monthday_p0, tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p1, NI year_p2);
N_LIB_PRIVATE N_NIMCALL(NI, getDayOfYear__pureZtimes_u266)(NI monthday_p0, tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p1, NI year_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError3)(NI i_p0, NI a_p1, NI b_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag*, eqdup___pureZtimes_u1557)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* src_p0, NIM_BOOL cyclic_p1);
N_LIB_PRIVATE N_NIMCALL(void, zonedTimeFromTime__pureZtimes_u1805)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* zone_p0, tyObject_Time__4WTh4uraGRwIK9abeHd66Xw time_p1, tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZtimes_u1561)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag** dest_p0, tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag*, newTimezone__pureZtimes_u1761)(NimStringV2 name_p0, tyProc__tcKV2iS3YOGzPD06HjxCSg zonedTimeFromTimeImpl_p1, tyProc__tcKV2iS3YOGzPD06HjxCSg zonedTimeFromAdjTimeImpl_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2664)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdup___pureZtimes_u1780)(tyProc__tcKV2iS3YOGzPD06HjxCSg src_p0, NIM_BOOL cyclic_p1, tyProc__tcKV2iS3YOGzPD06HjxCSg* Result);
N_LIB_PRIVATE N_NIMCALL(void, utcTzInfo__pureZtimes_u2065)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw time_p0, tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, eqdup___pureZtimes_u1213)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u1550)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZtimes_u1553)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag** dest_p0, tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isInitialized__pureZtimes_u1636)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dt_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ntEqTime)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw a_p0, tyObject_Time__4WTh4uraGRwIK9abeHd66Xw b_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, toTime__pureZtimes_u1660)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dt_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__dfW7lUzCkQZeKePAkY3nag_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__SbWCAn9czJMfLxIKVQMb1kQ_;
static const struct {
  NI cap; NIM_CHAR data[92+1];
} TM__6NbDwwj5FY059b1gz2AsAZQ_4 = { 92 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim(1159, 3) `dt.monthdayZero != 0` Uninitialized datetime" };
static const NimStringV2 TM__6NbDwwj5FY059b1gz2AsAZQ_5 = {92, (NimStrPayload*)&TM__6NbDwwj5FY059b1gz2AsAZQ_4};
static const struct {
  NI cap; NIM_CHAR data[88+1];
} TM__6NbDwwj5FY059b1gz2AsAZQ_6 = { 88 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim(482, 3) `monthday <= getDaysInMonth(month, year)` " };
static const NimStringV2 TM__6NbDwwj5FY059b1gz2AsAZQ_7 = {88, (NimStrPayload*)&TM__6NbDwwj5FY059b1gz2AsAZQ_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__6NbDwwj5FY059b1gz2AsAZQ_9 = { 1 | NIM_STRLIT_FLAG, "-" };
static const NimStringV2 TM__6NbDwwj5FY059b1gz2AsAZQ_10 = {1, (NimStrPayload*)&TM__6NbDwwj5FY059b1gz2AsAZQ_9};
static const NimStringV2 TM__6NbDwwj5FY059b1gz2AsAZQ_11 = {1, (NimStrPayload*)&TM__6NbDwwj5FY059b1gz2AsAZQ_9};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__6NbDwwj5FY059b1gz2AsAZQ_12 = { 20 | NIM_STRLIT_FLAG, " is not a valid date" };
static const NimStringV2 TM__6NbDwwj5FY059b1gz2AsAZQ_13 = {20, (NimStrPayload*)&TM__6NbDwwj5FY059b1gz2AsAZQ_12};
static const struct {
  NI cap; NIM_CHAR data[93+1];
} TM__6NbDwwj5FY059b1gz2AsAZQ_30 = { 93 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim(1081, 28) `dt.monthdayZero != 0` Uninitialized datetime" };
static const NimStringV2 TM__6NbDwwj5FY059b1gz2AsAZQ_31 = {93, (NimStrPayload*)&TM__6NbDwwj5FY059b1gz2AsAZQ_30};
static const struct {
  NI cap; NIM_CHAR data[93+1];
} TM__6NbDwwj5FY059b1gz2AsAZQ_32 = { 93 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim(1088, 28) `dt.monthdayZero != 0` Uninitialized datetime" };
static const NimStringV2 TM__6NbDwwj5FY059b1gz2AsAZQ_33 = {93, (NimStrPayload*)&TM__6NbDwwj5FY059b1gz2AsAZQ_32};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__6NbDwwj5FY059b1gz2AsAZQ_104 = { 7 | NIM_STRLIT_FLAG, "Etc/UTC" };
static const NimStringV2 TM__6NbDwwj5FY059b1gz2AsAZQ_105 = {7, (NimStrPayload*)&TM__6NbDwwj5FY059b1gz2AsAZQ_104};
N_LIB_PRIVATE NIM_CONST tyArray__MpDnbMAHoBSG9cUB0Gp9bYSw unitWeights__pureZtimes_u124 = {IL64(1),
IL64(1000),
IL64(1000000),
IL64(1000000000),
IL64(60000000000),
IL64(3600000000000),
IL64(86400000000000),
IL64(604800000000000)}
;
N_LIB_PRIVATE NIM_CONST tyArray__OJNtrzO4UatVMj5CiFeZ9ag daysUntilMonthLeap__pureZtimes_u272 = {((NI)0),
((NI)31),
((NI)60),
((NI)91),
((NI)121),
((NI)152),
((NI)182),
((NI)213),
((NI)244),
((NI)274),
((NI)305),
((NI)335)}
;
N_LIB_PRIVATE NIM_CONST tyArray__OJNtrzO4UatVMj5CiFeZ9ag daysUntilMonth__pureZtimes_u271 = {((NI)0),
((NI)31),
((NI)59),
((NI)90),
((NI)120),
((NI)151),
((NI)181),
((NI)212),
((NI)243),
((NI)273),
((NI)304),
((NI)334)}
;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* utcInstance__pureZtimes_u2068;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* localInstance__pureZtimes_u2069;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static NIM_CONST NU32 TM__6NbDwwj5FY059b1gz2AsAZQ_2[1] = {4122711296};
N_LIB_PRIVATE TNimTypeV2 NTIv2__dfW7lUzCkQZeKePAkY3nag_ = {.destructor = (void*)rttiDestroy__pureZtimes_u5498, .size = sizeof(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag), .align = (NI16) NIM_ALIGNOF(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag), .depth = 0, .display = TM__6NbDwwj5FY059b1gz2AsAZQ_2, .traceImpl = (void*)eqtrace___pureZtimes_u1582, .flags = 0};
static NIM_CONST NU32 TM__6NbDwwj5FY059b1gz2AsAZQ_3[2] = {3701606400, 3045196288};
N_LIB_PRIVATE TNimTypeV2 NTIv2__SbWCAn9czJMfLxIKVQMb1kQ_ = {.destructor = (void*)rttiDestroy__pureZtimes_u5500, .size = sizeof(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ), .align = (NI16) NIM_ALIGNOF(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ), .depth = 1, .display = TM__6NbDwwj5FY059b1gz2AsAZQ_3, .traceImpl = (void*)eqtrace___pureZtimes_u1724, .flags = 0};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimlf_(364, "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimlf_(518, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T5_));
		nimlf_(521, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3431(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u1570)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* dest_p0) {
	if ((*dest_p0).name.p && !((*dest_p0).name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).name.p);
}
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).zonedTimeFromAdjTimeImpl.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).zonedTimeFromAdjTimeImpl.ClE_0);
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).zonedTimeFromTimeImpl.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).zonedTimeFromTimeImpl.ClE_0);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZtimes_u5498)(void* dest_p0) {
	eqdestroy___pureZtimes_u1570(((tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag*) (dest_p0)));
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimlf_(353, "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");	nimln_(357);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u2971)(tyObject_CellSeq__3cx9bpyr9bZqFasqbmRVJ57Q* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "K:\\Progz\\nim-2.2.6\\lib\\system\\cellseqs_v2.nim");
	nimlf_(28, "K:\\Progz\\nim-2.2.6\\lib\\system\\cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u2979(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimlf_(138, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg*) (env_p1));
		nimln_(141);		add__system_u2971((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZtimes_u1582)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).zonedTimeFromTimeImpl.ClE_0), env_p1);
	nimTraceRefDyn((&(*dest_p0).zonedTimeFromAdjTimeImpl.ClE_0), env_p1);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicStatic", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimln_(544);	result = NIM_FALSE;
	nimln_(545);	{
		tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(546);		nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T5_));
		nimlf_(547, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(548);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(551);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(553);		rememberCycle__system_u3431(result, cell_1, desc_p1);
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u1712)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic((*dest_p0).timezone, ((TNimTypeV2*) ((&NTIv2__dfW7lUzCkQZeKePAkY3nag_))));
		if (!T3_) goto LA4_;
		eqdestroy___pureZtimes_u1570((&(*(*dest_p0).timezone)));
		nimRawDispose((*dest_p0).timezone, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZtimes_u5500)(void* dest_p0) {
	eqdestroy___pureZtimes_u1712(((tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ*) (dest_p0)));
}
static N_INLINE(void, nimTraceRef)(void* q_p0, TNimTypeV2* desc_p1, void* env_p2) {
	void** p_1;
	nimfr_("nimTraceRef", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimln_(129);	p_1 = ((void**) (q_p0));
	nimln_(130);	{
		tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(134);		j_1 = ((tyObject_GcEnv__ieaSfaLCsCTm9cePmaU82vg*) (env_p2));
		nimln_(135);		add__system_u2971((&(*j_1).traceStack), p_1, desc_p1);
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZtimes_u1724)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dest_p0, void* env_p1) {
	nimTraceRef(&(*dest_p0).timezone, ((TNimTypeV2*) ((&NTIv2__dfW7lUzCkQZeKePAkY3nag_))), env_p1);
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* h_1;
	NI T1_;
	nimfr_("nimIncRefCyclic", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimln_(47);	nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	h_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T1_));
	nimlf_(48, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZtimes_u1715)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dest_p0, tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* src_p1) {
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* colontmp_;
	(*dest_p0).nanosecond = (*src_p1).nanosecond;
	(*dest_p0).second = (*src_p1).second;
	(*dest_p0).minute = (*src_p1).minute;
	(*dest_p0).hour = (*src_p1).hour;
	(*dest_p0).monthdayZero = (*src_p1).monthdayZero;
	(*dest_p0).monthZero = (*src_p1).monthZero;
	(*dest_p0).year = (*src_p1).year;
	(*dest_p0).weekday = (*src_p1).weekday;
	(*dest_p0).yearday = (*src_p1).yearday;
	(*dest_p0).isDst = (*src_p1).isDst;
	colontmp_ = (*dest_p0).timezone;
	{
		if (!(*src_p1).timezone) goto LA3_;
		nimIncRefCyclic((*src_p1).timezone, NIM_TRUE);
	}
LA3_: ;
	(*dest_p0).timezone = (*src_p1).timezone;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicStatic(colontmp_, ((TNimTypeV2*) ((&NTIv2__dfW7lUzCkQZeKePAkY3nag_))));
		if (!T7_) goto LA8_;
		eqdestroy___pureZtimes_u1570((&(*colontmp_)));
		nimRawDispose(colontmp_, ((NI)8));
	}
LA8_: ;
	(*dest_p0).utcOffset = (*src_p1).utcOffset;
	(*dest_p0).Sup.m_type = (*src_p1).Sup.m_type;
}
N_LIB_PRIVATE N_NIMCALL(NI64, toUnix__pureZtimes_u1230)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw t_p0) {
	NI64 result;
	nimfr_("toUnix", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
	nimlf_(933, "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");	result = t_p0.seconds;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isLeapYear__pureZtimes_u144)(NI year_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T3_;
	nimfr_("isLeapYear", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
	result = (NIM_BOOL)0;
	nimln_(463);	nimln_(467);	T1_ = (NIM_BOOL)0;
	T1_ = ((NI)((year_p0) % (((NI)4))) == ((NI)0));
	if (!(T1_)) goto LA2_;
	T3_ = (NIM_BOOL)0;
	T3_ = !(((NI)((year_p0) % (((NI)100))) == ((NI)0)));
	if (T3_) goto LA4_;
	T3_ = ((NI)((year_p0) % (((NI)400))) == ((NI)0));
LA4_: ;
	T1_ = T3_;
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getDaysInMonth__pureZtimes_u147)(tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p0, NI year_p1) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("getDaysInMonth", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimln_(475);	switch (month_p0) {
	case ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)2):
	{
		NI colontmpD_;
		NI colontmpD__2;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimln_(476);		{
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = isLeapYear__pureZtimes_u144(year_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T4_) goto LA5_;
			colontmpD_ = ((NI)29);
			result = colontmpD_;
		}
		goto LA2_;
LA5_: ;
		{
			colontmpD__2 = ((NI)28);
			result = colontmpD__2;
		}
LA2_: ;
	}
	break;
	case ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)4):
	case ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)6):
	case ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)9):
	case ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)11):
	{
		nimln_(477);		result = ((NI)30);
	}
	break;
	default:
	{
		nimln_(478);		result = ((NI)31);
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__6NbDwwj5FY059b1gz2AsAZQ_8;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__6NbDwwj5FY059b1gz2AsAZQ_8)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_8);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, assertValidDate__pureZtimes_u151)(NI monthday_p0, tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p1, NI year_p2) {
NIM_BOOL* nimErr_;
	nimfr_("assertValidDate", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimln_(482);	{
		NI T3_;
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 colontmpD__3;
		NimStringV2 colontmpD__4;
		NimStringV2 T6_;
		T3_ = (NI)0;
		T3_ = getDaysInMonth__pureZtimes_u147(month_p1, year_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!((monthday_p0 <= T3_))) goto LA4_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		T6_.len = 0; T6_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u14(year_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__2 = nsuIntToStr(month_p1, ((NI)2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__3 = dollar___systemZdollars_u14(monthday_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T6_ = rawNewString(colontmpD_.len + colontmpD__2.len + colontmpD__3.len + 110);
appendString((&T6_), TM__6NbDwwj5FY059b1gz2AsAZQ_7);
appendString((&T6_), colontmpD_);
appendString((&T6_), TM__6NbDwwj5FY059b1gz2AsAZQ_10);
appendString((&T6_), colontmpD__2);
appendString((&T6_), TM__6NbDwwj5FY059b1gz2AsAZQ_11);
appendString((&T6_), colontmpD__3);
appendString((&T6_), TM__6NbDwwj5FY059b1gz2AsAZQ_13);
		colontmpD__4 = T6_;
		failedAssertImpl__stdZassertions_u234(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(394, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI64, toEpochDay__pureZtimes_u183)(NI monthday_p0, tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p1, NI year_p2) {
	NI64 result;
	NI colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	NI y_1;
	NI m_1;
	NI d_1;
	NI era_1;
	NI T5_;
	NI yoe_1;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_16;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_17;
	NI doy_1;
	NI T11_;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_18;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_19;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_20;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_21;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_22;
	NI doe_1;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_23;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_24;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_25;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_26;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_27;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_28;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_29;
NIM_BOOL* nimErr_;
	nimfr_("toEpochDay", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	result = (NI64)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	nimlf_(491, "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");	assertValidDate__pureZtimes_u151(monthday_p0, month_p1, year_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(492);	y_1 = year_p2;
	m_1 = month_p1;
	d_1 = monthday_p0;
	nimln_(493);	{
		NI TM__6NbDwwj5FY059b1gz2AsAZQ_14;
		if (!(m_1 <= ((NI)2))) goto LA3_;
		nimln_(494);		if (nimSubInt(y_1, ((NI)1), &TM__6NbDwwj5FY059b1gz2AsAZQ_14)) { raiseOverflow(); goto BeforeRet_;
		};
		y_1 = (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_14);
	}
LA3_: ;
	nimln_(496);	T5_ = (NI)0;
	{
		if (!(((NI)0) <= y_1)) goto LA8_;
		colontmpD_ = y_1;
		T5_ = colontmpD_;
	}
	goto LA6_;
LA8_: ;
	{
		NI TM__6NbDwwj5FY059b1gz2AsAZQ_15;
		if (nimSubInt(y_1, ((NI)399), &TM__6NbDwwj5FY059b1gz2AsAZQ_15)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD__2 = (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_15);
		T5_ = colontmpD__2;
	}
LA6_: ;
	era_1 = (NI)((T5_) / (((NI)400)));
	nimln_(497);	if (nimMulInt(era_1, ((NI)400), &TM__6NbDwwj5FY059b1gz2AsAZQ_16)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt(y_1, (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_16), &TM__6NbDwwj5FY059b1gz2AsAZQ_17)) { raiseOverflow(); goto BeforeRet_;
	};
	yoe_1 = (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_17);
	nimln_(498);	T11_ = (NI)0;
	{
		if (!(((NI)2) < m_1)) goto LA14_;
		colontmpD__3 = ((NI)-3);
		T11_ = colontmpD__3;
	}
	goto LA12_;
LA14_: ;
	{
		colontmpD__4 = ((NI)9);
		T11_ = colontmpD__4;
	}
LA12_: ;
	if (nimAddInt(m_1, T11_, &TM__6NbDwwj5FY059b1gz2AsAZQ_18)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt(((NI)153), (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_18), &TM__6NbDwwj5FY059b1gz2AsAZQ_19)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_19), ((NI)2), &TM__6NbDwwj5FY059b1gz2AsAZQ_20)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_20)) / (((NI)5))), d_1, &TM__6NbDwwj5FY059b1gz2AsAZQ_21)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_21), ((NI)1), &TM__6NbDwwj5FY059b1gz2AsAZQ_22)) { raiseOverflow(); goto BeforeRet_;
	};
	doy_1 = (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_22);
	nimln_(499);	if (nimMulInt(yoe_1, ((NI)365), &TM__6NbDwwj5FY059b1gz2AsAZQ_23)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_23), (NI)((yoe_1) / (((NI)4))), &TM__6NbDwwj5FY059b1gz2AsAZQ_24)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_24), (NI)((yoe_1) / (((NI)100))), &TM__6NbDwwj5FY059b1gz2AsAZQ_25)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_25), doy_1, &TM__6NbDwwj5FY059b1gz2AsAZQ_26)) { raiseOverflow(); goto BeforeRet_;
	};
	doe_1 = (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_26);
	nimln_(500);	nimln_(486);	nimln_(500);	if (nimMulInt(era_1, ((NI)146097), &TM__6NbDwwj5FY059b1gz2AsAZQ_27)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_27), doe_1, &TM__6NbDwwj5FY059b1gz2AsAZQ_28)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_28), ((NI)719468), &TM__6NbDwwj5FY059b1gz2AsAZQ_29)) { raiseOverflow(); goto BeforeRet_;
	};
	result = ((NI64) ((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_29)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, monthday__pureZtimes_u1491)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dt_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("monthday", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(1080);	nimln_(1081);	{
		if (!!(!(((*dt_p0).monthdayZero == ((NI)0))))) goto LA3_;
		failedAssertImpl__stdZassertions_u234(TM__6NbDwwj5FY059b1gz2AsAZQ_31);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	result = ((NI) ((*dt_p0).monthdayZero));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg, month__pureZtimes_u1499)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dt_p0) {
	tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg result;
NIM_BOOL* nimErr_;
	nimfr_("month", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	result = (tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)0;
	nimln_(1086);	nimln_(1088);	{
		if (!!(!(((*dt_p0).monthdayZero == ((NI)0))))) goto LA3_;
		failedAssertImpl__stdZassertions_u234(TM__6NbDwwj5FY059b1gz2AsAZQ_33);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	result = ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg) ((*dt_p0).monthZero));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, initTime__pureZtimes_u1200)(NI64 unix_p0, NI nanosecond_p1) {
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw result;
	NI64 colontmpD_;
	NI colontmpD__2;
	nimfr_("initTime", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI)0;
	nimln_(917);	colontmpD_ = unix_p0;
	result.seconds = colontmpD_;
	colontmpD__2 = nanosecond_p1;
	result.nanosecond = colontmpD__2;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, toTime__pureZtimes_u1660)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dt_p0) {
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw result;
	NI64 epochDay_1;
	NI T5_;
	tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg T6_;
	NI64 seconds_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_34;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_35;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_36;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_37;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_38;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_39;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_40;
NIM_BOOL* nimErr_;
	nimfr_("toTime", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw));
	nimln_(1159);	{
		if (!!(!(((*dt_p0).monthdayZero == ((NI)0))))) goto LA3_;
		failedAssertImpl__stdZassertions_u234(TM__6NbDwwj5FY059b1gz2AsAZQ_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(1160);	T5_ = (NI)0;
	T5_ = monthday__pureZtimes_u1491(dt_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = (tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)0;
	T6_ = month__pureZtimes_u1499(dt_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	epochDay_1 = toEpochDay__pureZtimes_u183(T5_, T6_, (*dt_p0).year);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1161);	if (nimMulInt64(epochDay_1, IL64(86400), &TM__6NbDwwj5FY059b1gz2AsAZQ_34)) { raiseOverflow(); goto BeforeRet_;
	};
	seconds_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_34);
	nimln_(1162);	if (nimMulInt((*dt_p0).hour, ((NI)3600), &TM__6NbDwwj5FY059b1gz2AsAZQ_35)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64(seconds_1, (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_35), &TM__6NbDwwj5FY059b1gz2AsAZQ_36)) { raiseOverflow(); goto BeforeRet_;
	};
	seconds_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_36);
	nimln_(1163);	if (nimMulInt((*dt_p0).minute, ((NI)60), &TM__6NbDwwj5FY059b1gz2AsAZQ_37)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64(seconds_1, (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_37), &TM__6NbDwwj5FY059b1gz2AsAZQ_38)) { raiseOverflow(); goto BeforeRet_;
	};
	seconds_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_38);
	nimln_(1164);	if (nimAddInt64(seconds_1, (*dt_p0).second, &TM__6NbDwwj5FY059b1gz2AsAZQ_39)) { raiseOverflow(); goto BeforeRet_;
	};
	seconds_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_39);
	nimln_(1165);	if (nimAddInt64(seconds_1, (*dt_p0).utcOffset, &TM__6NbDwwj5FY059b1gz2AsAZQ_40)) { raiseOverflow(); goto BeforeRet_;
	};
	seconds_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_40);
	nimln_(1166);	result = initTime__pureZtimes_u1200(seconds_1, (*dt_p0).nanosecond);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2) {
	NIM_BOOL result;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a_p0 == (IL64(-9223372036854775807) - IL64(1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b_p1 == IL64(-1));
LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_FALSE;
		(*res_p2) = (NI64)(a_p0 / b_p1);
	}
LA1_: ;
	return result;
}
static N_INLINE(NI64, convert__pureZtimes_u511)(tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ unitFrom_p0, tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ unitTo_p1, NI64 quantity_p2) {
	NI64 result;
	NI64 colontmpD_;
	NI64 colontmpD__2;
	nimfr_("convert", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{	result = (NI64)0;
	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI64)0;
	nimln_(439);	nimln_(445);	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_41;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_42;
		if (!(unitFrom_p0 < unitTo_p1)) goto LA3_;
		nimln_(446);		if (unitWeights__pureZtimes_u124[(unitFrom_p0)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__pureZtimes_u124[(unitTo_p1)- 0], unitWeights__pureZtimes_u124[(unitFrom_p0)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_41)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_41) == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(quantity_p2, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_41), &TM__6NbDwwj5FY059b1gz2AsAZQ_42)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD_ = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_42);
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_43;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_44;
		nimln_(448);		if (unitWeights__pureZtimes_u124[(unitTo_p1)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__pureZtimes_u124[(unitFrom_p0)- 0], unitWeights__pureZtimes_u124[(unitTo_p1)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_43)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_43), quantity_p2, &TM__6NbDwwj5FY059b1gz2AsAZQ_44)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD__2 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_44);
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, convert__pureZtimes_u595)(tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ unitFrom_p0, tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ unitTo_p1, NI quantity_p2) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	nimfr_("convert", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(439);	nimln_(445);	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_46;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_47;
		if (!(unitFrom_p0 < unitTo_p1)) goto LA3_;
		nimln_(446);		if (unitWeights__pureZtimes_u124[(unitFrom_p0)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__pureZtimes_u124[(unitTo_p1)- 0], unitWeights__pureZtimes_u124[(unitFrom_p0)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_46)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_46) == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(((NI64) (quantity_p2)), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_46), &TM__6NbDwwj5FY059b1gz2AsAZQ_47)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD_ = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_47)));
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_48;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_49;
		nimln_(448);		if (unitWeights__pureZtimes_u124[(unitTo_p1)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__pureZtimes_u124[(unitFrom_p0)- 0], unitWeights__pureZtimes_u124[(unitTo_p1)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_48)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_48), ((NI64) (quantity_p2)), &TM__6NbDwwj5FY059b1gz2AsAZQ_49)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD__2 = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_49)));
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, normalize__pureZtimes_u1330)(NI64 seconds_p0, NI64 nanoseconds_p1) {
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw result;
	NI64 T1_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_45;
	NI64 nanosecond_1;
	NI T2_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_50;
NIM_BOOL* nimErr_;
	nimfr_("normalize", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimln_(454);	nimZeroMem((void*)(&result), sizeof(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw));
	nimln_(455);	T1_ = (NI64)0;
	T1_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), nanoseconds_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64(seconds_p0, T1_, &TM__6NbDwwj5FY059b1gz2AsAZQ_45)) { raiseOverflow(); goto BeforeRet_;
	};
	result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_45);
	nimln_(456);	T2_ = (NI)0;
	T2_ = convert__pureZtimes_u595(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (((NI64) (T2_)) == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimModInt64(nanoseconds_p1, ((NI64) (T2_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_50)) { raiseOverflow(); goto BeforeRet_;
	};
	nanosecond_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_50);
	nimln_(457);	{
		NI T7_;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_51;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_52;
		if (!(nanosecond_1 < IL64(0))) goto LA5_;
		nimln_(458);		T7_ = (NI)0;
		T7_ = convert__pureZtimes_u595(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt64(nanosecond_1, ((NI64) (T7_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_51)) { raiseOverflow(); goto BeforeRet_;
		};
		nanosecond_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_51);
		nimln_(459);		if (nimSubInt64(result.seconds, IL64(1), &TM__6NbDwwj5FY059b1gz2AsAZQ_52)) { raiseOverflow(); goto BeforeRet_;
		};
		result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_52);
	}
LA5_: ;
	nimln_(460);	if ((((NI) (nanosecond_1))) < ((NI)0) || (((NI) (nanosecond_1))) > ((NI)999999999)){ raiseRangeErrorI(((NI) (nanosecond_1)), ((NI)0), ((NI)999999999)); goto BeforeRet_;
	}
	result.nanosecond = (((NI) (nanosecond_1)));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, ntSubTime)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw a_p0, tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w b_p1) {
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw result;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_53;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_54;
NIM_BOOL* nimErr_;
	nimfr_("-", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw));
	nimln_(1017);	nimln_(1020);	nimln_(638);	if (nimSubInt64(a_p0.seconds, b_p1.seconds, &TM__6NbDwwj5FY059b1gz2AsAZQ_53)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt(a_p0.nanosecond, b_p1.nanosecond, &TM__6NbDwwj5FY059b1gz2AsAZQ_54)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(1020);	result = normalize__pureZtimes_u1330((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_53), ((NI64) ((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_54))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w, normalize__pureZtimes_u580)(NI64 seconds_p0, NI64 nanoseconds_p1) {
	tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w result;
	NI64 T1_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_64;
	NI64 nanosecond_1;
	NI T2_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_65;
NIM_BOOL* nimErr_;
	nimfr_("normalize", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimln_(454);	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w));
	nimln_(455);	T1_ = (NI64)0;
	T1_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), nanoseconds_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64(seconds_p0, T1_, &TM__6NbDwwj5FY059b1gz2AsAZQ_64)) { raiseOverflow(); goto BeforeRet_;
	};
	result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_64);
	nimln_(456);	T2_ = (NI)0;
	T2_ = convert__pureZtimes_u595(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (((NI64) (T2_)) == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimModInt64(nanoseconds_p1, ((NI64) (T2_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_65)) { raiseOverflow(); goto BeforeRet_;
	};
	nanosecond_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_65);
	nimln_(457);	{
		NI T7_;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_66;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_67;
		if (!(nanosecond_1 < IL64(0))) goto LA5_;
		nimln_(458);		T7_ = (NI)0;
		T7_ = convert__pureZtimes_u595(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt64(nanosecond_1, ((NI64) (T7_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_66)) { raiseOverflow(); goto BeforeRet_;
		};
		nanosecond_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_66);
		nimln_(459);		if (nimSubInt64(result.seconds, IL64(1), &TM__6NbDwwj5FY059b1gz2AsAZQ_67)) { raiseOverflow(); goto BeforeRet_;
		};
		result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_67);
	}
LA5_: ;
	nimln_(460);	if ((((NI) (nanosecond_1))) < ((NI)0) || (((NI) (nanosecond_1))) > ((NI)999999999)){ raiseRangeErrorI(((NI) (nanosecond_1)), ((NI)0), ((NI)999999999)); goto BeforeRet_;
	}
	result.nanosecond = (((NI) (nanosecond_1)));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w, initDuration__pureZtimes_u501)(NI64 nanoseconds_p0, NI64 microseconds_p1, NI64 milliseconds_p2, NI64 seconds_p3, NI64 minutes_p4, NI64 hours_p5, NI64 days_p6, NI64 weeks_p7) {
	tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w result;
	NI64 seconds_2;
	NI64 T1_;
	NI64 T2_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_55;
	NI64 T3_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_56;
	NI64 T4_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_57;
	NI64 T5_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_58;
	NI64 T6_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_59;
	NI64 T7_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_60;
	NI64 T8_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_61;
	NI nanoseconds_2;
	NI64 T9_;
	NI64 T10_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_62;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_63;
NIM_BOOL* nimErr_;
	nimfr_("initDuration", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w));
	nimln_(673);	nimln_(679);	nimln_(678);	nimln_(677);	nimln_(676);	nimln_(675);	nimln_(674);	nimln_(673);	T1_ = (NI64)0;
	T1_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)7), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), weeks_p7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(674);	T2_ = (NI64)0;
	T2_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)6), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), days_p6);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64(T1_, T2_, &TM__6NbDwwj5FY059b1gz2AsAZQ_55)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(675);	T3_ = (NI64)0;
	T3_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)4), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), minutes_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_55), T3_, &TM__6NbDwwj5FY059b1gz2AsAZQ_56)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(676);	T4_ = (NI64)0;
	T4_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)5), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), hours_p5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_56), T4_, &TM__6NbDwwj5FY059b1gz2AsAZQ_57)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(677);	T5_ = (NI64)0;
	T5_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), seconds_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_57), T5_, &TM__6NbDwwj5FY059b1gz2AsAZQ_58)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(678);	T6_ = (NI64)0;
	T6_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)2), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), milliseconds_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_58), T6_, &TM__6NbDwwj5FY059b1gz2AsAZQ_59)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(679);	T7_ = (NI64)0;
	T7_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)1), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), microseconds_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_59), T7_, &TM__6NbDwwj5FY059b1gz2AsAZQ_60)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(680);	T8_ = (NI64)0;
	T8_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)3), nanoseconds_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_60), T8_, &TM__6NbDwwj5FY059b1gz2AsAZQ_61)) { raiseOverflow(); goto BeforeRet_;
	};
	seconds_2 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_61);
	nimln_(681);	nimln_(682);	nimln_(681);	T9_ = (NI64)0;
	T9_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)2), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), (NI64)((milliseconds_p2) % (IL64(1000))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(682);	T10_ = (NI64)0;
	T10_ = convert__pureZtimes_u511(((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)1), ((tyEnum_TimeUnit__9c6LszR0jLbS3j29bQyqgfkQ)0), (NI64)((microseconds_p1) % (IL64(1000000))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64(T9_, T10_, &TM__6NbDwwj5FY059b1gz2AsAZQ_62)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(683);	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_62), (NI64)((nanoseconds_p0) % (IL64(1000000000))), &TM__6NbDwwj5FY059b1gz2AsAZQ_63)) { raiseOverflow(); goto BeforeRet_;
	};
	nanoseconds_2 = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_63)));
	nimln_(685);	result = normalize__pureZtimes_u580(seconds_2, ((NI64) (nanoseconds_2)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__9bDuq5lKllnHHKqT6vicMTA, fromEpochDay__pureZtimes_u203)(NI64 epochday_p0) {
	tyTuple__9bDuq5lKllnHHKqT6vicMTA result;
	NI64 colontmpD_;
	NI64 colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	NI64 z_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_74;
	NI64 era_1;
	NI64 T1_;
	NI64 doe_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_76;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_77;
	NI64 yoe_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_78;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_79;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_80;
	NI64 y_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_81;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_82;
	NI64 doy_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_83;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_84;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_85;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_86;
	NI64 mp_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_87;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_88;
	NI64 d_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_89;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_90;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_91;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_92;
	NI64 m_1;
	NI T7_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_93;
	NI colontmp_;
	tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg colontmp__2;
	NI colontmp__3;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_94;
	nimfr_("fromEpochDay", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{	nimZeroMem((void*)(&result), sizeof(tyTuple__9bDuq5lKllnHHKqT6vicMTA));
	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI64)0;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	nimln_(508);	z_1 = epochday_p0;
	nimln_(509);	if (nimAddInt64(z_1, ((NI)719468), &TM__6NbDwwj5FY059b1gz2AsAZQ_74)) { raiseOverflow(); goto BeforeRet_;
	};
	z_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_74);
	nimln_(510);	T1_ = (NI64)0;
	{
		if (!(IL64(0) <= z_1)) goto LA4_;
		colontmpD_ = z_1;
		T1_ = colontmpD_;
	}
	goto LA2_;
LA4_: ;
	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_75;
		if (nimSubInt64(z_1, IL64(146096), &TM__6NbDwwj5FY059b1gz2AsAZQ_75)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD__2 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_75);
		T1_ = colontmpD__2;
	}
LA2_: ;
	era_1 = (NI64)((T1_) / (IL64(146097)));
	nimln_(511);	if (nimMulInt64(era_1, IL64(146097), &TM__6NbDwwj5FY059b1gz2AsAZQ_76)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64(z_1, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_76), &TM__6NbDwwj5FY059b1gz2AsAZQ_77)) { raiseOverflow(); goto BeforeRet_;
	};
	doe_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_77);
	nimln_(512);	if (nimSubInt64(doe_1, (NI64)((doe_1) / (IL64(1460))), &TM__6NbDwwj5FY059b1gz2AsAZQ_78)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_78), (NI64)((doe_1) / (IL64(36524))), &TM__6NbDwwj5FY059b1gz2AsAZQ_79)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_79), (NI64)((doe_1) / (IL64(146096))), &TM__6NbDwwj5FY059b1gz2AsAZQ_80)) { raiseOverflow(); goto BeforeRet_;
	};
	yoe_1 = (NI64)(((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_80)) / (IL64(365)));
	nimln_(513);	if (nimMulInt64(era_1, IL64(400), &TM__6NbDwwj5FY059b1gz2AsAZQ_81)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64(yoe_1, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_81), &TM__6NbDwwj5FY059b1gz2AsAZQ_82)) { raiseOverflow(); goto BeforeRet_;
	};
	y_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_82);
	nimln_(514);	if (nimMulInt64(IL64(365), yoe_1, &TM__6NbDwwj5FY059b1gz2AsAZQ_83)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_83), (NI64)((yoe_1) / (IL64(4))), &TM__6NbDwwj5FY059b1gz2AsAZQ_84)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_84), (NI64)((yoe_1) / (IL64(100))), &TM__6NbDwwj5FY059b1gz2AsAZQ_85)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64(doe_1, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_85), &TM__6NbDwwj5FY059b1gz2AsAZQ_86)) { raiseOverflow(); goto BeforeRet_;
	};
	doy_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_86);
	nimln_(515);	if (nimMulInt64(IL64(5), doy_1, &TM__6NbDwwj5FY059b1gz2AsAZQ_87)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_87), IL64(2), &TM__6NbDwwj5FY059b1gz2AsAZQ_88)) { raiseOverflow(); goto BeforeRet_;
	};
	mp_1 = (NI64)(((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_88)) / (IL64(153)));
	nimln_(516);	if (nimMulInt64(IL64(153), mp_1, &TM__6NbDwwj5FY059b1gz2AsAZQ_89)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_89), IL64(2), &TM__6NbDwwj5FY059b1gz2AsAZQ_90)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64(doy_1, (NI64)(((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_90)) / (IL64(5))), &TM__6NbDwwj5FY059b1gz2AsAZQ_91)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_91), IL64(1), &TM__6NbDwwj5FY059b1gz2AsAZQ_92)) { raiseOverflow(); goto BeforeRet_;
	};
	d_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_92);
	nimln_(517);	T7_ = (NI)0;
	{
		if (!(mp_1 < IL64(10))) goto LA10_;
		colontmpD__3 = ((NI)3);
		T7_ = colontmpD__3;
	}
	goto LA8_;
LA10_: ;
	{
		colontmpD__4 = ((NI)-9);
		T7_ = colontmpD__4;
	}
LA8_: ;
	if (nimAddInt64(mp_1, ((NI64) (T7_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_93)) { raiseOverflow(); goto BeforeRet_;
	};
	m_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_93);
	nimln_(518);	if ((d_1) < ((NI)1) || (d_1) > ((NI)31)){ raiseRangeErrorI(d_1, ((NI)1), ((NI)31)); goto BeforeRet_;
	}
	colontmp_ = ((NI) (d_1));
	if ((m_1) < ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)1) || (m_1) > ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)12)){ raiseRangeErrorI(m_1, ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)1), ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg)12)); goto BeforeRet_;
	}
	colontmp__2 = ((tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg) (m_1));
	if (nimAddInt64(y_1, ((NI64) ((m_1 <= IL64(2)))), &TM__6NbDwwj5FY059b1gz2AsAZQ_94)) { raiseOverflow(); goto BeforeRet_;
	};
	colontmp__3 = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_94)));
	nimln_(502);	nimln_(518);	result.Field0 = colontmp_;
	result.Field1 = colontmp__2;
	result.Field2 = colontmp__3;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw, getDayOfWeek__pureZtimes_u311)(NI monthday_p0, tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p1, NI year_p2) {
	tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw result;
	tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw colontmpD_;
	tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw colontmpD__2;
	NI64 days_1;
	NI64 T1_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_95;
	NI64 weeks_1;
	NI64 wd_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_96;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_97;
NIM_BOOL* nimErr_;
	nimfr_("getDayOfWeek", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	result = (tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)0;
	colontmpD_ = (tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)0;
	colontmpD__2 = (tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)0;
	nimln_(548);	assertValidDate__pureZtimes_u151(monthday_p0, month_p1, year_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(550);	T1_ = (NI64)0;
	T1_ = toEpochDay__pureZtimes_u183(monthday_p0, month_p1, year_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimSubInt64(T1_, IL64(3), &TM__6NbDwwj5FY059b1gz2AsAZQ_95)) { raiseOverflow(); goto BeforeRet_;
	};
	days_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_95);
	nimln_(551);	weeks_1 = floorDiv__pureZtimes_u317(days_1, IL64(7));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(552);	if (nimMulInt64(weeks_1, IL64(7), &TM__6NbDwwj5FY059b1gz2AsAZQ_96)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64(days_1, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_96), &TM__6NbDwwj5FY059b1gz2AsAZQ_97)) { raiseOverflow(); goto BeforeRet_;
	};
	wd_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_97);
	nimln_(555);	{
		if (!(wd_1 == IL64(0))) goto LA4_;
		colontmpD_ = ((tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)6);
		result = colontmpD_;
	}
	goto LA2_;
LA4_: ;
	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_98;
		if (nimSubInt64(wd_1, IL64(1), &TM__6NbDwwj5FY059b1gz2AsAZQ_98)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_98)) < ((tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)0) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_98)) > ((tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)6)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_98), ((tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)0), ((tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)6)); goto BeforeRet_;
		}
		colontmpD__2 = ((tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_98)));
		result = colontmpD__2;
	}
LA2_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getDayOfYear__pureZtimes_u266)(NI monthday_p0, tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg month_p1, NI year_p2) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("getDayOfYear", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(529);	assertValidDate__pureZtimes_u151(monthday_p0, month_p1, year_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(535);	{
		NIM_BOOL T3_;
		NI TM__6NbDwwj5FY059b1gz2AsAZQ_99;
		NI TM__6NbDwwj5FY059b1gz2AsAZQ_100;
		T3_ = (NIM_BOOL)0;
		T3_ = isLeapYear__pureZtimes_u144(year_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(536);		if (month_p1 < 1 || month_p1 > 12){ raiseIndexError3(month_p1, 1, 12); goto BeforeRet_;
		}
		if (nimAddInt(daysUntilMonthLeap__pureZtimes_u272[(month_p1)- 1], monthday_p0, &TM__6NbDwwj5FY059b1gz2AsAZQ_99)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_99), ((NI)1), &TM__6NbDwwj5FY059b1gz2AsAZQ_100)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_100)) < ((NI)0) || ((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_100)) > ((NI)365)){ raiseRangeErrorI((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_100), ((NI)0), ((NI)365)); goto BeforeRet_;
		}
		result = ((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_100));
	}
	goto LA1_;
LA4_: ;
	{
		NI TM__6NbDwwj5FY059b1gz2AsAZQ_101;
		NI TM__6NbDwwj5FY059b1gz2AsAZQ_102;
		nimln_(538);		if (month_p1 < 1 || month_p1 > 12){ raiseIndexError3(month_p1, 1, 12); goto BeforeRet_;
		}
		if (nimAddInt(daysUntilMonth__pureZtimes_u271[(month_p1)- 1], monthday_p0, &TM__6NbDwwj5FY059b1gz2AsAZQ_101)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_101), ((NI)1), &TM__6NbDwwj5FY059b1gz2AsAZQ_102)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_102)) < ((NI)0) || ((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_102)) > ((NI)365)){ raiseRangeErrorI((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_102), ((NI)0), ((NI)365)); goto BeforeRet_;
		}
		result = ((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_102));
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag*, eqdup___pureZtimes_u1557)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* src_p0, NIM_BOOL cyclic_p1) {
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* result;
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* colontmp_;
	result = NIM_NIL;
	colontmp_ = result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRefCyclic(src_p0, cyclic_p1);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initDateTime__pureZtimes_u1690)(tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* zt_p0, tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* zone_p1, tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* Result) {
	NI colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	NI colontmpD__4;
	NIM_BOOL colontmpD__5;
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* colontmpD__6;
	NI colontmpD__7;
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw adjTime_1;
	tyObject_Duration__M49aQghjNOIqBxxfIXLhG7w T1_;
	NI64 s_1;
	NI64 epochday_1;
	NI64 rem_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_68;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_69;
	NI64 hour_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_70;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_71;
	NI64 minute_1;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_72;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_73;
	NI64 second_1;
	tyTuple__9bDuq5lKllnHHKqT6vicMTA tmpTuple_1;
	NI d_1;
	tyEnum_Month__gE9cOK9cA9bmzUC4ynQJwuQIg m_1;
	NI y_1;
	tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw T2_;
	NI T3_;
NIM_BOOL* nimErr_;
	nimfr_("initDateTime", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ));
	(*Result).Sup.m_type = (&NTIv2__SbWCAn9czJMfLxIKVQMb1kQ_);
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NI)0;
	colontmpD__5 = (NIM_BOOL)0;
	colontmpD__6 = NIM_NIL;
	colontmpD__7 = (NI)0;
	nimln_(1170);	T1_ = initDuration__pureZtimes_u501(IL64(0), IL64(0), IL64(0), ((NI64) ((*zt_p0).utcOffset)), IL64(0), IL64(0), IL64(0), IL64(0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	adjTime_1 = ntSubTime((*zt_p0).time, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1171);	s_1 = adjTime_1.seconds;
	nimln_(1172);	epochday_1 = floorDiv__pureZtimes_u317(s_1, IL64(86400));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1173);	if (nimMulInt64(epochday_1, IL64(86400), &TM__6NbDwwj5FY059b1gz2AsAZQ_68)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64(s_1, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_68), &TM__6NbDwwj5FY059b1gz2AsAZQ_69)) { raiseOverflow(); goto BeforeRet_;
	};
	rem_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_69);
	nimln_(1174);	hour_1 = (NI64)((rem_1) / (IL64(3600)));
	nimln_(1175);	if (nimMulInt64(hour_1, IL64(3600), &TM__6NbDwwj5FY059b1gz2AsAZQ_70)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64(rem_1, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_70), &TM__6NbDwwj5FY059b1gz2AsAZQ_71)) { raiseOverflow(); goto BeforeRet_;
	};
	rem_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_71);
	nimln_(1176);	minute_1 = (NI64)((rem_1) / (IL64(60)));
	nimln_(1177);	if (nimMulInt64(minute_1, IL64(60), &TM__6NbDwwj5FY059b1gz2AsAZQ_72)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt64(rem_1, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_72), &TM__6NbDwwj5FY059b1gz2AsAZQ_73)) { raiseOverflow(); goto BeforeRet_;
	};
	rem_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_73);
	nimln_(1178);	second_1 = rem_1;
	nimln_(1180);	tmpTuple_1 = fromEpochDay__pureZtimes_u203(epochday_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	d_1 = tmpTuple_1.Field0;
	m_1 = tmpTuple_1.Field1;
	y_1 = tmpTuple_1.Field2;
	nimln_(1168);	nimln_(1182);	(*Result).Sup.m_type = (&NTIv2__SbWCAn9czJMfLxIKVQMb1kQ_);
	(*Result).year = y_1;
	(*Result).monthZero = ((NI) (m_1));
	(*Result).monthdayZero = d_1;
	nimln_(1186);	if ((hour_1) < ((NI)0) || (hour_1) > ((NI)23)){ raiseRangeErrorI(hour_1, ((NI)0), ((NI)23)); goto BeforeRet_;
	}
	colontmpD_ = ((NI) (hour_1));
	(*Result).hour = colontmpD_;
	nimln_(1187);	if ((minute_1) < ((NI)0) || (minute_1) > ((NI)59)){ raiseRangeErrorI(minute_1, ((NI)0), ((NI)59)); goto BeforeRet_;
	}
	colontmpD__2 = ((NI) (minute_1));
	(*Result).minute = colontmpD__2;
	nimln_(1188);	if ((second_1) < ((NI)0) || (second_1) > ((NI)60)){ raiseRangeErrorI(second_1, ((NI)0), ((NI)60)); goto BeforeRet_;
	}
	colontmpD__3 = ((NI) (second_1));
	(*Result).second = colontmpD__3;
	nimln_(1189);	colontmpD__4 = (*zt_p0).time.nanosecond;
	(*Result).nanosecond = colontmpD__4;
	nimln_(1190);	T2_ = (tyEnum_WeekDay__09avNMn3qyG7d3Y4frCak9cw)0;
	T2_ = getDayOfWeek__pureZtimes_u311(d_1, m_1, y_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).weekday = T2_;
	nimln_(1191);	T3_ = (NI)0;
	T3_ = getDayOfYear__pureZtimes_u266(d_1, m_1, y_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).yearday = T3_;
	nimln_(1192);	colontmpD__5 = (*zt_p0).isDst;
	(*Result).isDst = colontmpD__5;
	nimln_(1193);	nimln_(1118);	colontmpD__6 = eqdup___pureZtimes_u1557(zone_p1, NIM_TRUE);
	(*Result).timezone = colontmpD__6;
	nimln_(1194);	colontmpD__7 = (*zt_p0).utcOffset;
	(*Result).utcOffset = colontmpD__7;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, zonedTimeFromTime__pureZtimes_u1805)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* zone_p0, tyObject_Time__4WTh4uraGRwIK9abeHd66Xw time_p1, tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* Result) {
NIM_BOOL* nimErr_;
	nimfr_("zonedTimeFromTime", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ));
	nimln_(1238);	nimln_(1239);	(*zone_p0).zonedTimeFromTimeImpl.ClE_0? (*zone_p0).zonedTimeFromTimeImpl.ClP_0(time_p1, Result, (*zone_p0).zonedTimeFromTimeImpl.ClE_0):((TM__6NbDwwj5FY059b1gz2AsAZQ_103)((*zone_p0).zonedTimeFromTimeImpl.ClP_0))(time_p1, Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, inZone__pureZtimes_u1858)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw time_p0, tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* zone_p1, tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* Result) {
	tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("inZone", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ));
	(*Result).Sup.m_type = (&NTIv2__SbWCAn9czJMfLxIKVQMb1kQ_);
	nimln_(1268);	nimZeroMem((void*)(&T1_), sizeof(tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ));
	zonedTimeFromTime__pureZtimes_u1805(zone_p1, time_p0, (&T1_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	initDateTime__pureZtimes_u1690((&T1_), zone_p1, Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, fromUnix__pureZtimes_u1227)(NI64 unix_p0) {
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw result;
NIM_BOOL* nimErr_;
	nimfr_("fromUnix", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw));
	nimln_(926);	nimln_(930);	result = initTime__pureZtimes_u1200(unix_p0, ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZtimes_u1561)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag** dest_p0, tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* src_p1) {
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* colontmp_;
	colontmp_ = (*dest_p0);
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(colontmp_, ((TNimTypeV2*) ((&NTIv2__dfW7lUzCkQZeKePAkY3nag_))));
		if (!T3_) goto LA4_;
		eqdestroy___pureZtimes_u1570((&(*colontmp_)));
		nimRawDispose(colontmp_, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdup___pureZtimes_u1780)(tyProc__tcKV2iS3YOGzPD06HjxCSg src_p0, NIM_BOOL cyclic_p1, tyProc__tcKV2iS3YOGzPD06HjxCSg* Result) {
	void* colontmp_;
	nimZeroMem((void*)Result, sizeof(tyProc__tcKV2iS3YOGzPD06HjxCSg));
	colontmp_ = (*Result).ClE_0;
	(*Result).ClE_0 = src_p0.ClE_0;
	(*Result).ClP_0 = src_p0.ClP_0;
	{
		if (!src_p0.ClE_0) goto LA3_;
		nimIncRefCyclic(src_p0.ClE_0, cyclic_p1);
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag*, newTimezone__pureZtimes_u1761)(NimStringV2 name_p0, tyProc__tcKV2iS3YOGzPD06HjxCSg zonedTimeFromTimeImpl_p1, tyProc__tcKV2iS3YOGzPD06HjxCSg zonedTimeFromAdjTimeImpl_p2) {
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* result;
	NimStringV2 colontmpD_;
	tyProc__tcKV2iS3YOGzPD06HjxCSg colontmpD__2;
	tyProc__tcKV2iS3YOGzPD06HjxCSg colontmpD__3;
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* T1_;
	nimfr_("newTimezone", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyProc__tcKV2iS3YOGzPD06HjxCSg));
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyProc__tcKV2iS3YOGzPD06HjxCSg));
	nimln_(1219);	T1_ = NIM_NIL;
	T1_ = (tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag*) nimNewObjUninit(sizeof(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag), NIM_ALIGNOF(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag));
	nimln_(1220);	nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");	colontmpD_ = eqdup___system_u2664(name_p0);
	(*T1_).name = colontmpD_;
	nimlf_(1221, "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");	nimln_(1219);	eqdup___pureZtimes_u1780(zonedTimeFromTimeImpl_p1, NIM_TRUE, (&colontmpD__2));
	(*T1_).zonedTimeFromTimeImpl.ClE_0 = colontmpD__2.ClE_0;
	(*T1_).zonedTimeFromTimeImpl.ClP_0 = colontmpD__2.ClP_0;
	nimln_(1222);	nimln_(1219);	eqdup___pureZtimes_u1780(zonedTimeFromAdjTimeImpl_p2, NIM_TRUE, (&colontmpD__3));
	(*T1_).zonedTimeFromAdjTimeImpl.ClE_0 = colontmpD__3.ClE_0;
	(*T1_).zonedTimeFromAdjTimeImpl.ClP_0 = colontmpD__3.ClP_0;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw, eqdup___pureZtimes_u1213)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw src_p0) {
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw));
	result.seconds = src_p0.seconds;
	result.nanosecond = src_p0.nanosecond;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, utcTzInfo__pureZtimes_u2065)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw time_p0, tyObject_ZonedTime__aA28FJlusKBZPiNaISe9bPQ* Result) {
	tyObject_Time__4WTh4uraGRwIK9abeHd66Xw colontmpD_;
	nimfr_("utcTzInfo", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw));
	nimln_(1371);	(*Result).utcOffset = ((NI)0);
	(*Result).isDst = NIM_FALSE;
	nimln_(917);	colontmpD_ = eqdup___pureZtimes_u1213(time_p0);
	(*Result).time = colontmpD_;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u1550)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__dfW7lUzCkQZeKePAkY3nag_))));
		if (!T3_) goto LA4_;
		eqdestroy___pureZtimes_u1570((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZtimes_u1553)(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag** dest_p0, tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicStatic(colontmp_, ((TNimTypeV2*) ((&NTIv2__dfW7lUzCkQZeKePAkY3nag_))));
		if (!T7_) goto LA8_;
		eqdestroy___pureZtimes_u1570((&(*colontmp_)));
		nimRawDispose(colontmp_, ((NI)8));
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag*, utc__pureZtimes_u2070)(void) {
	tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* result;
NIM_BOOL* nimErr_;
	nimfr_("utc", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimln_(1381);	{
		tyProc__tcKV2iS3YOGzPD06HjxCSg T5_;
		tyProc__tcKV2iS3YOGzPD06HjxCSg T6_;
		tyObject_TimezonecolonObjectType___dfW7lUzCkQZeKePAkY3nag* T7_;
		if (!(utcInstance__pureZtimes_u2068 == 0)) goto LA3_;
		nimln_(1118);		nimln_(1382);		nimZeroMem((void*)(&T5_), sizeof(tyProc__tcKV2iS3YOGzPD06HjxCSg));
		T5_.ClP_0 = ((TM__6NbDwwj5FY059b1gz2AsAZQ_106) (utcTzInfo__pureZtimes_u2065)); T5_.ClE_0 = NIM_NIL;
		nimZeroMem((void*)(&T6_), sizeof(tyProc__tcKV2iS3YOGzPD06HjxCSg));
		T6_.ClP_0 = ((TM__6NbDwwj5FY059b1gz2AsAZQ_107) (utcTzInfo__pureZtimes_u2065)); T6_.ClE_0 = NIM_NIL;
		T7_ = NIM_NIL;
		T7_ = newTimezone__pureZtimes_u1761(TM__6NbDwwj5FY059b1gz2AsAZQ_105, T5_, T6_);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZtimes_u1550(T7_); goto BeforeRet_;}
		nimln_(1118);		eqsink___pureZtimes_u1561(&utcInstance__pureZtimes_u2068, T7_);
	}
LA3_: ;
	eqcopy___pureZtimes_u1553(&result, utcInstance__pureZtimes_u2068, NIM_FALSE);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isInitialized__pureZtimes_u1636)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* dt_p0) {
	NIM_BOOL result;
	nimfr_("isInitialized", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
	nimln_(1135);	nimln_(1138);	result = !(((*dt_p0).monthZero == ((NI)0)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ntEqTime)(tyObject_Time__4WTh4uraGRwIK9abeHd66Xw a_p0, tyObject_Time__4WTh4uraGRwIK9abeHd66Xw b_p1) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("==", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
	nimln_(1033);	nimln_(1034);	T1_ = (NIM_BOOL)0;
	nimln_(652);	T1_ = (a_p0.seconds == b_p1.seconds);
	if (!(T1_)) goto LA2_;
	T1_ = (a_p0.nanosecond == b_p1.nanosecond);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___pureZtimes_u2163)(tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* a_p0, tyObject_DateTime__SbWCAn9czJMfLxIKVQMb1kQ* b_p1) {
	NIM_BOOL result;
	NIM_BOOL colontmpD_;
	NIM_BOOL colontmpD__2;
	NIM_BOOL colontmpD__3;
NIM_BOOL* nimErr_;
	nimfr_("==", "K:\\Progz\\nim-2.2.6\\lib\\pure\\times.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	colontmpD_ = (NIM_BOOL)0;
	colontmpD__2 = (NIM_BOOL)0;
	colontmpD__3 = (NIM_BOOL)0;
	nimln_(1491);	nimln_(1492);	{
		NIM_BOOL T3_;
		NIM_BOOL T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isInitialized__pureZtimes_u1636(a_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		T6_ = (NIM_BOOL)0;
		T6_ = isInitialized__pureZtimes_u1636(b_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD_ = !(T6_);
		result = colontmpD_;
	}
	goto LA1_;
LA4_: ;
	{
		NIM_BOOL T8_;
		nimln_(1493);		T8_ = (NIM_BOOL)0;
		T8_ = isInitialized__pureZtimes_u1636(b_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T8_)) goto LA9_;
		colontmpD__2 = NIM_FALSE;
		result = colontmpD__2;
	}
	goto LA1_;
LA9_: ;
	{
		tyObject_Time__4WTh4uraGRwIK9abeHd66Xw T12_;
		tyObject_Time__4WTh4uraGRwIK9abeHd66Xw T13_;
		nimln_(1494);		T12_ = toTime__pureZtimes_u1660(a_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T13_ = toTime__pureZtimes_u1660(b_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__3 = ntEqTime(T12_, T13_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__3;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
