/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\owlkettleEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@punicode.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\owl_custom\@punicode.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, lteqpercent___system_u1082)(NI32 x_p0, NI32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2410)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3 = {0, (NimStrPayload*)&TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___pureZunicode_u1106)(NI32 a_p0, NI32 b_p1) {
	NIM_BOOL result;
	nimfr_("==", "K:\\Progz\\nim-2.2.6\\lib\\pure\\unicode.nim");
{	nimlf_(462, "K:\\Progz\\nim-2.2.6\\lib\\pure\\unicode.nim");	nimln_(460);	nimln_(462);	result = (((NI) (a_p0)) == ((NI) (b_p1)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, lteqpercent___system_u1082)(NI32 x_p0, NI32 y_p1) {
	NIM_BOOL result;
	nimfr_("<=%", "K:\\Progz\\nim-2.2.6\\lib\\system\\comparisons.nim");
	result = ((NU32)(((NU32) (x_p0))) <= (NU32)(((NU32) (y_p1))));
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2410(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nuctoUTF8)(NI32 c_p0) {
	NimStringV2 result;
	NI32 iX60gensym21__1;
	nimfr_("toUTF8", "K:\\Progz\\nim-2.2.6\\lib\\pure\\unicode.nim");
{	nimln_(276);	result = TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3;
	nimln_(221);	iX60gensym21__1 = c_p0;
	nimln_(277);	{
		NIM_BOOL T3_;
		nimln_(222);		T3_ = (NIM_BOOL)0;
		T3_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)127));
		if (!T3_) goto LA4_;
		nimln_(223);		setLengthStrV2((&result), ((NI)1));
		nimln_(224);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((iX60gensym21__1) < ((NI)0) || (iX60gensym21__1) > ((NI)255)){ raiseRangeErrorI(iX60gensym21__1, ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) (iX60gensym21__1))));
	}
	goto LA1_;
LA4_: ;
	{
		NIM_BOOL T7_;
		nimln_(226);		T7_ = (NIM_BOOL)0;
		T7_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)2047));
		if (!T7_) goto LA8_;
		nimln_(227);		setLengthStrV2((&result), ((NI)2));
		nimln_(228);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) | ((NI32)192))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) | ((NI32)192))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) | ((NI32)192)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) | ((NI32)192))))));
		nimln_(229);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA8_: ;
	{
		NIM_BOOL T11_;
		nimln_(231);		T11_ = (NIM_BOOL)0;
		T11_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)65535));
		if (!T11_) goto LA12_;
		nimln_(232);		setLengthStrV2((&result), ((NI)3));
		nimln_(233);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) | ((NI32)224))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) | ((NI32)224))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) | ((NI32)224)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) | ((NI32)224))))));
		nimln_(234);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(235);		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA12_: ;
	{
		NIM_BOOL T15_;
		nimln_(237);		T15_ = (NIM_BOOL)0;
		T15_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)2097151));
		if (!T15_) goto LA16_;
		nimln_(238);		setLengthStrV2((&result), ((NI)4));
		nimln_(239);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) | ((NI32)240))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) | ((NI32)240))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) | ((NI32)240)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) | ((NI32)240))))));
		nimln_(240);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(241);		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(242);		if (((NI)3) < 0 || ((NI)3) >= result.len){ raiseIndexError2(((NI)3),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA16_: ;
	{
		NIM_BOOL T19_;
		nimln_(244);		T19_ = (NIM_BOOL)0;
		T19_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)67108863));
		if (!T19_) goto LA20_;
		nimln_(245);		setLengthStrV2((&result), ((NI)5));
		nimln_(246);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) | ((NI32)248))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) | ((NI32)248))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) | ((NI32)248)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) | ((NI32)248))))));
		nimln_(247);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(248);		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(249);		if (((NI)3) < 0 || ((NI)3) >= result.len){ raiseIndexError2(((NI)3),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(250);		if (((NI)4) < 0 || ((NI)4) >= result.len){ raiseIndexError2(((NI)4),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA20_: ;
	{
		NIM_BOOL T23_;
		nimln_(252);		T23_ = (NIM_BOOL)0;
		T23_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)2147483647));
		if (!T23_) goto LA24_;
		nimln_(253);		setLengthStrV2((&result), ((NI)6));
		nimln_(254);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30))) | ((NI32)252))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30))) | ((NI32)252))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30))) | ((NI32)252)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30))) | ((NI32)252))))));
		nimln_(255);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(256);		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(257);		if (((NI)3) < 0 || ((NI)3) >= result.len){ raiseIndexError2(((NI)3),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(258);		if (((NI)4) < 0 || ((NI)4) >= result.len){ raiseIndexError2(((NI)4),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(259);		if (((NI)5) < 0 || ((NI)5) >= result.len){ raiseIndexError2(((NI)5),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)5)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA24_: ;
	{
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
