/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -DNO_SSL -IC:\Users\n1ght\.nimble\pkgs2\webui-2.5.0.2-0eb2646495c3c942e0ea7aefac42b63c0d8f1741\webui\webui\include -DNDEBUG -DNO_CACHING -DNO_CGI -DUSE_WEBSOCKET   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\webuiEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@mapp.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@mapp.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_WebUiEnhanceConfig__hZ39aMPC9c4p3JdRPbx68jqQ tyObject_WebUiEnhanceConfig__hZ39aMPC9c4p3JdRPbx68jqQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_WebUiConfig__Z0PW9b222x58xXm4A2Yw8pg tyObject_WebUiConfig__Z0PW9b222x58xXm4A2Yw8pg;
typedef struct tyObject_EventcolonObjectType___DQluA10r4q3m9aVvcwYgkXQ tyObject_EventcolonObjectType___DQluA10r4q3m9aVvcwYgkXQ;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_WebUiEnhanceConfig__hZ39aMPC9c4p3JdRPbx68jqQ {
	NIM_BOOL disableTitlebar;
	NIM_BOOL disablePasswordPopup;
	NIM_BOOL disableTranslationPopup;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ favoriteBrowsers;
	NIM_BOOL forceWebView;
	NI connectTimeoutSeconds;
	NIM_BOOL bindWindowButtons;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tyObject_WebUiConfig__Z0PW9b222x58xXm4A2Yw8pg {
	NimStringV2 appName;
	NimStringV2 webRoot;
	NIM_BOOL forceWebView;
	NIM_BOOL frameless;
	NIM_BOOL transparent;
	NIM_BOOL bindWindowButtons;
	NIM_BOOL disableBrowserPrompts;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ browserOrderNames;
	NI connectTimeoutSeconds;
};
typedef struct {
N_NIMCALL_PTR(NimStringV2, ClP_0) (NimStringV2 key_p0, void* ClE_0);
void* ClE_0;
} tyProc__oFHfEKFsiYTMAy9a42cSiKw;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_EventcolonObjectType___DQluA10r4q3m9aVvcwYgkXQ* e_p0, void* ClE_0);
void* ClE_0;
} tyProc__tfQ8RT3K2fb0SgsOUEAYeg;
typedef tyProc__tfQ8RT3K2fb0SgsOUEAYeg tyArray__pnKLqbQArGlZT9b01NGPRzw[256];
typedef tyArray__pnKLqbQArGlZT9b01NGPRzw tyArray__fgKNXGlplbkwCYb3muWTuA[256];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, enhance__OOZOOZOOZsrcZwebui69nhancedZenhance_u66)(NimStringV2 pathOfConfig_p0, tyObject_WebUiEnhanceConfig__hZ39aMPC9c4p3JdRPbx68jqQ* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, resolveConfigPath__app_u7)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringV2 path_p0, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZosdirs_u85)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* dest_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, runWebUi__OOZOOZOOZsrcZwebui69nhancedZsharedZwebui95shell_u436)(tyObject_WebUiConfig__Z0PW9b222x58xXm4A2Yw8pg* c_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, resolveWebRoot__app_u5)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZsrcZwebui69nhancedZenhance_u74)(tyObject_WebUiEnhanceConfig__hZ39aMPC9c4p3JdRPbx68jqQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunicode_u3808)(tyProc__oFHfEKFsiYTMAy9a42cSiKw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZwebui_u1432)(tyArray__pnKLqbQArGlZT9b01NGPRzw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsexitprocsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpwebuiEnhancedatssharedatswebui_shelldotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[78+1];
} TM__z5lfa2fJ29cO8OlQX4iMMsw_2 = { 78 | NIM_STRLIT_FLAG, "f:\\CodingMain\\proto-ViableNimUIs\\examples\\webuiEnhanced\\customTitlebar\\app.nim" };
static const NimStringV2 TM__z5lfa2fJ29cO8OlQX4iMMsw_3 = {78, (NimStrPayload*)&TM__z5lfa2fJ29cO8OlQX4iMMsw_2};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__z5lfa2fJ29cO8OlQX4iMMsw_4 = { 9 | NIM_STRLIT_FLAG, "config.md" };
static const NimStringV2 TM__z5lfa2fJ29cO8OlQX4iMMsw_5 = {9, (NimStrPayload*)&TM__z5lfa2fJ29cO8OlQX4iMMsw_4};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__z5lfa2fJ29cO8OlQX4iMMsw_6 = { 44 | NIM_STRLIT_FLAG, "Hestia-NimUISetups - WebUI (Custom Titlebar)" };
static const NimStringV2 TM__z5lfa2fJ29cO8OlQX4iMMsw_7 = {44, (NimStrPayload*)&TM__z5lfa2fJ29cO8OlQX4iMMsw_6};
static const NimStringV2 TM__z5lfa2fJ29cO8OlQX4iMMsw_8 = {78, (NimStrPayload*)&TM__z5lfa2fJ29cO8OlQX4iMMsw_2};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__z5lfa2fJ29cO8OlQX4iMMsw_9 = { 3 | NIM_STRLIT_FLAG, "web" };
static const NimStringV2 TM__z5lfa2fJ29cO8OlQX4iMMsw_10 = {3, (NimStrPayload*)&TM__z5lfa2fJ29cO8OlQX4iMMsw_9};
N_LIB_PRIVATE tyObject_WebUiEnhanceConfig__hZ39aMPC9c4p3JdRPbx68jqQ cfg__app_u9;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
extern tyProc__oFHfEKFsiYTMAy9a42cSiKw currHandler__pkgZwebui_u15;
extern tyArray__fgKNXGlplbkwCYb3muWTuA cbs__pkgZwebui_u12;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, resolveConfigPath__app_u7)(void) {
	NimStringV2 result;
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("resolveConfigPath", "f:\\CodingMain\\proto-ViableNimUIs\\examples\\webuiEnhanced\\customTitlebar\\app.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	nimlf_(19, "f:\\CodingMain\\proto-ViableNimUIs\\examples\\webuiEnhanced\\customTitlebar\\app.nim");	nossplitFile(TM__z5lfa2fJ29cO8OlQX4iMMsw_3, (&colontmpD_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = nosjoinPath(colontmpD_.Field0, TM__z5lfa2fJ29cO8OlQX4iMMsw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(76, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\osdirs.nim");	eqdestroy___stdZprivateZosdirs_u85((&colontmpD_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, resolveWebRoot__app_u5)(void) {
	NimStringV2 result;
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("resolveWebRoot", "f:\\CodingMain\\proto-ViableNimUIs\\examples\\webuiEnhanced\\customTitlebar\\app.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	nimlf_(15, "f:\\CodingMain\\proto-ViableNimUIs\\examples\\webuiEnhanced\\customTitlebar\\app.nim");	nossplitFile(TM__z5lfa2fJ29cO8OlQX4iMMsw_8, (&colontmpD_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = nosjoinPath(colontmpD_.Field0, TM__z5lfa2fJ29cO8OlQX4iMMsw_10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(76, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\osdirs.nim");	eqdestroy___stdZprivateZosdirs_u85((&colontmpD_));
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpstdatsexitprocsdotnim_Init000();
	atpstdatssynciodotnim_Init000();
	atpwinleandotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpstdatssynciodotnim_DatInit000();
	atpsystemdotnim_Init000();
	atpwinleandotnim_DatInit000();
	atpwebuiEnhancedatssharedatswebui_shelldotnim_DatInit000();
	(*inner)();
#else
	atpstdatssynciodotnim_DatInit000();
	atpsystemdotnim_Init000();
	atpwinleandotnim_DatInit000();
	atpwebuiEnhancedatssharedatswebui_shelldotnim_DatInit000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyObject_WebUiConfig__Z0PW9b222x58xXm4A2Yw8pg T2_;
	NIM_BOOL T3_;
	NIM_BOOL T5_;
NIM_BOOL* nimErr_;
	nimfr_("app", "f:\\CodingMain\\proto-ViableNimUIs\\examples\\webuiEnhanced\\customTitlebar\\app.nim");
nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimlf_(22, "f:\\CodingMain\\proto-ViableNimUIs\\examples\\webuiEnhanced\\customTitlebar\\app.nim");	colontmpD_ = resolveConfigPath__app_u7();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	enhance__OOZOOZOOZsrcZwebui69nhancedZenhance_u66(colontmpD_, (&cfg__app_u9));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(23);	T2_.appName = TM__z5lfa2fJ29cO8OlQX4iMMsw_7;
	nimln_(25);	colontmpD__2 = resolveWebRoot__app_u5();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_.webRoot = colontmpD__2;
	T2_.forceWebView = cfg__app_u9.forceWebView;
	T2_.frameless = cfg__app_u9.disableTitlebar;
	T2_.transparent = cfg__app_u9.disableTitlebar;
	nimln_(29);	T3_ = (NIM_BOOL)0;
	T3_ = cfg__app_u9.bindWindowButtons;
	if (!(T3_)) goto LA4_;
	T3_ = cfg__app_u9.disableTitlebar;
LA4_: ;
	T2_.bindWindowButtons = T3_;
	nimln_(30);	T5_ = (NIM_BOOL)0;
	T5_ = cfg__app_u9.disablePasswordPopup;
	if (T5_) goto LA6_;
	T5_ = cfg__app_u9.disableTranslationPopup;
LA6_: ;
	T2_.disableBrowserPrompts = T5_;
	T2_.browserOrderNames = cfg__app_u9.favoriteBrowsers;
	T2_.connectTimeoutSeconds = cfg__app_u9.connectTimeoutSeconds;
	nimln_(23);	runWebUi__OOZOOZOOZsrcZwebui69nhancedZsharedZwebui95shell_u436((&T2_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(54, "f:\\CodingMain\\proto-ViableNimUIs\\src\\webuiEnhanced\\enhance.nim");	eqdestroy___OOZOOZOOZsrcZwebui69nhancedZenhance_u74((&cfg__app_u9));
	nimlf_(729, "K:\\Progz\\nim-2.2.6\\lib\\pure\\unicode.nim");	eqdestroy___pureZunicode_u3808((&currHandler__pkgZwebui_u15));
	nimlf_(35, "C:\\Users\\n1ght\\.nimble\\pkgs2\\webui-2.5.0.2-0eb2646495c3c942e0ea7aefac42b63c0d8f1741\\webui.nim");	eqdestroy___pkgZwebui_u1432(cbs__pkgZwebui_u12);
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

