/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -DNO_SSL -IC:\Users\n1ght\.nimble\pkgs2\webui-2.5.0.2-0eb2646495c3c942e0ea7aefac42b63c0d8f1741\webui\webui\include -DNDEBUG -DNO_CACHING -DNO_CGI -DUSE_WEBSOCKET   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\webuiEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pdynlib.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pdynlib.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1) {
	void* result;
	HMODULE T1_;
	nimfr_("loadLib", "K:\\Progz\\nim-2.2.6\\lib\\pure\\dynlib.nim");
	nimlf_(187, "K:\\Progz\\nim-2.2.6\\lib\\pure\\dynlib.nim");	T1_ = (HMODULE)0;
	T1_ = LoadLibraryA(nimToCStringConv(path_p0));
	result = ((void*) (T1_));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1) {
	void* result;
	FARPROC T1_;
	nimfr_("symAddr", "K:\\Progz\\nim-2.2.6\\lib\\pure\\dynlib.nim");
	nimln_(193);	T1_ = (FARPROC)0;
	T1_ = GetProcAddress(((HMODULE) (lib_p0)), name_p1);
	result = ((void*) (T1_));
	popFrame();
	return result;
}
