/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -DNO_SSL -IC:\Users\n1ght\.nimble\pkgs2\webui-2.5.0.2-0eb2646495c3c942e0ea7aefac42b63c0d8f1741\webui\webui\include -DNDEBUG -DNO_CACHING -DNO_CGI -DUSE_WEBSOCKET   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\webuiEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pstd@senvvars.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pstd@senvvars.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q {
	NI bytes;
	NI16* data;
};
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
N_LIB_PRIVATE N_NIMCALL(NI16*, getEnvImpl__stdZenvvars_u11)(NCSTRING env_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q x_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q, newWideCString__stdZwidestrs_u322)(NCSTRING s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q a_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2661)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZwidestrs_u394)(NI16* s_p0);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q x_p0) {
	NI16* result;
	nimfr_("toWideCString", "K:\\Progz\\nim-2.2.6\\lib\\std\\widestrs.nim");
	nimlf_(63, "K:\\Progz\\nim-2.2.6\\lib\\std\\widestrs.nim");	result = x_p0.data;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI16*, getEnvImpl__stdZenvvars_u11)(NCSTRING env_p0) {
	NI16* result;
	tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q colontmpD_;
	NI16* r_1;
	wchar_t* T1_;
NIM_BOOL* nimErr_;
	nimfr_("getEnvImpl", "K:\\Progz\\nim-2.2.6\\lib\\std\\envvars.nim");
{nimErr_ = nimErrorFlag();
	result = (NI16*)0;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_WideCStringObj__MSxliLo5p9bZRO9by43qj48Q));
	nimlf_(74, "K:\\Progz\\nim-2.2.6\\lib\\std\\envvars.nim");	colontmpD_ = newWideCString__stdZwidestrs_u322(env_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	r_1 = toWideCString__stdZwidestrs_u49(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(75);	T1_ = (wchar_t*)0;
	T1_ = _wgetenv(((wchar_t*) (r_1)));
	result = ((NI16*) (T1_));
	nimlf_(30, "K:\\Progz\\nim-2.2.6\\lib\\std\\widestrs.nim");	eqdestroy___stdZwidestrs_u7(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u34)(NimStringV2 key_p0, NimStringV2 default_p1) {
	NimStringV2 result;
	NI16* env_1;
NIM_BOOL* nimErr_;
	nimfr_("getEnv", "K:\\Progz\\nim-2.2.6\\lib\\std\\envvars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(99, "K:\\Progz\\nim-2.2.6\\lib\\std\\envvars.nim");	env_1 = getEnvImpl__stdZenvvars_u11(nimToCStringConv(key_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(100);	{
		if (!(env_1 == ((NI16*) NIM_NIL))) goto LA3_;
		nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		eqcopy___system_u2661((&result), default_p1);
	}
	goto LA1_;
LA3_: ;
	{
		nimlf_(103, "K:\\Progz\\nim-2.2.6\\lib\\std\\envvars.nim");		result = dollar___stdZwidestrs_u394(env_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
