/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -DNO_SSL -IC:\Users\n1ght\.nimble\pkgs2\webui-2.5.0.2-0eb2646495c3c942e0ea7aefac42b63c0d8f1741\webui\webui\include -DNDEBUG -DNO_CACHING -DNO_CGI -DUSE_WEBSOCKET   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\webuiEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pstrutils.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pstrutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw;
typedef struct tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ tySequence__Eio1jF59abEpv9bLmutTDQvQ;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content;
typedef struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ {
  NI len; tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__Eio1jF59abEpv9bLmutTDQvQ trace;
	Exception* up;
};
struct tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA {
	Exception Sup;
};
struct tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw {
	tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA Sup;
};
struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content { NI cap; tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw data[SEQ_DECL_SIZE]; };
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2410)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8911)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NI, parseBiggestInt__pureZparseutils_u915)(NimStringV2 s_p0, NI64* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NI, parseFloat__pureZparseutils_u945)(NimStringV2 s_p0, NF* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0);
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2654)(NimStringV2 formatstr_p0);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2641)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NI, parseInt__pureZparseutils_u920)(NimStringV2 s_p0, NI* number_p1, NI start_p2);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_19 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_20 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_19};
extern TNimTypeV2 NTIv2__w75dCcMqUymzJ8IcKO0oIw_;
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_22 = { 17 | NIM_STRLIT_FLAG, "invalid integer: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_23 = {17, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_22};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_24 = { 15 | NIM_STRLIT_FLAG, "invalid float: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_25 = {15, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_24};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_29 = { 23 | NIM_STRLIT_FLAG, "invalid format string: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_30 = {23, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_29};
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_63 = {17, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_22};
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2410(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	nimfr_("toLowerAscii", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
	nimlf_(218, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");	{
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		nimln_(219);		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(221);		result = c_p0;
	}
LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toLowerAscii", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(224);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	{
		NI iX60gensym7__1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
		NI res_1;
		iX60gensym7__1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		nimlf_(225, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2);
		nimlf_(96, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NIM_CHAR T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(239, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");				iX60gensym7__1 = ((NI) (res_1));
				nimln_(226);				if (iX60gensym7__1 < 0 || iX60gensym7__1 >= result.len){ raiseIndexError2(iX60gensym7__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (iX60gensym7__1 < 0 || iX60gensym7__1 >= s_p0.len){ raiseIndexError2(iX60gensym7__1,s_p0.len-1); goto BeforeRet_;
				}
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToLowerAsciiChar(s_p0.p->data[iX60gensym7__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym7__1] = T4_;
				nimlf_(102, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NIM_CHAR by_p2) {
	NimStringV2 result;
	NI i_1;
	nimfr_("replace", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(2254, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	nimln_(2255);	i_1 = ((NI)0);
	{
		nimln_(2256);		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
			if (!(i_1 < s_p0.len)) goto LA2;
			nimln_(2257);			{
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				if (!((NU8)(s_p0.p->data[i_1]) == (NU8)(sub_p1))) goto LA5_;
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = by_p2;
			}
			goto LA3_;
LA5_: ;
			{
				nimln_(2258);				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				result.p->data[i_1] = s_p0.p->data[i_1];
			}
LA3_: ;
			nimln_(2259);			if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	nimfr_("toUpperAscii", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
	nimln_(255);	{
		if (!(((NU8)(c_p0)) >= ((NU8)(97)) && ((NU8)(c_p0)) <= ((NU8)(122)))) goto LA3_;
		nimln_(256);		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(258);		result = c_p0;
	}
LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToUpperAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toUpperAscii", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(224);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	{
		NI iX60gensym11__1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
		NI res_1;
		iX60gensym11__1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		nimlf_(225, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
		nimlf_(96, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NIM_CHAR T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(271, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");				iX60gensym11__1 = ((NI) (res_1));
				nimln_(226);				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= result.len){ raiseIndexError2(iX60gensym11__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= s_p0.len){ raiseIndexError2(iX60gensym11__1,s_p0.len-1); goto BeforeRet_;
				}
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToUpperAsciiChar(s_p0.p->data[iX60gensym11__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym11__1] = T4_;
				nimlf_(102, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3) {
	NimStringV2 result;
	NI first_1;
	NI last_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
	nimfr_("strip", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(2996, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");	first_1 = ((NI)0);
	nimln_(2997);	if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)) { raiseOverflow(); goto BeforeRet_;
	};
	last_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7);
	nimln_(2998);	{
		if (!leading_p1) goto LA3_;
		{
			nimln_(2999);			while (1) {
				NIM_BOOL T7_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_8;
				T7_ = (NIM_BOOL)0;
				T7_ = (first_1 <= last_1);
				if (!(T7_)) goto LA8_;
				if (first_1 < 0 || first_1 >= s_p0.len){ raiseIndexError2(first_1,s_p0.len-1); goto BeforeRet_;
				}
				T7_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[first_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[first_1]))))&7U)))!=0);
LA8_: ;
				if (!T7_) goto LA6;
				if (nimAddInt(first_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)) { raiseOverflow(); goto BeforeRet_;
				};
				first_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8);
			} LA6: ;
		}
	}
LA3_: ;
	nimln_(3000);	{
		if (!trailing_p2) goto LA11_;
		{
			nimln_(3001);			while (1) {
				NIM_BOOL T15_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
				T15_ = (NIM_BOOL)0;
				T15_ = (first_1 <= last_1);
				if (!(T15_)) goto LA16_;
				if (last_1 < 0 || last_1 >= s_p0.len){ raiseIndexError2(last_1,s_p0.len-1); goto BeforeRet_;
				}
				T15_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[last_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[last_1]))))&7U)))!=0);
LA16_: ;
				if (!T15_) goto LA14;
				if (nimSubInt(last_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); goto BeforeRet_;
				};
				last_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9);
			} LA14: ;
		}
	}
LA11_: ;
	nimln_(3002);	result = substr__system_u8911(s_p0, first_1, last_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimlf_(364, "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI length_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
	nimfr_("find", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(1972, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");	result = ((NI)-1);
	nimln_(1973);	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1984);	if (nimSubInt(last_2, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10), ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); goto BeforeRet_;
	};
	length_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11);
	nimln_(1985);	{
		void* found_1;
		if (!(((NI)0) < length_1)) goto LA8_;
		nimln_(1986);		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		found_1 = memchr(((void*) ((&s_p0.p->data[start_p2]))), ((int) (((NU8)(sub_p1)))), ((size_t) (length_1)));
		nimln_(1987);		{
			if (!!((found_1 == 0))) goto LA12_;
			nimln_(1988);			nimln_(1960);			nimln_(1988);			result = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
		}
LA12_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1) {
	NIM_BOOL result;
	NI prefixLenX60gensym144__1;
	NI sLenX60gensym144__1;
	NI iX60gensym144__1;
	nimfr_("startsWith", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{	nimln_(1647);	result = NIM_FALSE;
	nimlf_(56, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\strimpl.nim");	prefixLenX60gensym144__1 = prefix_p1.len;
	nimln_(57);	sLenX60gensym144__1 = s_p0.len;
	nimln_(58);	iX60gensym144__1 = ((NI)0);
	{
		nimlf_(1648, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
			nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\strimpl.nim");			{
				if (!(prefixLenX60gensym144__1 <= iX60gensym144__1)) goto LA5_;
				nimlf_(1634, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");				nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\strimpl.nim");				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA5_: ;
			nimln_(61);			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = (sLenX60gensym144__1 <= iX60gensym144__1);
				if (T9_) goto LA10_;
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= s_p0.len){ raiseIndexError2(iX60gensym144__1,s_p0.len-1); goto BeforeRet_;
				}
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= prefix_p1.len){ raiseIndexError2(iX60gensym144__1,prefix_p1.len-1); goto BeforeRet_;
				}
				T9_ = !(((NU8)(s_p0.p->data[iX60gensym144__1]) == (NU8)(prefix_p1.p->data[iX60gensym144__1])));
LA10_: ;
				if (!T9_) goto LA11_;
				nimlf_(1634, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");				nimlf_(61, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\strimpl.nim");				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA11_: ;
			nimln_(62);			if (nimAddInt(iX60gensym144__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym144__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_17;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_17);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1) {
	NimStringV2 result;
	nimfr_("join", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(1871, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");	{
		NI L_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_13;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
		if (!(((NI)0) < a_p0Len_0)) goto LA3_;
		nimln_(1872);		if (nimSubInt(a_p0Len_0, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt(sep_p1.len, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); goto BeforeRet_;
		};
		L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14);
		{
			NI i_1;
			NI colontmp_;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");			nimlf_(1873, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");			colontmp_ = (a_p0Len_0-1);
			nimlf_(96, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
					if (!(res_1 <= colontmp_)) goto LA7;
					nimlf_(1873, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");					i_1 = ((NI) (res_1));
					if (i_1 < 0 || i_1 >= a_p0Len_0){ raiseIndexError2(i_1,a_p0Len_0-1); goto BeforeRet_;
					}
					if (nimAddInt(L_1, a_p0[i_1].len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); goto BeforeRet_;
					};
					L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15);
					nimlf_(102, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16);
				} LA7: ;
			}
		}
		nimlf_(1874, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");		if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		result = rawNewString((L_1));
		nimln_(1875);		if (((NI)0) < 0 || ((NI)0) >= a_p0Len_0){ raiseIndexError2(((NI)0),a_p0Len_0-1); goto BeforeRet_;
		}
		prepareAdd((&result), a_p0[((NI)0)].len + 0);
appendString((&result), a_p0[((NI)0)]);
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(81, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");			nimlf_(1876, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");			colontmp__2 = (a_p0Len_0-1);
			nimlf_(96, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");			res_2 = ((NI)1);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_18;
					if (!(res_2 <= colontmp__2)) goto LA10;
					nimlf_(1876, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");					i_2 = ((NI) (res_2));
					nimln_(1877);					prepareAdd((&result), sep_p1.len + 0);
appendString((&result), sep_p1);
					nimln_(1878);					if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&result), a_p0[i_2].len + 0);
appendString((&result), a_p0[i_2]);
					nimlf_(102, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");					if (nimAddInt(res_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_18)) { raiseOverflow(); goto BeforeRet_;
					};
					res_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_18);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		nimlf_(1880, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");		result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_20;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	nimfr_("find", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(2004);	result = ((NI)-1);
	nimln_(2005);	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		nimlf_(2006, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");		colontmp_ = start_p2;
		nimlf_(96, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		res_1 = colontmp_;
		{
			nimln_(97);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_21;
				if (!(res_1 <= last_2)) goto LA8;
				nimlf_(2006, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");				i_1 = ((NI) (res_1));
				nimln_(2007);				{
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!((chars_p1[(NU)((((NU8)(s_p0.p->data[i_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[i_1]))))&7U)))!=0)) goto LA11_;
					nimln_(2008);					nimln_(1992);					nimln_(2008);					result = i_1;
					goto BeforeRet_;
				}
LA11_: ;
				nimlf_(102, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1897)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("contains", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(2197, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");	nimln_(2192);	nimln_(2197);	T1_ = (NI)0;
	T1_ = nsuFindCharSet(s_p0, chars_p1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringV2 s_p0) {
	NI64 result;
	NI L_1;
NIM_BOOL* nimErr_;
	nimfr_("parseBiggestInt", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(1167);	result = IL64(0);
	nimln_(1168);	L_1 = parseBiggestInt__pureZparseutils_u915(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1169);	{
		NIM_BOOL T3_;
		tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw*) nimNewObj(sizeof(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw), NIM_ALIGNOF(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__w75dCcMqUymzJ8IcKO0oIw_);
		(*T7_).Sup.Sup.name = "ValueError";
		nimln_(1170);		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 17);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_23);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseBiggestInt", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim", 1170);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringV2 s_p0) {
	NF result;
	NI L_1;
NIM_BOOL* nimErr_;
	nimfr_("parseFloat", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(1199);	result = 0.0;
	nimln_(1200);	L_1 = parseFloat__pureZparseutils_u945(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1201);	{
		NIM_BOOL T3_;
		tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw*) nimNewObj(sizeof(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw), NIM_ALIGNOF(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__w75dCcMqUymzJ8IcKO0oIw_);
		(*T7_).Sup.Sup.name = "ValueError";
		nimln_(1202);		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 15);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_25);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseFloat", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim", 1202);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2654)(NimStringV2 formatstr_p0) {
	tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw* T1_;
	NimStringV2 T2_;
	nimfr_("invalidFormatString", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw*) nimNewObj(sizeof(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw), NIM_ALIGNOF(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__w75dCcMqUymzJ8IcKO0oIw_);
	(*T1_).Sup.Sup.name = "ValueError";
	nimln_(2831);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(formatstr_p0.len + 23);
appendString((&T2_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_30);
appendString((&T2_), formatstr_p0);
	(*T1_).Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "ValueError", "invalidFormatString", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim", 2831);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_33;
{	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
	}BeforeRet_: ;
}
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	nimfr_("toLowerAscii", "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\strimpl.nim");
{	result = (NIM_CHAR)0;
	nimlf_(2, "K:\\Progz\\nim-2.2.6\\lib\\std\\private\\strimpl.nim");	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_51;
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		nimln_(3);		if (nimAddInt(((NU8)(c_p0)), ((NI)32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result = ((NIM_CHAR) (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51))));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(5);		result = c_p0;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NI result;
	NI aLenX60gensym24__1;
	NI bLenX60gensym24__1;
	NI iX60gensym24__1;
	NI jX60gensym24__1;
NIM_BOOL* nimErr_;
	nimfr_("cmpIgnoreStyle", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	aLenX60gensym24__1 = a_p0.len;
	bLenX60gensym24__1 = b_p1.len;
	iX60gensym24__1 = ((NI)0);
	jX60gensym24__1 = ((NI)0);
	{
		while (1) {
			NIM_CHAR colontmpD_;
			NIM_CHAR colontmpD__2;
			NIM_CHAR colontmpD__3;
			NIM_CHAR colontmpD__4;
			NIM_CHAR aaX60gensym24__1;
			NIM_CHAR bbX60gensym24__1;
			colontmpD_ = (NIM_CHAR)0;
			colontmpD__2 = (NIM_CHAR)0;
			colontmpD__3 = (NIM_CHAR)0;
			colontmpD__4 = (NIM_CHAR)0;
			{
				while (1) {
					NIM_BOOL T5_;
					T5_ = (NIM_BOOL)0;
					T5_ = (iX60gensym24__1 < aLenX60gensym24__1);
					if (!(T5_)) goto LA6_;
					T5_ = ((NU8)(a_p0.p->data[iX60gensym24__1]) == (NU8)(95));
LA6_: ;
					if (!T5_) goto LA4;
					iX60gensym24__1 += ((NI)1);
				} LA4: ;
			}
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = (jX60gensym24__1 < bLenX60gensym24__1);
					if (!(T9_)) goto LA10_;
					T9_ = ((NU8)(b_p1.p->data[jX60gensym24__1]) == (NU8)(95));
LA10_: ;
					if (!T9_) goto LA8;
					jX60gensym24__1 += ((NI)1);
				} LA8: ;
			}
			{
				if (!(iX60gensym24__1 < aLenX60gensym24__1)) goto LA13_;
				colontmpD_ = toLowerAscii__stdZprivateZstrimpl_u1(a_p0.p->data[iX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				aaX60gensym24__1 = colontmpD_;
			}
			goto LA11_;
LA13_: ;
			{
				colontmpD__2 = 0;
				aaX60gensym24__1 = colontmpD__2;
			}
LA11_: ;
			{
				if (!(jX60gensym24__1 < bLenX60gensym24__1)) goto LA18_;
				colontmpD__3 = toLowerAscii__stdZprivateZstrimpl_u1(b_p1.p->data[jX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				bbX60gensym24__1 = colontmpD__3;
			}
			goto LA16_;
LA18_: ;
			{
				colontmpD__4 = 0;
				bbX60gensym24__1 = colontmpD__4;
			}
LA16_: ;
			result = (NI)(((NU8)(aaX60gensym24__1)) - ((NU8)(bbX60gensym24__1)));
			{
				if (!!((result == ((NI)0)))) goto LA23_;
				goto BeforeRet_;
			}
LA23_: ;
			{
				if (!(aLenX60gensym24__1 <= iX60gensym24__1)) goto LA27_;
				{
					if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA31_;
					result = ((NI)0);
					goto BeforeRet_;
				}
LA31_: ;
				result = ((NI)-1);
				goto BeforeRet_;
			}
			goto LA25_;
LA27_: ;
			{
				if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA34_;
				result = ((NI)1);
				goto BeforeRet_;
			}
			goto LA25_;
LA34_: ;
LA25_: ;
			iX60gensym24__1 += ((NI)1);
			jX60gensym24__1 += ((NI)1);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2641)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0) {
	NI result;
	NI i_1;
NIM_BOOL* nimErr_;
	nimfr_("findNormalized", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(2823, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");	i_1 = ((NI)0);
	{
		nimln_(2824);		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_52;
			if (!(i_1 < (inArray_p1Len_0-1))) goto LA2;
			nimln_(2825);			{
				NI T5_;
				if (i_1 < 0 || i_1 >= inArray_p1Len_0){ raiseIndexError2(i_1,inArray_p1Len_0-1); goto BeforeRet_;
				}
				T5_ = (NI)0;
				T5_ = nsuCmpIgnoreStyle(x_p0, inArray_p1[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T5_ == ((NI)0))) goto LA6_;
				nimln_(2822);				nimln_(2825);				result = i_1;
				goto BeforeRet_;
			}
LA6_: ;
			nimln_(2826);			if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_52)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_52);
		} LA2: ;
	}
	nimln_(2828);	nimln_(2822);	nimln_(2828);	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0) {
	NI i_1;
	NI num_1;
NIM_BOOL* nimErr_;
	nimfr_("addf", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(2837);	i_1 = ((NI)0);
	nimln_(2838);	num_1 = ((NI)0);
	{
		nimln_(2839);		while (1) {
			if (!(i_1 < formatstr_p1.len)) goto LA2;
			nimln_(2840);			{
				NIM_BOOL T5_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_27;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_28;
				T5_ = (NIM_BOOL)0;
				if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
				}
				T5_ = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(36));
				if (!(T5_)) goto LA6_;
				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_27)) { raiseOverflow(); goto BeforeRet_;
				};
				T5_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_27) < formatstr_p1.len);
LA6_: ;
				if (!T5_) goto LA7_;
				nimln_(2841);				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28) >= formatstr_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28),formatstr_p1.len-1); goto BeforeRet_;
				}
				switch (((NU8)(formatstr_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)]))) {
				case 35:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_31;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_32;
					nimln_(2843);					{
						if (!((a_p2Len_0-1) < num_1)) goto LA12_;
						invalidFormatString__pureZstrutils_u2654(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA12_: ;
					nimln_(2844);					if (num_1 < 0 || num_1 >= a_p2Len_0){ raiseIndexError2(num_1,a_p2Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&(*s_p0)), a_p2[num_1].len + 0);
appendString((&(*s_p0)), a_p2[num_1]);
					nimln_(2845);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_31)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_31);
					nimln_(2846);					if (nimAddInt(num_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)) { raiseOverflow(); goto BeforeRet_;
					};
					num_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32);
				}
				break;
				case 36:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_34;
					nimln_(2848);					nimAddCharV1((&(*s_p0)), 36);
					nimln_(2849);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI colontmpD_;
					NI colontmpD__2;
					NI j_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_35;
					NIM_BOOL negative_1;
					NI idx_1;
					colontmpD_ = (NI)0;
					colontmpD__2 = (NI)0;
					nimln_(2851);					j_1 = ((NI)0);
					nimln_(2852);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_35)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_35);
					nimln_(2853);					if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
					}
					negative_1 = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(45));
					nimln_(2854);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_36;
						if (!negative_1) goto LA18_;
						if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_36)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36);
					}
LA18_: ;
					{
						nimln_(2855);						while (1) {
							NIM_BOOL T22_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_37;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_38;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_39;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_40;
							T22_ = (NIM_BOOL)0;
							T22_ = (i_1 < formatstr_p1.len);
							if (!(T22_)) goto LA23_;
							if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
							}
							T22_ = (((NU8)(formatstr_p1.p->data[i_1])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[i_1])) <= ((NU8)(57)));
LA23_: ;
							if (!T22_) goto LA21;
							nimln_(2856);							if (nimMulInt(j_1, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)) { raiseOverflow(); goto BeforeRet_;
							};
							if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
							}
							if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37), ((NU8)(formatstr_p1.p->data[i_1])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_39)) { raiseOverflow(); goto BeforeRet_;
							};
							j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_39);
							nimln_(2857);							if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_40)) { raiseOverflow(); goto BeforeRet_;
							};
							i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_40);
						} LA21: ;
					}
					nimln_(2858);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_41;
						if (!!(negative_1)) goto LA26_;
						if (nimSubInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41);
						idx_1 = colontmpD_;
					}
					goto LA24_;
LA26_: ;
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_42;
						if (nimSubInt(a_p2Len_0, j_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_42)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD__2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_42);
						idx_1 = colontmpD__2;
					}
LA24_: ;
					nimln_(2859);					{
						NIM_BOOL T31_;
						T31_ = (NIM_BOOL)0;
						T31_ = (idx_1 < ((NI)0));
						if (T31_) goto LA32_;
						T31_ = ((a_p2Len_0-1) < idx_1);
LA32_: ;
						if (!T31_) goto LA33_;
						invalidFormatString__pureZstrutils_u2654(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA33_: ;
					nimln_(2860);					if (idx_1 < 0 || idx_1 >= a_p2Len_0){ raiseIndexError2(idx_1,a_p2Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&(*s_p0)), a_p2[idx_1].len + 0);
appendString((&(*s_p0)), a_p2[idx_1]);
				}
				break;
				case 123:
				{
					NI j_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_43;
					NI k_1;
					NIM_BOOL negative_2;
					NI isNumber_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_56;
					nimln_(2862);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)) { raiseOverflow(); goto BeforeRet_;
					};
					j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43);
					nimln_(2863);					k_1 = ((NI)0);
					nimln_(2864);					if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
					}
					negative_2 = ((NU8)(formatstr_p1.p->data[j_2]) == (NU8)(45));
					nimln_(2865);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_44;
						if (!negative_2) goto LA38_;
						if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_44)) { raiseOverflow(); goto BeforeRet_;
						};
						j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44);
					}
LA38_: ;
					nimln_(2866);					isNumber_1 = ((NI)0);
					{
						nimln_(2867);						while (1) {
							NIM_BOOL T42_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_48;
							T42_ = (NIM_BOOL)0;
							T42_ = (j_2 < formatstr_p1.len);
							if (!(T42_)) goto LA43_;
							if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
							}
							T42_ = !((((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(0)) || ((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(125))));
LA43_: ;
							if (!T42_) goto LA41;
							nimln_(2868);							{
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_45;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_46;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_47;
								if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
								}
								if (!(((NU8)(formatstr_p1.p->data[j_2])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_2])) <= ((NU8)(57)))) goto LA46_;
								nimln_(2869);								if (nimMulInt(k_1, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_45)) { raiseOverflow(); goto BeforeRet_;
								};
								if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
								}
								if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_45), ((NU8)(formatstr_p1.p->data[j_2])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_46)) { raiseOverflow(); goto BeforeRet_;
								};
								if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_47)) { raiseOverflow(); goto BeforeRet_;
								};
								k_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_47);
								nimln_(2870);								{
									if (!(isNumber_1 == ((NI)0))) goto LA50_;
									isNumber_1 = ((NI)1);
								}
LA50_: ;
							}
							goto LA44_;
LA46_: ;
							{
								nimln_(2872);								isNumber_1 = ((NI)-1);
							}
LA44_: ;
							nimln_(2873);							if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)) { raiseOverflow(); goto BeforeRet_;
							};
							j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48);
						} LA41: ;
					}
					nimln_(2874);					{
						NI colontmpD__3;
						NI colontmpD__4;
						NI idx_2;
						if (!(isNumber_1 == ((NI)1))) goto LA55_;
						colontmpD__3 = (NI)0;
						colontmpD__4 = (NI)0;
						nimln_(2875);						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_49;
							if (!!(negative_2)) goto LA59_;
							if (nimSubInt(k_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_49)) { raiseOverflow(); goto BeforeRet_;
							};
							colontmpD__3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_49);
							idx_2 = colontmpD__3;
						}
						goto LA57_;
LA59_: ;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_50;
							if (nimSubInt(a_p2Len_0, k_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_50)) { raiseOverflow(); goto BeforeRet_;
							};
							colontmpD__4 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_50);
							idx_2 = colontmpD__4;
						}
LA57_: ;
						nimln_(2876);						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = (idx_2 < ((NI)0));
							if (T64_) goto LA65_;
							T64_ = ((a_p2Len_0-1) < idx_2);
LA65_: ;
							if (!T64_) goto LA66_;
							invalidFormatString__pureZstrutils_u2654(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA66_: ;
						nimln_(2877);						if (idx_2 < 0 || idx_2 >= a_p2Len_0){ raiseIndexError2(idx_2,a_p2Len_0-1); goto BeforeRet_;
						}
						prepareAdd((&(*s_p0)), a_p2[idx_2].len + 0);
appendString((&(*s_p0)), a_p2[idx_2]);
					}
					goto LA53_;
LA55_: ;
					{
						NimStringV2 colontmpD__5;
						NI x_1;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_53;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_54;
						colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
						nimln_(2879);						if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_53)) { raiseOverflow(); goto LA69_;
						};
						if (nimSubInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_54)) { raiseOverflow(); goto LA69_;
						};
						colontmpD__5 = substr__system_u8911(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_53), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_54));
						x_1 = findNormalized__pureZstrutils_u2641(colontmpD__5, a_p2, a_p2Len_0);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						nimln_(2880);						{
							NIM_BOOL T72_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_55;
							T72_ = (NIM_BOOL)0;
							T72_ = (((NI)0) <= x_1);
							if (!(T72_)) goto LA73_;
							T72_ = (x_1 < (a_p2Len_0-1));
LA73_: ;
							if (!T72_) goto LA74_;
							if (nimAddInt(x_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_55)) { raiseOverflow(); goto LA69_;
							};
							if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_55) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_55) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_55),a_p2Len_0-1); goto LA69_;
							}
							prepareAdd((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_55)].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_55)]);
						}
						goto LA70_;
LA74_: ;
						{
							nimln_(2881);							invalidFormatString__pureZstrutils_u2654(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						}
LA70_: ;
						{
							LA69_:;
						}
						{
							nimlf_(394, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");							if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA53_: ;
					nimlf_(2882, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");					if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_56)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_56);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NimStringV2 colontmpD__6;
					NI j_3;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_57;
					NI x_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_59;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_60;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					nimln_(2884);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_57)) { raiseOverflow(); goto LA80_;
					};
					j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_57);
					{
						nimln_(2885);						while (1) {
							NIM_BOOL T83_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_58;
							T83_ = (NIM_BOOL)0;
							T83_ = (j_3 < formatstr_p1.len);
							if (!(T83_)) goto LA84_;
							if (j_3 < 0 || j_3 >= formatstr_p1.len){ raiseIndexError2(j_3,formatstr_p1.len-1); goto LA80_;
							}
							T83_ = (((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(97)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(122)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(65)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(90)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(57)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(128)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(255)) || ((NU8)(formatstr_p1.p->data[j_3])) == ((NU8)(95)));
LA84_: ;
							if (!T83_) goto LA82;
							if (nimAddInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_58)) { raiseOverflow(); goto LA80_;
							};
							j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_58);
						} LA82: ;
					}
					nimln_(2886);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_59)) { raiseOverflow(); goto LA80_;
					};
					if (nimSubInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_60)) { raiseOverflow(); goto LA80_;
					};
					colontmpD__6 = substr__system_u8911(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_59), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_60));
					x_2 = findNormalized__pureZstrutils_u2641(colontmpD__6, a_p2, a_p2Len_0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					nimln_(2887);					{
						NIM_BOOL T87_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_61;
						T87_ = (NIM_BOOL)0;
						T87_ = (((NI)0) <= x_2);
						if (!(T87_)) goto LA88_;
						T87_ = (x_2 < (a_p2Len_0-1));
LA88_: ;
						if (!T87_) goto LA89_;
						if (nimAddInt(x_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) { raiseOverflow(); goto LA80_;
						};
						if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61),a_p2Len_0-1); goto LA80_;
						}
						prepareAdd((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)]);
					}
					goto LA85_;
LA89_: ;
					{
						nimln_(2888);						invalidFormatString__pureZstrutils_u2654(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					}
LA85_: ;
					nimln_(2889);					i_1 = j_3;
					{
						LA80_:;
					}
					{
						nimlf_(394, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");						if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				default:
				{
					nimlf_(2891, "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");					invalidFormatString__pureZstrutils_u2654(formatstr_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				}
			}
			goto LA3_;
LA7_: ;
			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_62;
				nimln_(2893);				if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
				}
				nimAddCharV1((&(*s_p0)), formatstr_p1.p->data[i_1]);
				nimln_(2894);				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_62)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_62);
			}
LA3_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr_p0, NimStringV2* a_p1, NI a_p1Len_0) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_26;
NIM_BOOL* nimErr_;
	nimfr_("%", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(2946);	if (nimAddInt(formatstr_p0.len, (NI)((NU64)(a_p1Len_0) << (NU64)(((NI)4))), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)));
	nimln_(2947);	nsuAddf((&result), formatstr_p0, a_p1, a_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0) {
	NI result;
	NI L_1;
NIM_BOOL* nimErr_;
	nimfr_("parseInt", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(1157);	result = ((NI)0);
	nimln_(1158);	L_1 = parseInt__pureZparseutils_u920(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1159);	{
		NIM_BOOL T3_;
		tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw*) nimNewObj(sizeof(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw), NIM_ALIGNOF(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__w75dCcMqUymzJ8IcKO0oIw_);
		(*T7_).Sup.Sup.name = "ValueError";
		nimln_(1160);		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 17);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_63);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseInt", "K:\\Progz\\nim-2.2.6\\lib\\pure\\strutils.nim", 1160);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
