/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -DNO_SSL -IC:\Users\n1ght\.nimble\pkgs2\webui-2.5.0.2-0eb2646495c3c942e0ea7aefac42b63c0d8f1741\webui\webui\include -DNDEBUG -DNO_CACHING -DNO_CGI -DUSE_WEBSOCKET   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\webuiEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pstd@sexitprocs.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pstd@sexitprocs.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__JgwmIb7t9cz0POYh46wWdrA tySequence__JgwmIb7t9cz0POYh46wWdrA;
typedef struct tySequence__JgwmIb7t9cz0POYh46wWdrA_Content tySequence__JgwmIb7t9cz0POYh46wWdrA_Content;
typedef struct tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA;
typedef struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__JgwmIb7t9cz0POYh46wWdrA {
  NI len; tySequence__JgwmIb7t9cz0POYh46wWdrA_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef NU8 tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA;
typedef N_NOCONV_PTR(void, tyProc__vhjNbzH0Mvv2fTvoe1717Q) (void);
struct tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA {
	tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA kind;
union{
	tyProc__HzVCwACFYM9cx9aV62PdjtuA fun1;
	tyProc__vhjNbzH0Mvv2fTvoe1717Q fun2;
};
};
struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_CLOSURE_PTR(void, TM__JXL39bfraktrl3ZkJ5EQGjw_11) (void);
struct tySequence__JgwmIb7t9cz0POYh46wWdrA_Content { NI cap; tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, initLock__coreZlocks_u7)(CRITICAL_SECTION* lock_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, acquire__coreZlocks_u14)(CRITICAL_SECTION* lock_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NOCONV(void, callClosures__stdZexitprocs_u19)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZexitprocs_u97)(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA* dest_p0, tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA src_p1);
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3431)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZexitprocs_u6)(tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZexitprocs_u94)(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLen__stdZexitprocs_u31)(tySequence__JgwmIb7t9cz0POYh46wWdrA* s_p0, NI newlen_p1);
static N_INLINE(void, release__coreZlocks_u16)(CRITICAL_SECTION* lock_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZexitprocs_u190)(tySequence__JgwmIb7t9cz0POYh46wWdrA* x_p0, tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdup___system_u3933)(tyProc__HzVCwACFYM9cx9aV62PdjtuA src_p0, NIM_BOOL cyclic_p1, tyProc__HzVCwACFYM9cx9aV62PdjtuA* Result);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[60+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_3 = { 60 | NIM_STRLIT_FLAG, "field \'fun1\' is not accessible for type \'Fun\' using \'kind = " };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_4 = {60, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_3};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_5 = { 8 | NIM_STRLIT_FLAG, "kClosure" };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_6 = {8, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_5};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_7 = { 7 | NIM_STRLIT_FLAG, "kNoconv" };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_8 = {7, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_7};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_9 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_10 = {0, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_9};
static const struct {
  NI cap; NIM_CHAR data[60+1];
} TM__JXL39bfraktrl3ZkJ5EQGjw_12 = { 60 | NIM_STRLIT_FLAG, "field \'fun2\' is not accessible for type \'Fun\' using \'kind = " };
static const NimStringV2 TM__JXL39bfraktrl3ZkJ5EQGjw_13 = {60, (NimStrPayload*)&TM__JXL39bfraktrl3ZkJ5EQGjw_12};
N_LIB_PRIVATE tySequence__JgwmIb7t9cz0POYh46wWdrA gFuns__stdZexitprocs_u15;
N_LIB_PRIVATE CRITICAL_SECTION gFunsLock__stdZexitprocs_u14;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static N_INLINE(void, initLock__coreZlocks_u7)(CRITICAL_SECTION* lock_p0) {
	InitializeCriticalSection(lock_p0);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, acquire__coreZlocks_u14)(CRITICAL_SECTION* lock_p0) {
	EnterCriticalSection(lock_p0);
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimlf_(364, "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimln_(353);	nimln_(357);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* h_1;
	NI T1_;
	nimfr_("nimIncRefCyclic", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimlf_(47, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	h_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T1_));
	nimlf_(48, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	(*h_1).rc = pluspercent___system_u793((*h_1).rc, ((NI)16));
	popFrame();
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T5_));
		nimlf_(521, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3431(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZexitprocs_u97)(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA* dest_p0, tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA src_p1) {
	tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA colontmp_;
	nimZeroMem((void*)(&colontmp_), sizeof(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA));
	colontmp_ = (*dest_p0);
	nimZeroMem((void*)(&(*dest_p0)), sizeof(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA));
	(*dest_p0).kind = src_p1.kind;
	switch ((*dest_p0).kind) {
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)0):
	{
		void* colontmp__2;
		nimZeroMem((void*)(&(*dest_p0).fun1), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
		colontmp__2 = (*dest_p0).fun1.ClE_0;
		{
			if (!src_p1.fun1.ClE_0) goto LA4_;
			nimIncRefCyclic(src_p1.fun1.ClE_0, NIM_TRUE);
		}
LA4_: ;
		(*dest_p0).fun1.ClE_0 = src_p1.fun1.ClE_0;
		(*dest_p0).fun1.ClP_0 = src_p1.fun1.ClP_0;
		{
			NIM_BOOL T8_;
			T8_ = (NIM_BOOL)0;
			T8_ = nimDecRefIsLastCyclicDyn(colontmp__2);
			if (!T8_) goto LA9_;
			nimDestroyAndDispose(colontmp__2);
		}
LA9_: ;
	}
	break;
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)1):
	{
		(*dest_p0).fun2 = 0;
		(*dest_p0).fun2 = src_p1.fun2;
	}
	break;
	default: __builtin_unreachable();
	}
	switch (colontmp_.kind) {
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)0):
	{
		{
			NIM_BOOL T15_;
			T15_ = (NIM_BOOL)0;
			T15_ = nimDecRefIsLastCyclicDyn(colontmp_.fun1.ClE_0);
			if (!T15_) goto LA16_;
			nimDestroyAndDispose(colontmp_.fun1.ClE_0);
		}
LA16_: ;
	}
	break;
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)1):
	{
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZexitprocs_u6)(tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)0):
	{
		result = TM__JXL39bfraktrl3ZkJ5EQGjw_6;
	}
	break;
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)1):
	{
		result = TM__JXL39bfraktrl3ZkJ5EQGjw_8;
	}
	break;
	default:
	{
		result = TM__JXL39bfraktrl3ZkJ5EQGjw_10;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZexitprocs_u94)(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)0):
	{
		{
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = nimDecRefIsLastCyclicDyn((*dest_p0).fun1.ClE_0);
			if (!T4_) goto LA5_;
			nimDestroyAndDispose((*dest_p0).fun1.ClE_0);
		}
LA5_: ;
	}
	break;
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)1):
	{
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___stdZexitprocs_u91)(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA* dest_p0) {
	(*dest_p0).kind = 0;
	switch ((*dest_p0).kind) {
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)0):
	{
		nimZeroMem((void*)(&(*dest_p0).fun1), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	}
	break;
	case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)1):
	{
		(*dest_p0).fun2 = 0;
	}
	break;
	default: __builtin_unreachable();
	}
}
static N_INLINE(void, release__coreZlocks_u16)(CRITICAL_SECTION* lock_p0) {
	LeaveCriticalSection(lock_p0);
}
N_LIB_PRIVATE N_NOCONV(void, callClosures__stdZexitprocs_u19)(void) {
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("callClosures", "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(83, "K:\\Progz\\nim-2.2.6\\lib\\core\\locks.nim");	acquire__coreZlocks_u14((&gFunsLock__stdZexitprocs_u14));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI T3_;
		NI TM__JXL39bfraktrl3ZkJ5EQGjw_2;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(6, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		nimlf_(45, "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");		T3_ = gFuns__stdZexitprocs_u15.len;
		if (nimSubInt(T3_, ((NI)1), &TM__JXL39bfraktrl3ZkJ5EQGjw_2)) { raiseOverflow(); goto LA1_;
		};
		colontmp_ = (NI)(TM__JXL39bfraktrl3ZkJ5EQGjw_2);
		nimlf_(33, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");		res_1 = colontmp_;
		{
			nimln_(34);			while (1) {
				tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA fun_1;
				NI TM__JXL39bfraktrl3ZkJ5EQGjw_14;
				if (!(((NI)0) <= res_1)) goto LA5;
				nimZeroMem((void*)(&fun_1), sizeof(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA));
				nimlf_(45, "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");				i_1 = ((NI) (res_1));
				nimlf_(934, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");				if (i_1 < 0 || i_1 >= gFuns__stdZexitprocs_u15.len){ raiseIndexError2(i_1,gFuns__stdZexitprocs_u15.len-1); goto LA1_;
				}
				eqcopy___stdZexitprocs_u97((&fun_1), gFuns__stdZexitprocs_u15.p->data[i_1]);
				nimlf_(47, "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");				switch (fun_1.kind) {
				case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)0):
				{
					nimln_(48);					if (!(((1 &((NU8)1<<((NU)((fun_1.kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__JXL39bfraktrl3ZkJ5EQGjw_4, dollar___stdZexitprocs_u6(fun_1.kind)); goto LA1_;
					}
					fun_1.fun1.ClE_0? fun_1.fun1.ClP_0(fun_1.fun1.ClE_0):((TM__JXL39bfraktrl3ZkJ5EQGjw_11)(fun_1.fun1.ClP_0))();
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				break;
				case ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)1):
				{
					nimln_(49);					if (!(((2 &((NU8)1<<((NU)((fun_1.kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__JXL39bfraktrl3ZkJ5EQGjw_13, dollar___stdZexitprocs_u6(fun_1.kind)); goto LA1_;
					}
					fun_1.fun2();
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				break;
				default: __builtin_unreachable();
				}
				nimlf_(39, "K:\\Progz\\nim-2.2.6\\lib\\system\\iterators_1.nim");				if (nimSubInt(res_1, ((NI)1), &TM__JXL39bfraktrl3ZkJ5EQGjw_14)) { raiseOverflow(); goto LA1_;
				};
				res_1 = (NI)(TM__JXL39bfraktrl3ZkJ5EQGjw_14);
				nimlf_(934, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");				eqdestroy___stdZexitprocs_u94((&fun_1));
			} LA5: ;
		}
	}
	nimlf_(50, "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");	setLen__stdZexitprocs_u31((&gFuns__stdZexitprocs_u15), ((NI)0));
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(88, "K:\\Progz\\nim-2.2.6\\lib\\core\\locks.nim");		release__coreZlocks_u16((&gFunsLock__stdZexitprocs_u14));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, addExitProc__stdZexitprocs_u184)(tyProc__HzVCwACFYM9cx9aV62PdjtuA cl_p0) {
	tyProc__HzVCwACFYM9cx9aV62PdjtuA colontmpD_;
	tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA T7_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("addExitProc", "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");
{nimErr_ = nimErrorFlag();
	nimln_(83);	acquire__coreZlocks_u14((&gFunsLock__stdZexitprocs_u14));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	nimlf_(63, "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");	{
		NI T4_;
		nimln_(53);		T4_ = gFuns__stdZexitprocs_u15.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		nimln_(54);		atexit(callClosures__stdZexitprocs_u19);
	}
LA5_: ;
	nimln_(64);	nimZeroMem((void*)(&T7_), sizeof(tyObject_Fun__SQuEpBkO9cKPDZxq9bEtpLwA));
	T7_.kind = ((tyEnum_FunKind__f9a73iUBxs3og9a9as2iKRegA)0);
	nimlf_(38, "K:\\Progz\\nim-2.2.6\\lib\\system\\threadimpl.nim");	eqdup___system_u3933(cl_p0, NIM_TRUE, (&colontmpD_));
	T7_.fun1.ClE_0 = colontmpD_.ClE_0;
	T7_.fun1.ClP_0 = colontmpD_.ClP_0;
	nimlf_(64, "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");	add__stdZexitprocs_u190((&gFuns__stdZexitprocs_u15), T7_);
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(88, "K:\\Progz\\nim-2.2.6\\lib\\core\\locks.nim");		release__coreZlocks_u16((&gFunsLock__stdZexitprocs_u14));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsexitprocsdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("exitprocs", "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");
nimErr_ = nimErrorFlag();
	nimlf_(27, "K:\\Progz\\nim-2.2.6\\lib\\std\\exitprocs.nim");	initLock__coreZlocks_u7((&gFunsLock__stdZexitprocs_u14));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

