/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -DNO_SSL -IC:\Users\n1ght\.nimble\pkgs2\webui-2.5.0.2-0eb2646495c3c942e0ea7aefac42b63c0d8f1741\webui\webui\include -DNDEBUG -DNO_CACHING -DNO_CGI -DUSE_WEBSOCKET   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\webuiEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@ptables.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@ptables.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg;
typedef struct tySequence__9clQuZ6vR9aegLYewjCfDuSQ tySequence__9clQuZ6vR9aegLYewjCfDuSQ;
typedef struct tySequence__9clQuZ6vR9aegLYewjCfDuSQ_Content tySequence__9clQuZ6vR9aegLYewjCfDuSQ_Content;
typedef struct tyTuple__fXFNu89aKPinEjbDbEkRPCg tyTuple__fXFNu89aKPinEjbDbEkRPCg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw;
typedef struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg;
typedef struct tySequence__PeOPK4xtHMbHys9bYUhFLJg tySequence__PeOPK4xtHMbHys9bYUhFLJg;
typedef struct tySequence__PeOPK4xtHMbHys9bYUhFLJg_Content tySequence__PeOPK4xtHMbHys9bYUhFLJg_Content;
typedef struct tyObject_KeyError__cEBjH5LNl2BlANEiuXVbvw tyObject_KeyError__cEBjH5LNl2BlANEiuXVbvw;
typedef struct tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw;
typedef struct tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ tySequence__Eio1jF59abEpv9bLmutTDQvQ;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content;
typedef struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw;
struct tySequence__9clQuZ6vR9aegLYewjCfDuSQ {
  NI len; tySequence__9clQuZ6vR9aegLYewjCfDuSQ_Content* p;
};
struct tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg {
	tySequence__9clQuZ6vR9aegLYewjCfDuSQ data;
	NI counter;
	NI first;
	NI last;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__fXFNu89aKPinEjbDbEkRPCg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* Field3;
};
struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg {
	NI rc;
	NI rootIdx;
};
typedef NU8 tyEnum_JsonNodeKind__pIgEqBN9caKLXmVQcXgyYkg;
struct tySequence__PeOPK4xtHMbHys9bYUhFLJg {
  NI len; tySequence__PeOPK4xtHMbHys9bYUhFLJg_Content* p;
};
struct tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__pIgEqBN9caKLXmVQcXgyYkg kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg fields;
} _kind_6;
	struct {
	tySequence__PeOPK4xtHMbHys9bYUhFLJg elems;
} _kind_7;
};
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ {
  NI len; tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__Eio1jF59abEpv9bLmutTDQvQ trace;
	Exception* up;
};
struct tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA {
	Exception Sup;
};
struct tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw {
	tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA Sup;
};
struct tyObject_KeyError__cEBjH5LNl2BlANEiuXVbvw {
	tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw Sup;
};
struct tySequence__9clQuZ6vR9aegLYewjCfDuSQ_Content { NI cap; tyTuple__fXFNu89aKPinEjbDbEkRPCg data[SEQ_DECL_SIZE]; };
struct tySequence__PeOPK4xtHMbHys9bYUhFLJg_Content { NI cap; tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content { NI cap; tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u249)(NI x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZjson_u468)(tySequence__9clQuZ6vR9aegLYewjCfDuSQ* s_p0, NI len_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, unregisterCycle__system_u3080)(tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u67)(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_u797)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u601)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZjson_u330)(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw** dest_p0, tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* src_p1);
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_u1125)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_u1276)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_u1659)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, tySequence__9clQuZ6vR9aegLYewjCfDuSQ* data_p1, NimStringV2 key_p2, tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* val_p3, NI hc_p4, NI h_p5);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2661)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2658)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZjson_u318)(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u91)(tySequence__9clQuZ6vR9aegLYewjCfDuSQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_u1921)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1, NI hc_p2);
static N_INLINE(NI, rawGet__pureZjson_u3051)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_u3308)(NimStringV2 key_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static const struct {
  NI cap; NIM_CHAR data[87+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_6 = { 87 | NIM_STRLIT_FLAG, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim(34, 9) `\012t.counter < t.dataLen` " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_7 = {87, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_6};
extern TNimTypeV2 NTIv2__cEBjH5LNl2BlANEiuXVbvw_;
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_15 = { 15 | NIM_STRLIT_FLAG, "key not found: " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_16 = {15, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_15};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_2;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_3;
NIM_BOOL* nimErr_;
	nimfr_("slotsNeeded", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(39, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	if (nimAddInt((NI)((count_p0) / (((NI)2))), count_p0, &TM__4SoG2KRQy3oMm9aUzSLtGrA_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_2), ((NI)4), &TM__4SoG2KRQy3oMm9aUzSLtGrA_3)) { raiseOverflow(); goto BeforeRet_;
	};
	result = nextPowerOfTwo__pureZmath_u249((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_3));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");
	nimlf_(364, "K:\\Progz\\nim-2.2.6\\lib\\system\\arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastDyn", "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");
	nimlf_(530, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");	result = NIM_FALSE;
	nimln_(531);	{
		tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(532);		nimlf_(60, "K:\\Progz\\nim-2.2.6\\lib\\system\\arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T5_));
		nimlf_(533, "K:\\Progz\\nim-2.2.6\\lib\\system\\orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(534);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(537);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(539);		{
			if (!result) goto LA13_;
			nimln_(540);			{
				if (!(((NI)0) < (*cell_1).rootIdx)) goto LA17_;
				nimln_(541);				unregisterCycle__system_u3080(cell_1);
			}
LA17_: ;
		}
LA13_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u91)(tySequence__9clQuZ6vR9aegLYewjCfDuSQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field2.p && !(dest_p0.p->data[colontmp_].Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field2.p);
}
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastDyn(dest_p0.p->data[colontmp_].Field3);
				if (!T6_) goto LA7_;
				eqdestroy___pureZjson_u67((&(*dest_p0.p->data[colontmp_].Field3)));
				nimRawDispose(dest_p0.p->data[colontmp_].Field3, ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__fXFNu89aKPinEjbDbEkRPCg));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u158)(tyTuple__fXFNu89aKPinEjbDbEkRPCg* dest_p0) {
	if ((*dest_p0).Field2.p && !((*dest_p0).Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field2.p);
}
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastDyn((*dest_p0).Field3);
		if (!T3_) goto LA4_;
		eqdestroy___pureZjson_u67((&(*(*dest_p0).Field3)));
		nimRawDispose((*dest_p0).Field3, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZjson_u155)(tyTuple__fXFNu89aKPinEjbDbEkRPCg* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1 = 0;
	(*dest_p0).Field2.len = 0; (*dest_p0).Field2.p = NIM_NIL;
	(*dest_p0).Field3 = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_u454)(NI initialSize_p0, tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* Result) {
	NI correctSizeX60gensym0__1;
NIM_BOOL* nimErr_;
	nimfr_("initOrderedTable", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1411, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");	nimZeroMem((void*)Result, sizeof(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg));
	nimlf_(182, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tableimpl.nim");	if ((initialSize_p0) < ((NI)0) || (initialSize_p0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p0, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	correctSizeX60gensym0__1 = slotsNeeded__pureZcollectionsZtables_u42((initialSize_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(186);	(*Result).counter = ((NI)0);
	nimln_(187);	if ((correctSizeX60gensym0__1) < ((NI)0) || (correctSizeX60gensym0__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym0__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__pureZjson_u468((&(*Result).data), (correctSizeX60gensym0__1));
	nimln_(189);	(*Result).first = ((NI)-1);
	nimln_(190);	(*Result).last = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isFilled", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
	nimlf_(27, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	result = !((hcode_p0 == ((NI)0)));
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "K:\\Progz\\nim-2.2.6\\lib\\system\\strmantle.nim");
{	nimlf_(33, "K:\\Progz\\nim-2.2.6\\lib\\system\\strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1749(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_4;
	nimfr_("nextTry", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{	result = (NI)0;
	nimlf_(30, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	if (nimAddInt(h_p0, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_4)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_4) & maxHash_p1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_u797)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_5;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(72);	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u601(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = (*t_p0).data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimlf_(1357, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");		nimlf_(43, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = ((*t_p0).data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T17_ = ((*t_p0).data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T17_ = eqStrings((*t_p0).data.p->data[h_1].Field2, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimlf_(1357, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");				nimlf_(51, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = ((*t_p0).data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_5)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_5);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_u1125)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_8;
	NI T9_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_9;
NIM_BOOL* nimErr_;
	nimfr_("mustRehash", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(34);	{
		NI T3_;
		T3_ = (*t_p0).data.len;
		if (!!(((*t_p0).counter < T3_))) goto LA4_;
		failedAssertImpl__stdZassertions_u234(TM__4SoG2KRQy3oMm9aUzSLtGrA_7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimln_(35);	T6_ = (NIM_BOOL)0;
	T7_ = (*t_p0).data.len;
	if (nimAddInt((*t_p0).counter, (NI)(((*t_p0).counter) / (((NI)2))), &TM__4SoG2KRQy3oMm9aUzSLtGrA_8)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = (T7_ < (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_8));
	if (T6_) goto LA8_;
	T9_ = (*t_p0).data.len;
	if (nimSubInt(T9_, (*t_p0).counter, &TM__4SoG2KRQy3oMm9aUzSLtGrA_9)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_9) < ((NI)4));
LA8_: ;
	result = T6_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_u1659)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, tySequence__9clQuZ6vR9aegLYewjCfDuSQ* data_p1, NimStringV2 key_p2, tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* val_p3, NI hc_p4, NI h_p5) {
NIM_BOOL* nimErr_;
	nimfr_("rawInsert", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1699, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");	if (h_p5 < 0 || h_p5 >= (*data_p1).len){ raiseIndexError2(h_p5,(*data_p1).len-1); goto BeforeRet_;
	}
	eqcopy___system_u2661((&(*data_p1).p->data[h_p5].Field2), key_p2);
	nimln_(934);	if (h_p5 < 0 || h_p5 >= (*data_p1).len){ raiseIndexError2(h_p5,(*data_p1).len-1); goto BeforeRet_;
	}
	eqsink___pureZjson_u330(&(*data_p1).p->data[h_p5].Field3, val_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(27, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tableimpl.nim");	if (h_p5 < 0 || h_p5 >= (*data_p1).len){ raiseIndexError2(h_p5,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p5].Field0 = hc_p4;
	nimlf_(1364, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");	if (h_p5 < 0 || h_p5 >= (*data_p1).len){ raiseIndexError2(h_p5,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p5].Field1 = ((NI)-1);
	nimln_(1365);	{
		if (!((*t_p0).first < ((NI)0))) goto LA3_;
		(*t_p0).first = h_p5;
	}
LA3_: ;
	nimln_(1366);	{
		if (!(((NI)0) <= (*t_p0).last)) goto LA7_;
		if ((*t_p0).last < 0 || (*t_p0).last >= (*data_p1).len){ raiseIndexError2((*t_p0).last,(*data_p1).len-1); goto BeforeRet_;
		}
		(*data_p1).p->data[(*t_p0).last].Field1 = h_p5;
	}
LA7_: ;
	nimln_(1367);	(*t_p0).last = h_p5;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_u1276)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0) {
	tySequence__9clQuZ6vR9aegLYewjCfDuSQ n_1;
	NI T1_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_10;
	NI h_1;
	tySequence__9clQuZ6vR9aegLYewjCfDuSQ T2_;
NIM_BOOL* nimErr_;
	nimfr_("enlarge", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	nimln_(1371);	T1_ = (*t_p0).data.len;
	if (nimMulInt(T1_, ((NI)2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) < ((NI)0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__pureZjson_u468((&n_1), ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10)));
	nimln_(1372);	h_1 = (*t_p0).first;
	nimln_(1373);	(*t_p0).first = ((NI)-1);
	nimln_(1374);	(*t_p0).last = ((NI)-1);
	nimln_(1375);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*t_p0).data;
	(*t_p0).data = n_1;
	n_1 = T2_;
	{
		nimln_(1376);		while (1) {
			NI nxt_1;
			NI eh_1;
			if (!(((NI)0) <= h_1)) goto LA4;
			nimln_(1377);			if (h_1 < 0 || h_1 >= n_1.len){ raiseIndexError2(h_1,n_1.len-1); goto BeforeRet_;
			}
			nxt_1 = n_1.p->data[h_1].Field1;
			nimln_(1378);			if (h_1 < 0 || h_1 >= n_1.len){ raiseIndexError2(h_1,n_1.len-1); goto BeforeRet_;
			}
			eh_1 = n_1.p->data[h_1].Field0;
			nimln_(1379);			{
				NIM_BOOL T7_;
				NimStringV2 colontmpD_;
				NI j_1;
				NI T10_;
				tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* T15_;
				tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* T16_;
				T7_ = (NIM_BOOL)0;
				T7_ = isFilled__pureZcollectionsZtables_u31(eh_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!T7_) goto LA8_;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimln_(1380);				T10_ = ((*t_p0).data.len-1);
				j_1 = (NI)(eh_1 & T10_);
				{
					nimln_(1381);					while (1) {
						NIM_BOOL T13_;
						NI T14_;
						if (j_1 < 0 || j_1 >= (*t_p0).data.len){ raiseIndexError2(j_1,(*t_p0).data.len-1); goto BeforeRet_;
						}
						T13_ = (NIM_BOOL)0;
						T13_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[j_1].Field0);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T13_) goto LA12;
						nimln_(1382);						T14_ = ((*t_p0).data.len-1);
						j_1 = nextTry__pureZcollectionsZtables_u34(j_1, T14_);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					} LA12: ;
				}
				nimln_(1383);				T15_ = (tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg*)0;
				T15_ = t_p0;
				if (h_1 < 0 || h_1 >= n_1.len){ raiseIndexError2(h_1,n_1.len-1); goto BeforeRet_;
				}
				colontmpD_ = n_1.p->data[h_1].Field2;
				eqwasMoved___system_u2658((&n_1.p->data[h_1].Field2));
				if (h_1 < 0 || h_1 >= n_1.len){ raiseIndexError2(h_1,n_1.len-1); goto BeforeRet_;
				}
				T16_ = NIM_NIL;
				T16_ = n_1.p->data[h_1].Field3;
				eqwasMoved___pureZjson_u318((&n_1.p->data[h_1].Field3));
				if (h_1 < 0 || h_1 >= n_1.len){ raiseIndexError2(h_1,n_1.len-1); goto BeforeRet_;
				}
				rawInsert__pureZjson_u1659(T15_, (&(*t_p0).data), colontmpD_, T16_, n_1.p->data[h_1].Field0, j_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(394, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			}
LA8_: ;
			nimlf_(1384, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");			h_1 = nxt_1;
		} LA4: ;
	}
	nimlf_(218, "K:\\Progz\\nim-2.2.6\\lib\\pure\\json.nim");	eqdestroy___pureZjson_u91(n_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_u1921)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_11;
NIM_BOOL* nimErr_;
	nimfr_("rawGetKnownHC", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(42, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	{
		NI T3_;
		T3_ = (*t_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(43);		nimlf_(1351, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");		nimlf_(43, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(44);	T6_ = ((*t_p0).data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
			}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			nimln_(50);			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T12_ = ((*t_p0).data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T12_ = eqStrings((*t_p0).data.p->data[h_1].Field2, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				nimln_(51);				nimlf_(1351, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");				nimlf_(51, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			nimln_(52);			T16_ = ((*t_p0).data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_11)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_11);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_u728)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1, tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* val_p2) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("[]=", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(58, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tableimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym13__1;
		nimln_(37);		T3_ = (*t_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(182);		correctSizeX60gensym13__1 = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(186);		(*t_p0).counter = ((NI)0);
		nimln_(187);		if ((correctSizeX60gensym13__1) < ((NI)0) || (correctSizeX60gensym13__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym13__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__pureZjson_u468((&(*t_p0).data), (correctSizeX60gensym13__1));
		nimln_(189);		(*t_p0).first = ((NI)-1);
		nimln_(190);		(*t_p0).last = ((NI)-1);
	}
LA4_: ;
	nimln_(59);	hc_1 = 0;
	nimln_(60);	index_1 = rawGet__pureZjson_u797((&(*t_p0)), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(1428, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");	{
		nimlf_(61, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tableimpl.nim");		if (!(((NI)0) <= index_1)) goto LA8_;
		nimlf_(934, "K:\\Progz\\nim-2.2.6\\lib\\system.nim");		if (index_1 < 0 || index_1 >= (*t_p0).data.len){ raiseIndexError2(index_1,(*t_p0).data.len-1); goto BeforeRet_;
		}
		eqsink___pureZjson_u330(&(*t_p0).data.p->data[index_1].Field3, val_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA6_;
LA8_: ;
	{
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_12;
		tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* T21_;
		tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw* blitTmp_1;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_13;
		nimlf_(49, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tableimpl.nim");		{
			NI T13_;
			NI correctSizeX60gensym18__1;
			nimln_(37);			T13_ = (*t_p0).data.len;
			if (!(T13_ == ((NI)0))) goto LA14_;
			nimln_(182);			correctSizeX60gensym18__1 = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(186);			(*t_p0).counter = ((NI)0);
			nimln_(187);			if ((correctSizeX60gensym18__1) < ((NI)0) || (correctSizeX60gensym18__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym18__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			newSeq__pureZjson_u468((&(*t_p0).data), (correctSizeX60gensym18__1));
			nimln_(189);			(*t_p0).first = ((NI)-1);
			nimln_(190);			(*t_p0).last = ((NI)-1);
		}
LA14_: ;
		nimln_(50);		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__pureZjson_u1125((&(*t_p0)));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T18_) goto LA19_;
			nimln_(51);			enlarge__pureZjson_u1276(t_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(52);			index_1 = rawGetKnownHC__pureZjson_u1921((&(*t_p0)), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA19_: ;
		nimln_(53);		if (nimSubInt(((NI)-1), index_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) { raiseOverflow(); goto BeforeRet_;
		};
		index_1 = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12);
		nimln_(54);		T21_ = (tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg*)0;
		T21_ = t_p0;
		nimln_(62);		blitTmp_1 = val_p2;
		nimln_(54);		rawInsert__pureZjson_u1659(T21_, (&(*t_p0).data), key_p1, blitTmp_1, hc_1, index_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(62);		if (nimAddInt((*t_p0).counter, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_13)) { raiseOverflow(); goto BeforeRet_;
		};
		(*t_p0).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_13);
	}
LA6_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u2970)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("hasKey", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(1503, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");	hc_1 = 0;
	nimln_(1504);	T1_ = (NI)0;
	T1_ = rawGet__pureZjson_u797(t_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGet__pureZjson_u3051)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_14;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(72, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\hashcommon.nim");	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u601(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = (*t_p0).data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimln_(75);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = ((*t_p0).data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T17_ = ((*t_p0).data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= (*t_p0).data.len){ raiseIndexError2(h_1,(*t_p0).data.len-1); goto BeforeRet_;
				}
				T17_ = eqStrings((*t_p0).data.p->data[h_1].Field2, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimln_(75);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = ((*t_p0).data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_17;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__4SoG2KRQy3oMm9aUzSLtGrA_17)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_17);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_u3308)(NimStringV2 key_p0) {
	tyObject_KeyError__cEBjH5LNl2BlANEiuXVbvw* T1_;
	NimStringV2 T2_;
	nimfr_("raiseKeyError", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_KeyError__cEBjH5LNl2BlANEiuXVbvw*) nimNewObj(sizeof(tyObject_KeyError__cEBjH5LNl2BlANEiuXVbvw), NIM_ALIGNOF(tyObject_KeyError__cEBjH5LNl2BlANEiuXVbvw));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__cEBjH5LNl2BlANEiuXVbvw_);
	(*T1_).Sup.Sup.Sup.name = "KeyError";
	nimlf_(232, "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(key_p0.len + 15);
appendString((&T2_), TM__4SoG2KRQy3oMm9aUzSLtGrA_16);
appendString((&T2_), key_p0);
	(*T1_).Sup.Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "KeyError", "raiseKeyError", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim", 232);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw**, X5BX5D___pureZjson_u3044)(tyObject_OrderedTable__od9aPAPpUDu8JO3nMXozuFg* t_p0, NimStringV2 key_p1) {
	tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw** result;
	NI hcX60gensym97__1;
	NI indexX60gensym97__1;
NIM_BOOL* nimErr_;
	nimfr_("[]", "K:\\Progz\\nim-2.2.6\\lib\\pure\\collections\\tables.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_JsonNodeObj__M6Finu0fRVfZbeZ2hzK0lw**)0;
	hcX60gensym97__1 = (NI)0;
	nimln_(241);	indexX60gensym97__1 = rawGet__pureZjson_u3051((&(*t_p0)), key_p1, (&hcX60gensym97__1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1485);	{
		nimln_(242);		if (!(((NI)0) <= indexX60gensym97__1)) goto LA3_;
		if (indexX60gensym97__1 < 0 || indexX60gensym97__1 >= (*t_p0).data.len){ raiseIndexError2(indexX60gensym97__1,(*t_p0).data.len-1); goto BeforeRet_;
		}
		result = &(*t_p0).data.p->data[indexX60gensym97__1].Field3;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(244);		raiseKeyError__pureZjson_u3308(key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
