/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -DNO_SSL -IC:\Users\n1ght\.nimble\pkgs2\webui-2.5.0.2-0eb2646495c3c942e0ea7aefac42b63c0d8f1741\webui\webui\include -DNDEBUG -DNO_CACHING -DNO_CGI -DUSE_WEBSOCKET   -IK:\Progz\nim-2.2.6\lib -If:\CodingMain\proto-ViableNimUIs\examples\webuiEnhanced\customTitlebar -o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pwinlean.nim.c.o f:\CodingMain\proto-ViableNimUIs\.nimcache\webui_custom\@pwinlean.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_GUID__gqVITC6hRRkXjcpIWgpejw tyObject_GUID__gqVITC6hRRkXjcpIWgpejw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef NI8 tyArray__9cWG514ToTTjfTPLhXXV0IQ[8];
struct tyObject_GUID__gqVITC6hRRkXjcpIWgpejw {
	NI32 D1;
	NI16 D2;
	NI16 D3;
	tyArray__9cWG514ToTTjfTPLhXXV0IQ D4;
};
typedef N_STDCALL_PTR(NCSTRING, tyProc__zlYMfOxBV4VSYbrZMjd2xQ) (int family_p0, void* paddr_p1, NCSTRING pStringBuffer_p2, NI32 stringBufSize_p3);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(NI32, tyProc__5sqIMptsyAfPn3c9cPj4DOA) (NI16* lpFileName_p0);
typedef N_STDCALL_PTR(void, tyProc__Tjolzh1w2dIIpj3oCDGPFw) (NI32 dwMilliseconds_p0);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4594)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__k6kyf4Co79a84IkK9blFuQVA_2 = { 10 | NIM_STRLIT_FLAG, "Ws2_32.dll" };
static const NimStringV2 TM__k6kyf4Co79a84IkK9blFuQVA_3 = {10, (NimStrPayload*)&TM__k6kyf4Co79a84IkK9blFuQVA_2};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__k6kyf4Co79a84IkK9blFuQVA_6 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__k6kyf4Co79a84IkK9blFuQVA_7 = {8, (NimStrPayload*)&TM__k6kyf4Co79a84IkK9blFuQVA_6};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__k6kyf4Co79a84IkK9blFuQVA_8 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__k6kyf4Co79a84IkK9blFuQVA_9 = {8, (NimStrPayload*)&TM__k6kyf4Co79a84IkK9blFuQVA_8};
N_LIB_PRIVATE tyObject_GUID__gqVITC6hRRkXjcpIWgpejw WSAID_CONNECTEX__windowsZwinlean_u723 = {((NI32)631375801), ((NI16)-8717), ((NI16)18016), {((NI8)-114),
((NI8)-23),
((NI8)118),
((NI8)-27),
((NI8)-116),
((NI8)116),
((NI8)6),
((NI8)62)}
}
;
N_LIB_PRIVATE tyObject_GUID__gqVITC6hRRkXjcpIWgpejw WSAID_ACCEPTEX__windowsZwinlean_u724 = {((NI32)-1254720015), ((NI16)-13396), ((NI16)4559), {((NI8)-107),
((NI8)-54),
((NI8)0),
((NI8)-128),
((NI8)95),
((NI8)72),
((NI8)-95),
((NI8)-110)}
}
;
N_LIB_PRIVATE tyObject_GUID__gqVITC6hRRkXjcpIWgpejw WSAID_GETACCEPTEXSOCKADDRS__windowsZwinlean_u725 = {((NI32)-1254720014), ((NI16)-13396), ((NI16)4559), {((NI8)-107),
((NI8)-54),
((NI8)0),
((NI8)-128),
((NI8)95),
((NI8)72),
((NI8)-95),
((NI8)-110)}
}
;
N_LIB_PRIVATE tyProc__zlYMfOxBV4VSYbrZMjd2xQ inet_ntop_real__windowsZwinlean_u796 = NIM_NIL;
N_LIB_PRIVATE void* ws2__windowsZwinlean_u797;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4376;
static void* TM__k6kyf4Co79a84IkK9blFuQVA_4;
tyProc__5sqIMptsyAfPn3c9cPj4DOA Dl_1577058566_;
tyProc__Tjolzh1w2dIIpj3oCDGPFw Dl_1577058602_;
extern NIM_THREADVAR TFrame* framePtr__system_u2694;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4376);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2694 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2694).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2694;
	framePtr__system_u2694 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4594();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2694 = (*framePtr__system_u2694).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_Init000)(void) {
{
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("winlean", "K:\\Progz\\nim-2.2.6\\lib\\windows\\winlean.nim");
nimErr_ = nimErrorFlag();
	nimlf_(837, "K:\\Progz\\nim-2.2.6\\lib\\windows\\winlean.nim");	T1_ = (void*)0;
	T1_ = loadLib__pureZdynlib_u3(TM__k6kyf4Co79a84IkK9blFuQVA_3, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	ws2__windowsZwinlean_u797 = T1_;
	nimln_(838);	{
		void* T6_;
		if (!!((ws2__windowsZwinlean_u797 == NIM_NIL))) goto LA4_;
		nimln_(839);		T6_ = (void*)0;
		T6_ = symAddr__pureZdynlib_u74(ws2__windowsZwinlean_u797, "inet_ntop");
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		inet_ntop_real__windowsZwinlean_u796 = ((tyProc__zlYMfOxBV4VSYbrZMjd2xQ) (T6_));
	}
LA4_: ;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_DatInit000)(void) {
if (!((TM__k6kyf4Co79a84IkK9blFuQVA_4 = nimLoadLibrary(TM__k6kyf4Co79a84IkK9blFuQVA_7))
)) nimLoadLibraryError(TM__k6kyf4Co79a84IkK9blFuQVA_9);
	Dl_1577058566_ = (tyProc__5sqIMptsyAfPn3c9cPj4DOA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "GetFileAttributesW");
	Dl_1577058602_ = (tyProc__Tjolzh1w2dIIpj3oCDGPFw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "Sleep");
}

